/*
  Výpis z platobnej brány (Stripe, PayPal, GoPay, Comgate, Barion) ako bankový
  výpis.

  Brána je pre účtovníctvo samostatný „účet": prídu na ňu platby zákazníkov,
  strhne si z nich poplatok a zvyšok raz za čas pošle na bankový účet. Účtovník
  to dovtedy prepisoval z exportu brány ručne — riadok po riadku, s poplatkom
  zvlášť. Tu sa z exportu stanú pohyby v tvare, aký majú bankové výpisy, a
  ďalej idú tou istou cestou: do Pohody (dávka alebo camt.053), do Faktera na
  párovanie s faktúrami.

  Každý riadok brány dá:
    - platbu (príjem, označenie „Úhrada faktúry"),
    - poplatok ako samostatný výdaj („Bankový poplatok"),
    - a výber na bankový účet ako výdaj („Prevod medzi vlastnými účtami").

  Formáty sa poznávajú podľa hlavičky. Názvy stĺpcov sú podľa dokumentácie
  brán; PayPal a GoPay ich prekladajú do jazyka účtu, preto sa porovnávajú
  bez diakritiky a s viacerými názvami naraz.
*/
import { citajCsv, cisloZTextu, normalizuj } from "./import-prijatych";
import type { VypisPohyb } from "./export.server";
import type { Vypis } from "./vypis-pohyby";

export type Brana = "stripe" | "paypal" | "gopay" | "comgate" | "barion" | "iny";

export const NAZVY_BRAN: Record<Brana, string> = {
  stripe: "Stripe",
  paypal: "PayPal",
  gopay: "GoPay",
  comgate: "Comgate",
  barion: "Barion",
  iny: "Platobná brána",
};

/** Pohyb s identifikátorom z brány — podľa neho sa pri opakovanom nahraní nič nezdvojí. */
export type PohybBrany = VypisPohyb & { id: string };

export type VypisBrany = Omit<Vypis, "pohyby"> & {
  brana: Brana;
  pohyby: PohybBrany[];
  pocty: { platby: number; poplatky: number; vybery: number; vratenia: number };
  varovanie: string | null;
};

type Pole =
  | "id"
  | "datum"
  | "cas"
  | "brutto"
  | "poplatok"
  | "netto"
  | "suma"
  | "mena"
  | "typ"
  | "stav"
  | "meno"
  | "email"
  | "referencia"
  | "referencia2"
  | "popis"
  | "zostatok"
  | "datumPrevodu"
  | "prevedene"
  | "vsPrevodu";

type Stlpce = Partial<Record<Pole, number>>;

/** Hlavička na porovnanie: malé písmená, bez diakritiky, len písmená a číslice. */
export function holaHlavicka(v: unknown): string {
  return normalizuj(v)
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/** Názvy stĺpcov pre každé pole — prvý nájdený vyhráva. */
const NAZVY: Record<Pole, string[]> = {
  id: [
    "balance transaction id",
    "transaction id",
    "id transakcie",
    "id transakce",
    "kod transakcie",
    "id pohybu",
    "id comgate",
    "comgate id",
    "unique payment id generated by barion",
    "id",
  ],
  datum: [
    "created utc",
    "created",
    "date",
    "datum",
    "datum zaplaceni",
    "datum zaplatenia",
    "transaction time",
    "cas transakcie",
    "datum transakcie",
    "datum zalozeni",
  ],
  cas: ["time", "cas"],
  brutto: ["gross", "brutto", "hruba castka", "hruba suma", "amount", "potvrzena castka", "cena"],
  poplatok: ["fee", "poplatok", "poplatek", "poplatek celkem", "poplatok celkom"],
  netto: ["net", "netto", "cista castka", "cista suma"],
  suma: ["castka", "ciastka", "suma", "transaction amount", "suma transakcie"],
  mena: ["currency", "mena", "mena transakcie"],
  typ: ["reporting category", "type", "typ", "transaction type", "typ transakcie"],
  stav: ["status", "stav"],
  meno: [
    "name",
    "meno",
    "jmeno",
    "customer name",
    "protistrana",
    "customer beneficiary",
    "zakaznik",
  ],
  email: [
    "customer email",
    "from email address",
    "e mail platce",
    "email platce",
    "subjekt e mail",
    "e mail odosielatela",
  ],
  referencia: [
    "payment metadata order id",
    "order id metadata",
    "invoice number",
    "cislo faktury",
    "id objednavky vs",
    "variabilni symbol platby",
    "payment id generated by shop",
  ],
  referencia2: ["id od klienta", "transaction id generated by shop", "item id"],
  popis: ["description", "popis", "item title", "nazov polozky", "subject", "predmet"],
  zostatok: ["balance", "zostatok", "zustatek", "koncovy stav", "balance after transaction"],
  datumPrevodu: ["datum prevodu"],
  prevedene: ["prevedena castka"],
  vsPrevodu: ["variabilni symbol prevodu"],
};

function najdiStlpce(hlavicka: string[]): Stlpce {
  const h = hlavicka.map(holaHlavicka);
  const out: Stlpce = {};
  const pouzite = new Set<number>();
  for (const pole of Object.keys(NAZVY) as Pole[]) {
    for (const nazov of NAZVY[pole]) {
      const i = h.findIndex((x, idx) => !pouzite.has(idx) && x === nazov);
      if (i >= 0) {
        out[pole] = i;
        pouzite.add(i);
        break;
      }
    }
  }
  return out;
}

function rozpoznajBranu(hlavicka: string[]): Brana | null {
  const h = new Set(hlavicka.map(holaHlavicka));
  const ma = (...n: string[]) => n.some((x) => h.has(x));
  if (ma("balance transaction id") && ma("reporting category")) return "stripe";
  if (ma("id") && ma("net") && ma("created utc", "created")) return "stripe";
  if (ma("id") && ma("created utc") && ma("amount") && ma("status")) return "stripe";
  if (
    ma("transaction id", "id transakcie", "id transakce", "kod transakcie") &&
    ma("gross", "brutto", "hruba castka", "hruba suma")
  )
    return "paypal";
  if (ma("id pohybu") && ma("castka", "ciastka")) return "gopay";
  if (ma("id comgate", "comgate id")) return "comgate";
  if (
    ma("unique payment id generated by barion") ||
    (ma("transaction time") && ma("transaction amount"))
  )
    return "barion";
  return null;
}

/*
  Dátum. PayPal ho píše v tvare podľa krajiny účtu — americký účet
  mesiac/deň/rok, európsky deň/mesiac/rok alebo s bodkami. Rozhoduje celý súbor:
  ak niekde stojí na prvom mieste číslo nad 12, je to deň.
*/
export function citacDatumu(vzorky: string[]): (v: string) => string | null {
  const lomky = vzorky
    .map((v) => /^(\d{1,2})\/(\d{1,2})\/(\d{4})/.exec(v.trim()))
    .filter(Boolean) as RegExpExecArray[];
  const mesiacPrvy = !lomky.some((m) => Number(m[1]) > 12) && lomky.some((m) => Number(m[2]) > 12);
  return (v: string) => {
    const s = String(v ?? "").trim();
    let m = /^(\d{4})-(\d{2})-(\d{2})/.exec(s);
    if (m) return `${m[1]}-${m[2]}-${m[3]}`;
    m = /^(\d{1,2})\/(\d{1,2})\/(\d{4})/.exec(s);
    if (m) {
      const [d, mes] = mesiacPrvy ? [m[2]!, m[1]!] : [m[1]!, m[2]!];
      return `${m[3]}-${mes.padStart(2, "0")}-${d.padStart(2, "0")}`;
    }
    m = /^(\d{1,2})\s*\.\s*(\d{1,2})\s*\.\s*(\d{4})/.exec(s);
    if (m) return `${m[3]}-${m[2]!.padStart(2, "0")}-${m[1]!.padStart(2, "0")}`;
    return null;
  };
}

/** Variabilný symbol z referencie: „WC-1234", „Order #1234" → „1234". */
export function vsZReferencie(...texty: (string | null | undefined)[]): string | null {
  for (const t of texty) {
    const s = String(t ?? "").trim();
    if (!s) continue;
    const cista = s.replace(/\s/g, "");
    if (/^\d{1,10}$/.test(cista)) return cista;
    const m =
      /(?:\b(?:order|ord|objedn[aá]vk[ayu]|obj\.|invoice|inv|fakt[uú]r[ay]|wc)|#)\s*[-:#]?\s*(?:č\.?\s*)?#?\s*(\d{2,10})\b/i.exec(
        s,
      );
    if (m) return m[1]!;
  }
  return null;
}

const hole = (v: unknown) => normalizuj(v);

type Druh = "platba" | "poplatok" | "vyber" | "vratenie" | "iny";

/** Čím riadok je, podľa typu z brány. */
function druhRiadku(brana: Brana, typ: string, suma: number): Druh {
  const t = hole(typ);
  if (brana === "stripe") {
    if (/^payout|^transfer/.test(t)) return "vyber";
    if (/refund|dispute/.test(t)) return "vratenie";
    if (/fee|tax/.test(t)) return "poplatok";
    if (/charge|payment/.test(t)) return "platba";
    return suma >= 0 ? "platba" : "iny";
  }
  if (
    /withdraw|vyber|vyplat|prevod na (bankovy )?ucet|transfer to bank|bank deposit|payout|vyuctovani/.test(
      t,
    )
  )
    return "vyber";
  if (/refund|vraten|vracen|chargeback|reklamac/.test(t)) return "vratenie";
  if (/fee|poplat/.test(t)) return "poplatok";
  // Prevod medzi menami v PayPale nie je platba od zákazníka.
  if (/conversion|konverz|prevod men|vymena men|smena/.test(t)) return "iny";
  return suma >= 0 ? "platba" : "iny";
}

/** Riadky PayPalu, ktoré nie sú pohybom peňazí (zablokovanie, čakajúca platba). */
function vynechat(brana: Brana, typ: string, stav: string): boolean {
  const s = hole(stav);
  /*
    Stripe píše „pending" aj pri platbe, ktorá prebehla a len ešte nie je
    k dispozícii na výber — tá do výpisu patrí. Vynechať treba len neúspešné.
  */
  if (brana === "stripe") return /failed|canceled|cancelled|blocked|incomplete/.test(s);
  if (
    /pending|denied|reversed|cancel|zrusen|cakajuc|ceka|zamietnut|odmitnut|stornovan|failed|neuspes/.test(
      s,
    )
  )
    return true;
  const t = hole(typ);
  if (brana === "paypal" && /hold|release|zadrz|blokov|authorization|autoriz/.test(t)) return true;
  return false;
}

export function jeVypisBrany(obsah: string): boolean {
  const riadky = citajCsv(obsah).slice(0, 15);
  return riadky.some((r) => rozpoznajBranu(r) !== null);
}

/**
 * Prečíta export brány. Hodí chybu, keď súbor nie je export žiadnej známej
 * brány — radšej to, než si domýšľať stĺpce a vyrobiť zlý výpis.
 */
export function citajVypisBrany(obsah: string): VypisBrany {
  const vsetky = citajCsv(obsah);
  const hlavickaIdx = vsetky.slice(0, 15).findIndex((r) => rozpoznajBranu(r) !== null);
  if (hlavickaIdx < 0) {
    throw new Error(
      "Súbor nevyzerá ako export platobnej brány. Podporujeme Stripe, PayPal, GoPay, Comgate a Barion (CSV).",
    );
  }
  const hlavicka = vsetky[hlavickaIdx]!;
  const brana = rozpoznajBranu(hlavicka)!;
  const s = najdiStlpce(hlavicka);
  const riadky = vsetky.slice(hlavickaIdx + 1).filter((r) => r.some((b) => b.trim()));
  const bunka = (r: string[], p: Pole) => (s[p] === undefined ? "" : String(r[s[p]!] ?? "").trim());
  const datum = citacDatumu(riadky.map((r) => bunka(r, "datum")));

  // Hlavná mena: výpis je v jednej mene, ostatné sa vynechajú a povie sa to.
  const pocetMien = new Map<string, number>();
  for (const r of riadky) {
    const m = (bunka(r, "mena") || "EUR").toUpperCase();
    pocetMien.set(m, (pocetMien.get(m) ?? 0) + 1);
  }
  const mena = [...pocetMien.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? "EUR";

  const pohyby: PohybBrany[] = [];
  const pocty = { platby: 0, poplatky: 0, vybery: 0, vratenia: 0 };
  let inaMena = 0;
  let bezDatumu = 0;
  const vyplaty = new Map<string, { datum: string; suma: number; vs: string | null }>();
  const nazov = NAZVY_BRAN[brana];

  riadky.forEach((r, i) => {
    const m = (bunka(r, "mena") || mena).toUpperCase();
    if (m !== mena) {
      inaMena++;
      return;
    }
    const typ = bunka(r, "typ");
    if (vynechat(brana, typ, bunka(r, "stav"))) return;
    const d = datum(bunka(r, "datum"));
    if (!d) {
      bezDatumu++;
      return;
    }
    const id = bunka(r, "id") || `${d}-${i}`;
    const brutto = cisloZTextu(bunka(r, "brutto")) ?? cisloZTextu(bunka(r, "suma"));
    if (brutto === null) return;
    const poplatokSurovy = cisloZTextu(bunka(r, "poplatok")) ?? 0;
    const netto = cisloZTextu(bunka(r, "netto"));
    /*
      Znamienko poplatku: Stripe a Comgate ho píšu kladne (koľko si brána vzala),
      PayPal záporne (pohyb na účte). Rozhodne netto — keď ho riadok má.
    */
    const poplatok =
      netto !== null && Math.abs(brutto + poplatokSurovy - netto) < 0.011
        ? poplatokSurovy
        : -Math.abs(poplatokSurovy);
    const druh = druhRiadku(brana, typ, brutto);
    const meno = bunka(r, "meno") || bunka(r, "email") || null;
    const referencia = bunka(r, "referencia");
    const referencia2 = bunka(r, "referencia2");
    const popisZBrany = bunka(r, "popis");
    const vs =
      druh === "platba" || druh === "vratenie"
        ? vsZReferencie(referencia, referencia2, popisZBrany)
        : null;
    const zostatok = cisloZTextu(bunka(r, "zostatok"));

    const pridaj = (suma: number, o: Partial<PohybBrany> & { id: string }) => {
      if (Math.abs(suma) < 0.005) return;
      pohyby.push({
        datum: d,
        suma: Math.abs(Math.round(suma * 100) / 100),
        smer: suma < 0 ? "vydaj" : "prijem",
        popis: null,
        protistrana: null,
        protiucet: null,
        zostatok: null,
        vs: null,
        ks: null,
        ss: null,
        oznacenie: null,
        ...o,
      });
    };

    if (druh === "vyber") {
      pocty.vybery++;
      pridaj(-Math.abs(brutto), {
        id: `${id}:vyber`,
        popis: `${nazov}: výber na bankový účet${popisZBrany ? ` — ${popisZBrany}` : ""}`,
        oznacenie: "prevod",
        zostatok,
      });
      return;
    }
    if (druh === "poplatok") {
      pocty.poplatky++;
      pridaj(brutto < 0 ? brutto : -Math.abs(brutto), {
        id: `${id}:poplatok`,
        popis: `${nazov}: ${popisZBrany || "poplatok"}`,
        protistrana: nazov,
        oznacenie: "poplatok",
        zostatok,
      });
      return;
    }

    if (druh === "platba") pocty.platby++;
    if (druh === "vratenie") pocty.vratenia++;
    const maPoplatok = Math.abs(poplatok) >= 0.005;
    pridaj(brutto, {
      id: `${id}:platba`,
      popis: [
        `${nazov}:`,
        popisZBrany || (druh === "vratenie" ? "vrátenie platby" : "platba"),
        referencia && `(${referencia})`,
      ]
        .filter(Boolean)
        .join(" "),
      protistrana: meno,
      vs,
      oznacenie: druh === "iny" ? "ine" : "faktura",
      zostatok: maPoplatok ? null : zostatok,
    });
    if (maPoplatok) {
      pocty.poplatky++;
      pridaj(poplatok, {
        id: `${id}:poplatok`,
        popis: `${nazov}: poplatok k platbe ${referencia || id}`,
        protistrana: nazov,
        oznacenie: "poplatok",
        zostatok,
      });
    }

    // Comgate nemá riadky výberov — výplata je pri každej platbe (dátum a suma prevodu).
    const datumPrevodu = datum(bunka(r, "datumPrevodu"));
    const prevedene = cisloZTextu(bunka(r, "prevedene"));
    if (datumPrevodu && prevedene) {
      const vsP = bunka(r, "vsPrevodu") || null;
      const kluc = `${datumPrevodu}|${vsP ?? ""}`;
      const v = vyplaty.get(kluc) ?? { datum: datumPrevodu, suma: 0, vs: vsP };
      v.suma += prevedene;
      vyplaty.set(kluc, v);
    }
  });

  for (const [kluc, v] of vyplaty) {
    pocty.vybery++;
    pohyby.push({
      id: `vyplata:${kluc}`,
      datum: v.datum,
      suma: Math.round(Math.abs(v.suma) * 100) / 100,
      smer: "vydaj",
      popis: `${nazov}: výber na bankový účet${v.vs ? ` (VS ${v.vs})` : ""}`,
      protistrana: null,
      protiucet: null,
      zostatok: null,
      vs: v.vs ? v.vs.replace(/\D/g, "").slice(0, 10) || null : null,
      ks: null,
      ss: null,
      oznacenie: "prevod",
    });
  }

  pohyby.sort((a, b) => a.datum.localeCompare(b.datum));
  const varovania = [
    inaMena &&
      `${inaMena} ${inaMena === 1 ? "pohyb" : "pohybov"} v inej mene než ${mena} sa vynechalo — výpis je vždy v jednej mene; ostatné nahrajte zvlášť.`,
    bezDatumu &&
      `${bezDatumu} ${bezDatumu === 1 ? "riadok" : "riadkov"} bez čitateľného dátumu sa vynechalo.`,
    brana === "stripe" &&
      s.netto === undefined &&
      "Export platieb zo Stripe neobsahuje výbery na účet. Úplný výpis dá Stripe v Reports → Balance → Itemized balance change (CSV).",
  ].filter(Boolean) as string[];

  return {
    brana,
    cisloVypisu: null,
    ucet: nazov,
    mena,
    datumVypisu: pohyby[pohyby.length - 1]?.datum ?? null,
    pohyby,
    pocty,
    varovanie: varovania.length ? varovania.join(" ") : null,
  };
}

/** Text súboru — exporty z českých brán bývajú vo Windows-1250. */
export function dekodujCsv(bajty: ArrayBuffer | Uint8Array): string {
  const u8 = bajty instanceof Uint8Array ? bajty : new Uint8Array(bajty);
  try {
    return new TextDecoder("utf-8", { fatal: true }).decode(u8);
  } catch {
    return new TextDecoder("windows-1250").decode(u8);
  }
}
