import type { Kluc } from "./sk";

/** Čeština. Čo tu chýba, spadne na slovenčinu. */
export const cs: Partial<Record<Kluc, string>> = {
  "tab.skener": "Skener",
  "tab.faktury": "Faktury",
  "tab.vytvorit": "Vytvořit",
  "tab.banka": "Banka",
  "tab.jazda": "Kniha jízd",
  "tab.navigacia": "Hlavní navigace",

  "panel.nastavenia": "Nastavení",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Změnit firmu",
  "panel.bezFirmy": "Bez firmy",
  "panel.prehladAgend": "Přehled agend",
  "panel.vystaveneFaktury": "Vystavené faktury",
  "panel.cenovePonuky": "Cenové nabídky",
  "panel.prijateDoklady": "Přijaté doklady",
  "panel.pomoc": "Nápověda",
  "panel.nastavenieAplikacie": "Nastavení aplikace",
  "panel.navody": "Návody k Fakteru",
  "panel.otvoriVPrehliadaci": "Otevře se v prohlížeči",
  "panel.blocky": "Účtenky a pokladna",
  "panel.nahlasitChybu": "Nahlásit chybu nebo návrh",
  "panel.otvoritNaWebe": "Otevřít Faktero na webu",
  "panel.pravne": "Právní dokumenty",
  "panel.odhlasit": "Odhlásit se",
  "panel.zavriet": "Zavřít",
  "panel.jazyk": "Jazyk",

  "domov.novaFaktura": "Nová faktura",
  "domov.novaFakturaPopis": "Odběratel, položky, splatnost — a rovnou odeslat",
  "domov.vystaveneFaktury": "Vystavené faktury",
  "domov.vystaveneFakturyPopis": "Kdo ještě nezaplatil, PDF a odeslání",
  "domov.blocek": "Účtenka s QR kódem",
  "domov.blocekPopis": "Načte se z Finanční správy i s položkami",
  "domov.fakturaPdf": "Faktura v PDF",
  "domov.fakturaPdfPopis": "Vyberte soubor z telefonu nebo z cloudu",
  "domov.viacstranovy": "Vícestránkový doklad",
  "domov.viacstranovyPopis": "Stranu po straně, uloží se jako jedno PDF",
  "domov.prijateDoklady": "Přijaté doklady",
  "domov.prijateDokladyPopis": "Účtenky a faktury, které jste už naskenovali",
  "domov.pohybyNaUcte": "Pohyby na účtu",
  "domov.pohybyNaUctePopis": "Jestli přišly peníze — zůstatek a poslední platby",
  "domov.novaJazda": "Nová jízda",
  "domov.novaJazdaPopis": "Kilometry změří telefon, stačí start a stop",

  "jazdy.historia": "Historie jízd",
  "jazdy.charakter": "Charakter jízdy",
  "jazdy.sluzobna": "Služební",
  "jazdy.sukromna": "Soukromá",
  "jazdy.oznacenaSukromna": "Označena jako soukromá.",
  "jazdy.oznacenaSluzobna": "Označena jako služební.",
  "jazdy.jazda": "Jízda",
  "jazdy.spolu": "Celkem",
  "jazdy.starsie": "Starší jízdy",
  "jazdy.ziadne": "Zatím žádné jízdy",

  "ponuky.nazov": "Cenové nabídky",
  "ponuky.nova": "Nová nabídka",
  "ponuky.novaDlha": "Nová cenová nabídka",
  "ponuky.ziadne": "Zatím žádná cenová nabídka",
  "ponuky.ziadnePopis":
    "Nabídku uděláte stejně jako fakturu — a když ji zákazník přijme, jedním ťuknutím z ní faktura vznikne.",
  "ponuky.vytvorit": "Vytvořit nabídku",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Sdílet",
  "ponuky.odoslat": "Odeslat",
  "ponuky.naFakturu": "Na fakturu",
  "ponuky.platiDo": "platí do",
  "ponuky.stav.vyfakturovana": "Vyfakturovaná",
  "ponuky.stav.zamietnuta": "Zamítnutá",
  "ponuky.stav.prijata": "Přijatá",
  "ponuky.stav.poPlatnosti": "Po platnosti",
  "ponuky.stav.odoslana": "Odeslaná",
  "ponuky.stav.navrh": "Návrh",
  "ponuky.odberatel": "Odběratel",
  "ponuky.polozky": "Položky",
  "ponuky.pridajPolozku": "Přidat položku",
  "ponuky.vystavena": "Vystavena",
  "ponuky.poznamka": "Poznámka",
  "ponuky.zaklad": "Základ",
  "ponuky.dph": "DPH",
  "ponuky.hladatOdberatela": "Hledat odběratele…",
  "ponuky.novyOdberatel": "Nový odběratel",
  "ponuky.nikNenajdeny": "Nikdo se nenašel.",
  "ponuky.zmenit": "změnit",

  "domov.skupina.fakturacia": "Fakturace",
  "domov.skupina.skenovanie": "Skenování dokladů",
  "domov.skupina.banka": "Banka",
  "domov.skupina.jazdy": "Kniha jízd",

  /* vystavené faktúry */
  "faktury.nazov": "Vystavené faktury",
  "faktury.hladat": "Hledat číslo nebo odběratele",
  "faktury.nacitavam": "Načítám faktury…",
  "faktury.ziadne": "Zatím žádné faktury",
  "faktury.vystavPrvu": "Vystavit první fakturu",
  "faktury.nicSaNenaslo": "Nic se nenašlo",
  "faktury.bezOdberatela": "Bez odběratele",
  "faktury.stav.navrh": "Návrh",
  "faktury.stav.vystavena": "Vystavená",
  "faktury.stav.odoslana": "Odeslaná",
  "faktury.stav.uhradena": "Uhrazená",
  "faktury.stav.neuhradena": "Neuhrazená",
  "faktury.stav.splatna": "Splatná",
  "faktury.stav.poSplatnosti": "Po splatnosti",
  "faktury.stav.stornovana": "Stornovaná",
  "faktury.otvoritPdf": "Otevřít PDF",
  "faktury.zdielat": "Sdílet fakturu",
  "faktury.zdielatPopis": "Pošlete ji přes WhatsApp, Messenger nebo uložte do souborů",
  "faktury.poslatEmailom": "Poslat e-mailem",
  "faktury.oznacitUhradenu": "Označit jako uhrazenou",
  "faktury.oznacitPopis": "Když platba přišla mimo párování s bankou",
  "faktury.oznacenaUhradena": "Označena jako uhrazená",
  "faktury.upravit": "Upravit fakturu",
  "faktury.upravitPopis": "Položky, data i poznámka",
  "faktury.zmazat": "Smazat fakturu",
  "faktury.zmazatPopis":
    "Zmizí ze seznamu, ale číslo zůstává obsazené — v číselné řadě nevznikne díra.",
  "faktury.zmazatKratke": "Smazat",
  "faktury.ponechat": "Ponechat",
  "faktury.mazem": "Mažu…",
  "faktury.naPrezretie": "Faktura k prohlédnutí",
  "faktury.bezPripojenia": "Bez připojení — zobrazeny naposledy načtené faktury.",
  "faktury.bezPripojeniaNacitanie": "Bez připojení se faktury nedají načíst",
  "faktury.odlozenaVystavena": "Odložená faktura je vystavená.",
  "faktury.odosluSaSamy": "Odešlou se samy, jakmile bude signál. Nemusíte na to myslet.",
  "faktury.chybaNacitania": "Faktury se nepodařilo načíst.",
  "faktury.chybaMazania": "Fakturu se nepodařilo smazat.",
  "faktury.chybaPdf": "PDF se nepodařilo připravit.",
  "faktury.chybaZdielania": "Sdílení selhalo.",
  "faktury.chybaUpomienky": "Upomínku se nepodařilo odeslat.",

  /* nová faktúra */
  "nf.komuFakturujete": "Komu fakturujete?",
  "nf.zaCoFakturujete": "Za co fakturujete?",
  "nf.skontrolujte": "Zkontrolujte fakturu",
  "nf.skontrolujteZalohovu": "Zkontrolujte zálohovou",
  "nf.krok": "Krok {n} ze 3",
  "nf.krokZalohova": "Krok 1 ze 3 · zálohová",
  "nf.faktura": "Faktura",
  "nf.zalohova": "Zálohová",
  "nf.odberatel": "Odběratel",
  "nf.hladatOdberatela": "Hledat odběratele",
  "nf.novyOdberatel": "Nový odběratel",
  "nf.ziadnyOdberatel": "Zatím nemáte žádného odběratele.",
  "nf.nicSaNenaslo": "Nic se nenašlo.",
  "nf.nacitavamOdberatelov": "Načítám odběratele…",
  "nf.nazov": "Název",
  "nf.zadajteNazov": "Zadejte název odběratele.",
  "nf.podlaIco": "Podle IČO se doplní název i adresa",
  "nf.hladamVRegistri": "Hledám v registru…",
  "nf.udajeDoplnene": "Údaje doplněny z registru",
  "nf.psc": "PSČ",
  "nf.email": "Na tento e-mail se dá faktura hned odeslat",
  "nf.odberatelPridany": "Odběratel přidán",
  "nf.chybaOdberatela": "Odběratele se nepodařilo uložit.",
  "nf.polozky": "Položky",
  "nf.nazovPolozky": "Název položky",
  "nf.mnozstvo": "Množství",
  "nf.pridajtePolozku": "Přidejte položku",
  "nf.odstranitPolozku": "Odstranit položku",
  "nf.zCennika": "Z ceníku",
  "nf.vlastna": "Vlastní",
  "nf.cennik": "Ceník",
  "nf.hladatPolozku": "Hledat položku",
  "nf.zopakovatPoslednu": "Zopakovat poslední fakturu",
  "nf.splatnost": "Splatnost",
  "nf.splatnostSkor": "Splatnost nemůže být dříve než vystavení.",
  "nf.sposobUhrady": "Způsob úhrady",
  "nf.hotovost": "Hotovost",
  "nf.poznamkaNad": "Poznámka nad položkami",
  "nf.poznamkaPod": "Poznámka pod položkami",
  "nf.priklad": "Například: podle objednávky č. 2026/114",
  "nf.zaklad": "Základ",
  "nf.naUhradu": "K úhradě",
  "nf.dalej": "Dále",
  "nf.zrusit": "Zrušit",
  "nf.zavriet": "Zavřít",
  "nf.ulozitPokracovat": "Uložit a pokračovat",
  "nf.ulozitZmeny": "Uložit změny",
  "nf.ukladam": "Ukládám…",
  "nf.ukladamZmeny": "Ukládám změny…",
  "nf.vystavit": "Vystavit fakturu",
  "nf.vystavitZalohovu": "Vystavit zálohovou fakturu",
  "nf.vystavujem": "Vystavuji fakturu…",
  "nf.vystavena": "Faktura vystavena",
  "nf.maCislo": "Faktura má přidělené číslo",
  "nf.odlozena": "Faktura je odložená v telefonu",
  "nf.naPrezretie": "Faktura k prohlédnutí",
  "nf.otvoritPdf": "Otevřít PDF",
  "nf.zdielat": "Sdílet fakturu",
  "nf.zdielatPopis": "Pošlete ji přes WhatsApp, Messenger nebo uložte do souborů",
  "nf.poslatEmailom": "Poslat e-mailem",
  "nf.odoslane": "Odesláno",
  "nf.odosielam": "Odesílám fakturu…",
  "nf.bezEmailu":
    "Odběratel nemá e-mail, takže fakturu nelze odeslat. Doplňte ho v kartě odběratele.",
  "nf.zalohy": "Nezúčtované zálohy tohoto odběratele",
  "nf.hladamZalohy": "Hledám zálohy…",
  "nf.ziadnaZaloha": "Žádná zálohová faktura k zúčtování",
  "nf.pridatZalohovu": "Přidat zálohovou fakturu",
  "nf.bezPripojenia": "Bez připojení — pracuji s naposledy načtenými údaji.",
  "nf.bezPripojeniaVystavit":
    "Bez připojení a bez uložených odběratelů se faktura vystavit nedá. Otevřete tuto obrazovku jednou s internetem.",
  "nf.zalohovaBezPripojenia": "Zálohovou fakturu se bez připojení vystavit nedá.",
  "nf.opravaBezPripojenia": "K opravě faktury je potřeba připojení.",
  "nf.chybaPodkladov": "Podklady se nepodařilo načíst.",
  "nf.chybaNacitania": "Fakturu se nepodařilo načíst.",
  "nf.chybaVystavenia": "Fakturu se nepodařilo vystavit.",
  "nf.chybaZmien": "Změny se nepodařilo uložit.",
  "nf.chybaPdf": "PDF se nepodařilo připravit.",
  "nf.chybaZdielania": "Sdílení selhalo.",

  /* prijaté doklady a banka */
  "pd.nazov": "Přijaté doklady",
  "pd.hladat": "Hledat dodavatele nebo číslo",
  "pd.nacitavam": "Načítám doklady…",
  "pd.ziadne": "Zatím žádné doklady",
  "pd.ziadnePopis": "Naskenované účtenky a faktury se objeví tady.",
  "pd.nicSaNenaslo": "Nic se nenašlo",
  "pd.skusteInak": "Zkuste hledat jinak.",
  "pd.bezDodavatela": "Bez dodavatele",
  "pd.neprecitany": "Nepřečtený doklad",
  "pd.zFinancnejSpravy": "Z Finanční správy",
  "pd.sQrKodom": "· s QR kódem",
  "pd.cisloDokladu": "Číslo dokladu",
  "pd.poznamka": "Poznámka",
  "pd.sposobUhrady": "Způsob úhrady",
  "pd.hotovost": "Hotovost",
  "pd.kartou": "Kartou",
  "pd.prevodom": "Převodem",
  "pd.sposobZmeneny": "Způsob úhrady změněn",
  "pd.otvoritPdf": "Otevřít PDF",
  "pd.nacitavamPrilohu": "Načítám přílohu…",
  "pd.presunut": "Přesunout mezi přijaté faktury",
  "pd.presuvam": "Přesouvám…",
  "pd.presunuty": "Doklad je mezi přijatými fakturami.",
  "pd.zmazat": "Smazat doklad",
  "pd.zmazatKratke": "Smazat",
  "pd.naozajZmazat": "Opravdu smazat tento doklad?",
  "pd.nedaSaVratit": "Vrátit se to nedá.",
  "pd.zmazany": "Doklad smazán",
  "pd.ponechat": "Ponechat",
  "pd.zrusit": "Zrušit",
  "pd.sparovat": "Spárovat",
  "pd.anoPatriKSebe": "Ano, patří k sobě",
  "pd.uhradenyZUctu": "Doklad označen za uhrazený z účtu.",
  "pd.parovanieZrusene": "Párování zrušeno.",
  "pd.chybaParovania": "Spárovat se to nepodařilo.",
  "pd.chybaZrusenia": "Zrušit se to nepodařilo.",
  "pd.chybaNacitania": "Doklady se nepodařilo načíst.",
  "pd.bezPripojenia": "Bez připojení se doklady nedají načíst",
  "pd.odlozeneOdoslu": "Odložené účtenky se odešlou samy, jakmile se vrátí signál.",
  "pd.bezSignalu": "Zatím bez signálu — zkusím to znovu sám.",
  "pd.zahodit": "Zahodit odložený doklad",
  "pd.odoslat": "Odeslat",
  "banka.ucet": "Účet",
  "banka.vsetky": "Všechny",
  "banka.nacitavam": "Načítám pohyby…",
  "banka.ziadnePohyby": "Zatím žádné pohyby",
  "banka.stiahnut": "Stáhnout z banky",
  "banka.stahujem": "Stahuji z banky…",
  "banka.ziadneNove": "Žádné nové pohyby.",
  "banka.prijataPlatba": "Přijatá platba",
  "banka.odchadzajucaPlatba": "Odchozí platba",
  "banka.dnes": "Dnes",
  "banka.vcera": "Včera",
  "banka.nesynchronizovane": "zatím nesynchronizováno",
  "banka.bezUctu": "Firma nemá připojený bankovní účet",
  "banka.pripojenieNaWebe":
    "Účet se připojuje na webu — banka při tom vyžaduje přihlášení a souhlas, který se v telefonu dobře vyřídit nedá.",
  "banka.bezPripojenia": "Bez připojení se účty nedají načíst",
  "banka.lenSoSignalom":
    "Zůstatky a pohyby se dají prohlédnout, jen když je signál — z telefonu se nikam neukládají.",
  "banka.neodpovedala": "Banka teď neodpověděla. Zkuste to za chvíli.",
  "banka.chybaNacitania": "Pohyby se nepodařilo načíst.",

  "spolocne.spat": "Zpět",
  "spolocne.ulozit": "Uložit",
  "spolocne.zrusit": "Zrušit",
  "spolocne.nacitavam": "Načítám…",
  "spolocne.km": "km",
};
