import type { Kluc } from "./sk";

/** Čeština. Čo tu chýba, spadne na slovenčinu. */
export const cs: Partial<Record<Kluc, string>> = {
  "tab.skener": "Skener",
  "tab.faktury": "Faktury",
  "tab.vytvorit": "Vytvořit",
  "tab.banka": "Banka",
  "tab.jazda": "Kniha jízd",
  "tab.navigacia": "Hlavní navigace",

  "panel.nastavenia": "Nastavení",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Změnit firmu",
  "panel.bezFirmy": "Bez firmy",
  "panel.prehladAgend": "Přehled agend",
  "panel.vystaveneFaktury": "Vystavené faktury",
  "panel.cenovePonuky": "Cenové nabídky",
  "panel.prijateDoklady": "Přijaté doklady",
  "panel.pomoc": "Nápověda",
  "panel.nastavenieAplikacie": "Nastavení aplikace",
  "panel.navody": "Návody k Fakteru",
  "panel.otvoriVPrehliadaci": "Otevře se v prohlížeči",
  "panel.blocky": "Účtenky a pokladna",
  "panel.nahlasitChybu": "Nahlásit chybu nebo návrh",
  "panel.otvoritNaWebe": "Otevřít Faktero na webu",
  "panel.pravne": "Právní dokumenty",
  "panel.odhlasit": "Odhlásit se",
  "panel.zavriet": "Zavřít",
  "panel.jazyk": "Jazyk",

  "domov.novaFaktura": "Nová faktura",
  "domov.novaFakturaPopis": "Odběratel, položky, splatnost — a rovnou odeslat",
  "domov.vystaveneFaktury": "Vystavené faktury",
  "domov.vystaveneFakturyPopis": "Kdo ještě nezaplatil, PDF a odeslání",
  "domov.blocek": "Účtenka s QR kódem",
  "domov.blocekPopis": "Načte se z Finanční správy i s položkami",
  "domov.fakturaPdf": "Faktura v PDF",
  "domov.fakturaPdfPopis": "Vyberte soubor z telefonu nebo z cloudu",
  "domov.viacstranovy": "Vícestránkový doklad",
  "domov.viacstranovyPopis": "Stranu po straně, uloží se jako jedno PDF",
  "domov.prijateDoklady": "Přijaté doklady",
  "domov.prijateDokladyPopis": "Účtenky a faktury, které jste už naskenovali",
  "domov.pohybyNaUcte": "Pohyby na účtu",
  "domov.pohybyNaUctePopis": "Jestli přišly peníze — zůstatek a poslední platby",
  "domov.novaJazda": "Nová jízda",
  "domov.novaJazdaPopis": "Kilometry změří telefon, stačí start a stop",

  "jazdy.historia": "Historie jízd",
  "jazdy.charakter": "Charakter jízdy",
  "jazdy.sluzobna": "Služební",
  "jazdy.sukromna": "Soukromá",
  "jazdy.oznacenaSukromna": "Označena jako soukromá.",
  "jazdy.oznacenaSluzobna": "Označena jako služební.",
  "jazdy.jazda": "Jízda",
  "jazdy.spolu": "Celkem",
  "jazdy.starsie": "Starší jízdy",
  "jazdy.ziadne": "Zatím žádné jízdy",

  "ponuky.nazov": "Cenové nabídky",
  "ponuky.nova": "Nová nabídka",
  "ponuky.novaDlha": "Nová cenová nabídka",
  "ponuky.ziadne": "Zatím žádná cenová nabídka",
  "ponuky.ziadnePopis":
    "Nabídku uděláte stejně jako fakturu — a když ji zákazník přijme, jedním ťuknutím z ní faktura vznikne.",
  "ponuky.vytvorit": "Vytvořit nabídku",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Sdílet",
  "ponuky.odoslat": "Odeslat",
  "ponuky.naFakturu": "Na fakturu",
  "ponuky.platiDo": "platí do",
  "ponuky.stav.vyfakturovana": "Vyfakturovaná",
  "ponuky.stav.zamietnuta": "Zamítnutá",
  "ponuky.stav.prijata": "Přijatá",
  "ponuky.stav.poPlatnosti": "Po platnosti",
  "ponuky.stav.odoslana": "Odeslaná",
  "ponuky.stav.navrh": "Návrh",
  "ponuky.odberatel": "Odběratel",
  "ponuky.polozky": "Položky",
  "ponuky.pridajPolozku": "Přidat položku",
  "ponuky.vystavena": "Vystavena",
  "ponuky.poznamka": "Poznámka",
  "ponuky.zaklad": "Základ",
  "ponuky.dph": "DPH",
  "ponuky.hladatOdberatela": "Hledat odběratele…",
  "ponuky.novyOdberatel": "Nový odběratel",
  "ponuky.nikNenajdeny": "Nikdo se nenašel.",
  "ponuky.zmenit": "změnit",

  "domov.skupina.fakturacia": "Fakturace",
  "domov.skupina.skenovanie": "Skenování dokladů",
  "domov.skupina.banka": "Banka",
  "domov.skupina.jazdy": "Kniha jízd",

  /* vystavené faktúry */
  "faktury.nazov": "Vystavené faktury",
  "faktury.hladat": "Hledat číslo nebo odběratele",
  "faktury.nacitavam": "Načítám faktury…",
  "faktury.ziadne": "Zatím žádné faktury",
  "faktury.vystavPrvu": "Vystavit první fakturu",
  "faktury.nicSaNenaslo": "Nic se nenašlo",
  "faktury.bezOdberatela": "Bez odběratele",
  "faktury.stav.navrh": "Návrh",
  "faktury.stav.vystavena": "Vystavená",
  "faktury.stav.odoslana": "Odeslaná",
  "faktury.stav.uhradena": "Uhrazená",
  "faktury.stav.neuhradena": "Neuhrazená",
  "faktury.stav.splatna": "Splatná",
  "faktury.stav.poSplatnosti": "Po splatnosti",
  "faktury.stav.stornovana": "Stornovaná",
  "faktury.otvoritPdf": "Otevřít PDF",
  "faktury.zdielat": "Sdílet fakturu",
  "faktury.zdielatPopis": "Pošlete ji přes WhatsApp, Messenger nebo uložte do souborů",
  "faktury.poslatEmailom": "Poslat e-mailem",
  "faktury.oznacitUhradenu": "Označit jako uhrazenou",
  "faktury.oznacitPopis": "Když platba přišla mimo párování s bankou",
  "faktury.oznacenaUhradena": "Označena jako uhrazená",
  "faktury.upravit": "Upravit fakturu",
  "faktury.upravitPopis": "Položky, data i poznámka",
  "faktury.zmazat": "Smazat fakturu",
  "faktury.zmazatPopis":
    "Zmizí ze seznamu, ale číslo zůstává obsazené — v číselné řadě nevznikne díra.",
  "faktury.zmazatKratke": "Smazat",
  "faktury.ponechat": "Ponechat",
  "faktury.mazem": "Mažu…",
  "faktury.naPrezretie": "Faktura k prohlédnutí",
  "faktury.bezPripojenia": "Bez připojení — zobrazeny naposledy načtené faktury.",
  "faktury.bezPripojeniaNacitanie": "Bez připojení se faktury nedají načíst",
  "faktury.odlozenaVystavena": "Odložená faktura je vystavená.",
  "faktury.odosluSaSamy": "Odešlou se samy, jakmile bude signál. Nemusíte na to myslet.",
  "faktury.chybaNacitania": "Faktury se nepodařilo načíst.",
  "faktury.chybaMazania": "Fakturu se nepodařilo smazat.",
  "faktury.chybaPdf": "PDF se nepodařilo připravit.",
  "faktury.chybaZdielania": "Sdílení selhalo.",
  "faktury.chybaUpomienky": "Upomínku se nepodařilo odeslat.",

  /* nová faktúra */
  "nf.komuFakturujete": "Komu fakturujete?",
  "nf.zaCoFakturujete": "Za co fakturujete?",
  "nf.skontrolujte": "Zkontrolujte fakturu",
  "nf.skontrolujteZalohovu": "Zkontrolujte zálohovou",
  "nf.krok": "Krok {n} ze 3",
  "nf.krokZalohova": "Krok 1 ze 3 · zálohová",
  "nf.faktura": "Faktura",
  "nf.zalohova": "Zálohová",
  "nf.odberatel": "Odběratel",
  "nf.hladatOdberatela": "Hledat odběratele",
  "nf.novyOdberatel": "Nový odběratel",
  "nf.ziadnyOdberatel": "Zatím nemáte žádného odběratele.",
  "nf.nicSaNenaslo": "Nic se nenašlo.",
  "nf.nacitavamOdberatelov": "Načítám odběratele…",
  "nf.nazov": "Název",
  "nf.zadajteNazov": "Zadejte název odběratele.",
  "nf.podlaIco": "Podle IČO se doplní název i adresa",
  "nf.hladamVRegistri": "Hledám v registru…",
  "nf.udajeDoplnene": "Údaje doplněny z registru",
  "nf.psc": "PSČ",
  "nf.email": "Na tento e-mail se dá faktura hned odeslat",
  "nf.odberatelPridany": "Odběratel přidán",
  "nf.chybaOdberatela": "Odběratele se nepodařilo uložit.",
  "nf.polozky": "Položky",
  "nf.nazovPolozky": "Název položky",
  "nf.mnozstvo": "Množství",
  "nf.pridajtePolozku": "Přidejte položku",
  "nf.odstranitPolozku": "Odstranit položku",
  "nf.zCennika": "Z ceníku",
  "nf.vlastna": "Vlastní",
  "nf.cennik": "Ceník",
  "nf.hladatPolozku": "Hledat položku",
  "nf.zopakovatPoslednu": "Zopakovat poslední fakturu",
  "nf.splatnost": "Splatnost",
  "nf.splatnostSkor": "Splatnost nemůže být dříve než vystavení.",
  "nf.sposobUhrady": "Způsob úhrady",
  "nf.hotovost": "Hotovost",
  "nf.poznamkaNad": "Poznámka nad položkami",
  "nf.poznamkaPod": "Poznámka pod položkami",
  "nf.priklad": "Například: podle objednávky č. 2026/114",
  "nf.zaklad": "Základ",
  "nf.naUhradu": "K úhradě",
  "nf.dalej": "Dále",
  "nf.zrusit": "Zrušit",
  "nf.zavriet": "Zavřít",
  "nf.ulozitPokracovat": "Uložit a pokračovat",
  "nf.ulozitZmeny": "Uložit změny",
  "nf.ukladam": "Ukládám…",
  "nf.ukladamZmeny": "Ukládám změny…",
  "nf.vystavit": "Vystavit fakturu",
  "nf.vystavitZalohovu": "Vystavit zálohovou fakturu",
  "nf.vystavujem": "Vystavuji fakturu…",
  "nf.vystavena": "Faktura vystavena",
  "nf.maCislo": "Faktura má přidělené číslo",
  "nf.odlozena": "Faktura je odložená v telefonu",
  "nf.naPrezretie": "Faktura k prohlédnutí",
  "nf.otvoritPdf": "Otevřít PDF",
  "nf.zdielat": "Sdílet fakturu",
  "nf.zdielatPopis": "Pošlete ji přes WhatsApp, Messenger nebo uložte do souborů",
  "nf.poslatEmailom": "Poslat e-mailem",
  "nf.odoslane": "Odesláno",
  "nf.odosielam": "Odesílám fakturu…",
  "nf.bezEmailu":
    "Odběratel nemá e-mail, takže fakturu nelze odeslat. Doplňte ho v kartě odběratele.",
  "nf.zalohy": "Nezúčtované zálohy tohoto odběratele",
  "nf.hladamZalohy": "Hledám zálohy…",
  "nf.ziadnaZaloha": "Žádná zálohová faktura k zúčtování",
  "nf.pridatZalohovu": "Přidat zálohovou fakturu",
  "nf.bezPripojenia": "Bez připojení — pracuji s naposledy načtenými údaji.",
  "nf.bezPripojeniaVystavit":
    "Bez připojení a bez uložených odběratelů se faktura vystavit nedá. Otevřete tuto obrazovku jednou s internetem.",
  "nf.zalohovaBezPripojenia": "Zálohovou fakturu se bez připojení vystavit nedá.",
  "nf.opravaBezPripojenia": "K opravě faktury je potřeba připojení.",
  "nf.chybaPodkladov": "Podklady se nepodařilo načíst.",
  "nf.chybaNacitania": "Fakturu se nepodařilo načíst.",
  "nf.chybaVystavenia": "Fakturu se nepodařilo vystavit.",
  "nf.chybaZmien": "Změny se nepodařilo uložit.",
  "nf.chybaPdf": "PDF se nepodařilo připravit.",
  "nf.chybaZdielania": "Sdílení selhalo.",

  /* prijaté doklady a banka */
  "pd.nazov": "Přijaté doklady",
  "pd.hladat": "Hledat dodavatele nebo číslo",
  "pd.nacitavam": "Načítám doklady…",
  "pd.ziadne": "Zatím žádné doklady",
  "pd.ziadnePopis": "Naskenované účtenky a faktury se objeví tady.",
  "pd.nicSaNenaslo": "Nic se nenašlo",
  "pd.skusteInak": "Zkuste hledat jinak.",
  "pd.bezDodavatela": "Bez dodavatele",
  "pd.neprecitany": "Nepřečtený doklad",
  "pd.zFinancnejSpravy": "Z Finanční správy",
  "pd.sQrKodom": "· s QR kódem",
  "pd.cisloDokladu": "Číslo dokladu",
  "pd.poznamka": "Poznámka",
  "pd.sposobUhrady": "Způsob úhrady",
  "pd.hotovost": "Hotovost",
  "pd.kartou": "Kartou",
  "pd.prevodom": "Převodem",
  "pd.sposobZmeneny": "Způsob úhrady změněn",
  "pd.otvoritPdf": "Otevřít PDF",
  "pd.nacitavamPrilohu": "Načítám přílohu…",
  "pd.presunut": "Přesunout mezi přijaté faktury",
  "pd.presuvam": "Přesouvám…",
  "pd.presunuty": "Doklad je mezi přijatými fakturami.",
  "pd.zmazat": "Smazat doklad",
  "pd.zmazatKratke": "Smazat",
  "pd.naozajZmazat": "Opravdu smazat tento doklad?",
  "pd.nedaSaVratit": "Vrátit se to nedá.",
  "pd.zmazany": "Doklad smazán",
  "pd.ponechat": "Ponechat",
  "pd.zrusit": "Zrušit",
  "pd.sparovat": "Spárovat",
  "pd.anoPatriKSebe": "Ano, patří k sobě",
  "pd.uhradenyZUctu": "Doklad označen za uhrazený z účtu.",
  "pd.parovanieZrusene": "Párování zrušeno.",
  "pd.chybaParovania": "Spárovat se to nepodařilo.",
  "pd.chybaZrusenia": "Zrušit se to nepodařilo.",
  "pd.chybaNacitania": "Doklady se nepodařilo načíst.",
  "pd.bezPripojenia": "Bez připojení se doklady nedají načíst",
  "pd.odlozeneOdoslu": "Odložené účtenky se odešlou samy, jakmile se vrátí signál.",
  "pd.bezSignalu": "Zatím bez signálu — zkusím to znovu sám.",
  "pd.zahodit": "Zahodit odložený doklad",
  "pd.odoslat": "Odeslat",
  "banka.ucet": "Účet",
  "banka.vsetky": "Všechny",
  "banka.nacitavam": "Načítám pohyby…",
  "banka.ziadnePohyby": "Zatím žádné pohyby",
  "banka.stiahnut": "Stáhnout z banky",
  "banka.stahujem": "Stahuji z banky…",
  "banka.ziadneNove": "Žádné nové pohyby.",
  "banka.prijataPlatba": "Přijatá platba",
  "banka.odchadzajucaPlatba": "Odchozí platba",
  "banka.dnes": "Dnes",
  "banka.vcera": "Včera",
  "banka.nesynchronizovane": "zatím nesynchronizováno",
  "banka.bezUctu": "Firma nemá připojený bankovní účet",
  "banka.pripojenieNaWebe":
    "Účet se připojuje na webu — banka při tom vyžaduje přihlášení a souhlas, který se v telefonu dobře vyřídit nedá.",
  "banka.bezPripojenia": "Bez připojení se účty nedají načíst",
  "banka.lenSoSignalom":
    "Zůstatky a pohyby se dají prohlédnout, jen když je signál — z telefonu se nikam neukládají.",
  "banka.neodpovedala": "Banka teď neodpověděla. Zkuste to za chvíli.",
  "banka.chybaNacitania": "Pohyby se nepodařilo načíst.",

  /* kniha jázd */
  "jz.novaJazda": "Nová jízda",
  "jz.zacatJazdu": "Začít jízdu",
  "jz.jazdaBezi": "Jízda běží",
  "jz.jazdaPozastavena": "Jízda pozastavena",
  "jz.meranieNebezi": "měření zatím neběží",
  "jz.pozastavene": "pozastaveno — pohyb se nezapočítává",
  "jz.pozastavitMeranie": "Pozastavit měření",
  "jz.pokracovatVMerani": "Pokračovat v měření",
  "jz.tuknutimPozastavite": "Ťuknutím na kruh pozastavíte měření",
  "jz.tuknutimPokracujete": "Ťuknutím na kruh budete pokračovat",
  "jz.ukoncitAUlozit": "Ukončit a uložit jízdu",
  "jz.ukladamJazdu": "Ukládám jízdu…",
  "jz.ucelCesty": "Účel cesty",
  "jz.ucelPriklad": "např. servis u odběratele",
  "jz.ulozeneSluzobna": "Uloženo jako služební",
  "jz.ulozeneSukromna": "Uloženo jako soukromá",
  "jz.bezSignaluOdoslana": "Jízda zapsaná bez signálu je odeslána",
  "jz.chybaUlozenia": "Jízdu se nepodařilo uložit.",
  "jz.chybaGps": "GPS se nepodařilo spustit.",
  "jz.chybaPokracovania": "V měření se nepodařilo pokračovat.",
  "jz.rozpoznanaBezi": "Probíhá rozpoznaná jízda",
  "jz.ukoncitJazdu": "Ukončit jízdu",
  "jz.ukoncujem": "Ukončuji…",
  "jz.zahodit": "Zahodit",
  "jz.zahoditOtazka": "Zahodit tuto jízdu? Do knihy jízd se nezapíše.",
  "jz.ukoncena": "Jízda ukončena — zařaďte ji níže.",
  "jz.zahodena": "Jízda zahozena.",
  "jz.vozidloPreJazdu": "Vozidlo pro rozpoznanou jízdu",
  "jz.telefonNevie": "Telefon neví, do kterého auta jste sedli — zkontrolujte ho u každé jízdy.",
  "jz.rozpoznavat": "Rozpoznávat jízdy automaticky",
  "jz.detekciaZapnuta": "Detekce jízd je zapnutá",
  "jz.detekciaNemaAkoBezat": "Detekce je zapnutá, ale nemá jak běžet",
  "jz.vyzadujePolohu": "Vyžaduje polohu „Vždy“.",
  "jz.akoFunguje": "Jak rozpoznávání funguje",
  "jz.ukazatTrasu": "Ukázat trasu",
  "jz.skrytTrasu": "Skrýt trasu",
  "jz.historia": "historie",
  "jz.noveVozidlo": "Nové vozidlo",
  "jz.pridatVozidlo": "Přidat vozidlo",
  "jz.vozidloPridane": "Vozidlo přidáno",
  "jz.chybaVozidla": "Vozidlo se nepodařilo přidat.",
  "jz.zadajteNazovVozidla": "Zadejte název vozidla.",
  "jz.evidencneCislo": "Evidenční číslo",
  "jz.nazovVozidlaPriklad": "např. Škoda Octavia",
  "jz.ukladamVozidlo": "Ukládám vozidlo…",
  "jz.nacitavamVozidla": "Načítám vozidla…",
  "jz.bezVozidla": "Firma nemá žádné vozidlo",
  "jz.pridajteHo": "Přidejte ho tady — stačí název a značka, zbytek se dá doplnit na webu.",
  "jz.commander": "Jízdy tohoto auta tahá Commander",
  "jz.bezPripojenia": "Bez připojení se vozidla nedají načíst",
  "jz.bezZoznamu": "V telefonu zatím není uložený seznam. Otevřete tuto obrazovku jednou s internetem.",
  "jz.nepovinneCena": "Nepovinné, ale bez ní vyjde náklad na jízdu nula.",

  /* skener, notifikácie, čísla dopredu */
  "jz.nahravamJazdu": "Nahrávám jízdu",
  "jz.spustenaRucne": "spuštěna ručně",
  "jz.otvoritPrebiehajucu": "Otevřít probíhající jízdu",
  "qr.namierte": "Namiřte na QR kód",
  "qr.zrusitSkenovanie": "Zrušit skenování",
  "qr.kameraNejde": "Kameru se nepodařilo spustit. Zkuste doklad vyfotit.",
  "qr.kameraZamietnuta": "Přístup ke kameře je zamítnut. Povolte jej v nastavení telefonu.",
  "push.nazov": "Oznámení",
  "push.zistujem": "Zjišťuji…",
  "push.zaregistrovane": "Zařízení je zaregistrováno, oznámení chodit budou.",
  "push.neznameZariadenie": "Server toto zařízení zatím nezná.",
  "push.povolenieVTelefone": "Povolení v telefonu:",
  "push.lenVApke": "jen v mobilní aplikaci",
  "push.pluginNedostupny": "plugin nedostupný",
  "push.registraciaZlyhala": "registrace selhala",
  "push.zaregistrovatZnova": "Zaregistrovat znovu",
  "push.skusitZaregistrovat": "Zkusit zaregistrovat",
  "spolocne.chyba": "Chyba",
  "cisla.nazov": "Vystavovat bez signálu rovnou s číslem",
  "cisla.vypnutePopis": "Bez toho se faktura bez signálu odloží a vystaví se sama po připojení — číslo dostane až tehdy.",
  "cisla.zapnutePopis": "Připravených čísel: {pocet}. Faktura vystavená bez signálu dostane číslo hned, takže se dá předat na místě.",
  "cisla.zapnut": "Zapnout",
  "cisla.vypnut": "Vypnout",
  "cisla.vypnute": "Vypnuto. Nepoužitá čísla se vrátila do řady.",
  "cisla.zapnute": "Zapnuto. Aplikace má připraveno {pocet} čísel.",
  "cisla.trebaPripojenie": "K zapnutí je potřeba připojení — čísla si aplikace vyžádá od serveru.",
  "cisla.nepodariloVypytat": "Čísla se nepodařilo vyžádat. Zkuste to za chvíli.",
  "cisla.nepodariloPrepnut": "Nepodařilo se to přepnout.",

  /* skener, firma, registrácia */
  "sken.naskenujte": "Naskenujte QR kód účtenky",
  "sken.aleboOdfotte": "nebo doklad vyfoťte",
  "sken.kameraNejde": "Doklad se dá i tak vyfotit nebo vybrat ze souborů — tlačítka níže fungují.",
  "sken.odfotit": "Vyfotit",
  "sken.zGalerie": "Z galerie",
  "sken.uhrada": "Úhrada",
  "sken.karta": "Karta",
  "sken.kategoria": "Kategorie nákladu",
  "sken.nezaradene": "Nezařazené",
  "sken.pdfSubor": "PDF soubor",
  "sken.viacstranovy": "Vícestránkový",
  "vf.vytvorteSiFirmu": "Vytvořte si firmu",
  "vf.pridatFirmu": "Přidat firmu",
  "vf.podnadpis": "Tyto údaje se zobrazí na fakturách",
  "vf.vytvaram": "Vytvářím…",
  "vf.vytvoritFirmu": "Vytvořit firmu",
  "vf.uvod": "Stačí název — ostatní se dá doplnit kdykoli později v nastavení. Když zadáte IČO, adresu i daňová čísla natáhneme z rejstříku.",
  "vf.nazovFirmy": "Název firmy",
  "vf.ico": "IČO",
  "vf.dic": "DIČ",
  "vf.icDph": "DIČ (DPH)",
  "vf.ulica": "Ulice a číslo",
  "vf.mesto": "Město",
  "vf.psc": "PSČ",
  "vf.iban": "IBAN",
  "vf.ibanHint": "Zákazník podle něj zaplatí — klidně i později.",
  "vf.email": "E-mail",
  "vf.telefon": "Telefon",
  "vf.hladamVRegistri": "Hledám v rejstříku…",
  "vf.trebaPripojenie": "K založení firmy je potřeba připojení. Zkuste to, až bude signál.",
  "vf.nepodariloVytvorit": "Firmu se nepodařilo vytvořit.",
  "vf.vytvorena": "Firma je vytvořena.",
  "vf.chyba.nazov": "Zadejte název firmy.",
  "vf.chyba.ico": "IČO má 6 až 8 číslic.",
  "vf.chyba.email": "Zadejte platný e-mail firmy.",
  "vf.chyba.iban": "IBAN nemá správný tvar.",
  "reg.potvrdteEmail": "Potvrďte si e-mail",
  "reg.potvrdenieText": "Účet {email} je vytvořen. Poslali jsme na něj odkaz — otevřete jej a vraťte se sem. Aplikace si potvrzení všimne sama; kdyby ne, je tu tlačítko níže. Bez potvrzení se přihlásit nedá.",
  "reg.spamPriecinok": "Pokud e-mail do pár minut nepřijde, podívejte se do nevyžádané pošty.",
  "reg.overujem": "Ověřuji…",
  "reg.uzSomPotvrdil": "Už jsem potvrdil, pokračovat",
  "reg.posielam": "Posílám…",
  "reg.poslatZnova": "Poslat e-mail znovu",
  "reg.spatNaPrihlasenie": "Zpět na přihlášení",
  "reg.vytvorteSiUcet": "Vytvořte si účet",
  "reg.zadarmo": "30 dní zdarma v plánu Premium. Bez platební karty.",
  "reg.meno": "Jméno a příjmení",
  "reg.email": "E-mail",
  "reg.heslo": "Heslo (alespoň 8 znaků)",
  "reg.suhlasPodmienky": "Souhlasím s {odkaz}.",
  "reg.obchodnePodmienky": "Obchodními podmínkami",
  "reg.suhlasGdpr": "Beru na vědomí {odkaz}.",
  "reg.spracuvanieUdajov": "Zpracování osobních údajů",
  "reg.vytvaram": "Vytvářím…",
  "reg.vytvoritUcet": "Vytvořit účet",
  "reg.uzMamUcet": "Už mám účet, přihlásit se",
  "reg.ucetJeVytvoreny": "Účet je vytvořen.",
  "reg.registraciaZlyhala": "Registrace selhala.",
  "reg.nepotvrdene": "Zatím to není potvrzeno. Otevřete odkaz z e-mailu a zkuste to znovu.",
  "reg.emailPoslanyZnova": "E-mail jsme poslali znovu.",
  "reg.chyba.meno": "Zadejte jméno a příjmení.",
  "reg.chyba.email": "Zadejte platný e-mail.",
  "reg.chyba.heslo": "Heslo musí mít alespoň 8 znaků.",
  "reg.chyba.suhlasy": "Potvrďte oba souhlasy.",

  /* cenové ponuky */
  "ponuky.bezEmailu": "Odběratel nemá e-mail. Doplňte ho na jeho kartě.",
  "ponuky.odoslatOtazka": "Odeslat nabídku {cislo} na {email}?",
  "ponuky.odoslana": "Nabídka odeslána.",
  "ponuky.uzFakturovana": "Z této nabídky už faktura vznikla.",
  "ponuky.naFakturuOtazka": "Vytvořit fakturu z nabídky {cislo}?",
  "ponuky.fakturaVytvorena": "Faktura vytvořena.",
  "ponuky.platiDoSkratka": "platí do {den}",
  "ponuky.vyberteOdberatela": "Vyberte odběratele.",
  "ponuky.doplntePolozku": "Doplňte alespoň jednu položku.",
  "ponuky.platnostPredVystavenim": "Platnost nemůže být před vystavením.",
  "ponuky.nepodariloVytvorit": "Nabídku se nepodařilo vytvořit.",
  "ponuky.vytvaram": "Vytvářím nabídku…",

  /* kniha jázd — zvyšok */
  "jz.odCasu": "Od {cas}. Když jste dojeli, ukončete ji — jinak se zastaví sama až po pěti minutách stání.",
  "jz.rozpoznalaJazdu": "Aplikace rozpoznala jízdu",
  "jz.rozpoznalaJazdy": "Aplikace rozpoznala jízdy ({pocet})",
  "jz.commanderZvysok": ", takže je telefon měřit nemusí — vyber jiné auto, nebo nech detekci vypnutou.",
  "jz.typJazdy": "Typ jízdy",
  "jz.vozidlo": "Vozidlo",
  "jz.nazovVozidla": "Název",
  "jz.spotreba": "Spotřeba (l/100 km)",
  "jz.spotrebaPriklad": "např. 6,5",
  "jz.vsimneSi": "Aplikace si jízdu všimne sama a zeptá se oznámením, zda byla služební.",
  "jz.lenPocasPouzivania": "Pokud jste polohu povolili jen „při používání“, nechte aplikaci otevřenou — po zhasnutí displeje telefon měření zastaví a kilometry by se dopočítaly nesprávně. S povolením „Vždy“ běží měření i v kapse.",
  "jz.vyberteVozidlo": "Vyberte vozidlo.",
  "jz.odoslanychJazd": "Odesláno {pocet} jízd zapsaných bez signálu",
  "jz.rozpoznanaUlozena": "Rozpoznaná jízda uložena — {km} km, {auto}",
  "jz.bezPolohy": "Nenaměřili jsme žádnou polohu, jízdu jsem neuložil. Zkuste to venku — v budově je poloha nepřesná — a polohu povolte na „Vždy“.",
  "jz.ulozenaVTelefone": "Jízda uložena v telefonu — {km} km. Odešle se po připojení.",
  "jz.ulozenaKm": "Jízda uložena — {km} km",
  "jz.historiaVozidla": "Historie jízd — {auto}",

  /* bočný panel */
  "panel.nadpis": "Panel nastavení",
  "panel.prihlasenyAko": "Přihlášen jako",
  "panel.vsetkoNaJednej": "Vše, co aplikace umí, na jedné obrazovce",
  "panel.ucetPamat": "Účet a jeho zrušení, paměť, připojení, verze",
  "panel.ekasaPopis": "Jak se čtou doklady z eKasy",
  "panel.napisteNam": "Napište nám, co nefunguje nebo co by pomohlo",
  "panel.zvysokAplikacie": "Faktury, sklad a zbytek aplikace",
  "panel.pravnePopis": "Podmínky, ochrana údajů a ostatní — otevře se v prohlížeči",
  "panel.biometria": "Přihlášení biometrií",
  "panel.biometriaZapnuta": "Ptá se při spuštění aplikace",
  "panel.biometriaVypnuta": "Vypnuto",
  "panel.biometriaNedostupna": "Biometrie na tomto zařízení není dostupná.",
  "panel.rychleZapnute": "Rychlé přihlášení zapnuto",
  "panel.rychleVypnute": "Rychlé přihlášení vypnuto",
  "panel.nepodariloZapnut": "Nepodařilo se zapnout",

  /* doklady, faktúry, jazdy, banka — zvyšok */
  "pd.doklad": "Doklad",
  "pd.ico": "IČO",
  "pd.icDph": "DIČ (DPH)",
  "faktury.vystavenychPocet": "Vystaveno faktur: {pocet}.",
  "faktury.neuhradene": "Neuhrazené",
  "faktury.odosluSaSamy2": "Odešlou se samy, jakmile bude signál. Nemusíte na to myslet.",
  "faktury.bezZoznamu": "V telefonu zatím není uložen žádný seznam. Otevřete tuto obrazovku jednou s internetem, potom bude dostupná i bez něj.",
  "faktury.vystavena": "Vystavena",
  "faktury.splatna": "Splatná",
  "faktury.uhradena": "Uhrazena",
  "faktury.odoslana": "Odeslána",
  "faktury.cisloOstava": "Zmizí ze seznamu, ale číslo zůstává obsazené — v číselné řadě nevznikne díra.",
  "jazdy.nacitavam": "Načítám jízdy…",
  "jazdy.prvaPribudne": "První přibude po ukončení měření — nebo se natáhne z GPS jednotky, když je vozidlo propojené.",
  "jazdy.spoluCelaHistoria": "Celkem za celou historii",
  "jazdy.spoluPoslednych": "Celkem za posledních {pocet} jízd",
  "jazdy.nacitatStarsie": "Načíst starší jízdy",
  "jazdy.chybaStarsich": "Starší jízdy se nepodařilo načíst.",
  "banka.nazov": "Banka",
  "banka.vsetkyUcty": "Všechny",
  "banka.ucetSkratka": "účet",

  /* banka — prepínač účtov */
  "banka.ucetVelke": "Účet",
  "banka.zostatokSpolu": "Zůstatek celkem",

  /* nová faktúra — zvyšok */
  "nf.zalohovaVysvetlenie": "Zálohová faktura je výzva k platbě, ne daňový doklad — nevstupuje do DPH a dostane číslo z vlastní řady. Po zaplacení na ni vystavíte běžnou fakturu a zálohu na ní zúčtujete.",
  "nf.ico": "IČO",
  "nf.ulica": "Ulice",
  "nf.mesto": "Město",
  "nf.dic": "DIČ",
  "nf.icDph": "DIČ (DPH)",
  "nf.emailPole": "E-mail",
  "nf.spolu": "Celkem",
  "nf.dph": "DPH",
  "nf.vystavenie": "Vystavení",
  "nf.bezIbanu": "Firma nemá vyplněný IBAN — na faktuře nebude kam zaplatit. Doplňte jej na webu v nastavení firmy.",
  "nf.ziadnaZalohaPopis": "Tento odběratel nemá zálohovou fakturu, která by ještě nebyla zúčtovaná. Vystavíte ji tak, že v prvním kroku nové faktury vyberete {zalohova}.",
  "nf.cisloJeVase": "Číslo je vaše a nikomu jinému se nepřidělí — klidně jej předejte zákazníkovi. PDF se vytvoří a faktura odešle sama, jakmile bude signál.",
  "nf.odlozenaPopis": "Vystaví se i s číslem sama, jakmile bude signál. Číslo zatím nemá, takže se zákazníkovi nedá nadiktovat — pokud to potřebujete, zapněte si v nastavení vydávání s číslem dopředu.",
  "nf.hotovo": "Hotovo",
  "nf.pripravujemPdf": "Připravuji PDF…",
  "nf.bezPripojeniaNadpis": "Bez připojení",

  /* hlavná obrazovka appky */
  "app.chybaObrazovky": "Tuto obrazovku se nepodařilo otevřít.",
  "app.slabePripojenie": "Bývá to slabým připojením. Zkuste to znovu, nebo se přihlaste znovu.",
  "app.skusitZnova": "Zkusit znovu",
  "app.prihlasitNanovo": "Přihlásit se znovu",
  "app.diagnostika": "Diagnostika",
  "app.diagnostikaPopis": "Co aplikace v telefonu vidí — balíček, paměť, připojení.",
  "app.novaVerzia": "Je dostupná novější verze aplikace — klepněte na aktualizaci",
  "app.prihlasenie": "Přihlášení",
  "app.prihlasteSa": "Přihlaste se do svého účtu ve Fakteru.",
  "app.odomknutBiometriou": "Odemknout biometrií",
  "app.nemateUcet": "Nemáte účet?",
  "app.zaregistrujteSa": "Zaregistrujte se",
  "app.zabudnuteHeslo": "Zapomenuté heslo si obnovíte na faktero.sk.",
  "app.zamknute": "Faktero je zamčeno",
  "app.odomknitePokracujte": "Odemkněte jej biometrií a pokračujte tam, kde jste skončili.",
  "app.pridatDalsiuFirmu": "Přidat další firmu",
  "app.odvolatZiadost": "Odvolat žádost",
  "app.zFakturyPrecita": "Z faktury se přečte dodavatel, datum, částka i DPH. Údaje před uložením zkontrolujte.",
  "app.vyberteUhradu": "Vyberte způsob úhrady",
  "app.povinne": "Povinné",
  "app.vyberteMoznost": "Vyberte jednu z možností — bez ní se doklad uložit nedá.",
  "app.hotovostnyDoklad": "Hotovostní doklad ubere ze stavu pokladny.",
  "app.fotkaDokladu": "Fotka dokladu",
  "app.prilozenePdf": "Přiložené PDF",
  "app.odfotitZnova": "Vyfotit znovu",
  "app.otvaram": "Otevírám…",
  "app.skenerDokladov": "Skener dokladů",
  "app.ucet": "Účet",
  "app.email": "E-mail",
  "app.heslo": "Heslo",
  "app.vyberteFirmu": "Vyberte firmu",
  "app.doVybranejFirmy": "Doklady se uloží do vybrané firmy",
  "app.staciNazov": "Stačí název, ostatní se dá doplnit později",
  "app.fakturyADoklady": "Faktury a doklady",
  "app.citamDoklad": "Čtu doklad…",
  "app.ukladamDoklad": "Ukládám doklad…",
  "app.nasnimatQr": "Nasnímat QR kód",
  "app.namierteNaBlocek": "Namiřte na QR kód na účtence",
  "app.odfotitBlocek": "Vyfotit celou účtenku",
  "app.qrNaFotke": "QR se najde i na fotce",
  "app.vybratSubor": "Vybrat soubor",
  "app.pdfAleboObrazok": "PDF nebo obrázek faktury",
  "app.stranySaSpoja": "Strany se spojí do jednoho PDF",
  "app.skontrolujteDoklad": "Zkontrolujte doklad",
  "app.odfotitDoklad": "Vyfotit doklad",
  "app.papierovyDoklad": "Papírový doklad je třeba odložit i tak — fotka jej nahradí",
  "app.vyplnteEmailHeslo": "Vyplňte e-mail i heslo.",
  "app.prilohaNenahrata": "Přílohu se nepodařilo nahrát, doklad uložím bez ní.",
  "app.dokladUlozeny": "Doklad uložen",
  "app.bezPripojeniaFirmy": "Bez připojení a v telefonu zatím není uložen seznam firem. Otevřete aplikaci jednou s internetem.",
  "app.fakturaOdoslana": "Faktura vystavená bez signálu je odeslána.",
  "app.odoslanychOdlozenych": "Odesláno odložených faktur: {pocet}.",
  "app.jazdaUlozena": "Rozpoznaná jízda uložena",
  "app.jazdUlozenych": "Uloženo {pocet} rozpoznaných jízd",
  "app.prihlasenieZlyhalo": "Přihlášení selhalo.",
  "app.prihlasujem": "Přihlašuji…",
  "app.prihlasitSa": "Přihlásit se",
  "app.odomykam": "Odemykám…",
  "app.odomknut": "Odemknout",
  "app.bezFirmy": "K tomuto účtu zatím nepatří žádná firma. Bez ní nemají doklady kam jít — založte si ji rovnou tady.",
  "app.blocekQr": "Účtenka s QR kódem",
  "app.fakturaPdf": "Faktura v PDF",
  "app.viacstranovyDoklad": "Vícestránkový doklad",
  "app.nepodariloPrecitat": "Doklad se nepodařilo přečíst.",
  "app.citanieZlyhalo": "Čtení selhalo.",
  "app.spojenieStranZlyhalo": "Spojení stran selhalo.",
  "app.bezSignaluOdosleSa": "Bez signálu — doklad se odešle sám, až bude připojení.",
  "app.spojenieVypadlo": "Spojení vypadlo — doklad se odešle sám později.",
  "app.ulozenieZlyhalo": "Uložení selhalo.",
  "app.odfotitPrvuStranu": "Vyfotit první stranu",
  "app.pridatDalsiuStranu": "Přidat další stranu",
  "app.zatialStran": "Zatím {pocet} stran",
  "app.dokladOdfotteCely": "Doklad vyfoťte celý",
  "app.precitaneZDokladu": "Přečteno z dokladu",
  "app.ulozitDoklad": "Uložit doklad",
  "app.neznamyPredajca": "Neznámý prodejce",
  "app.zDokladuZatvorka": "(přečteno z dokladu)",
  "app.zTohoDph": "z toho DPH {suma}",
  "app.bezPripojeniaKratke": "bez připojení",
  "app.bezOdpovede": "bez odpovědi",

  /* zrušenie účtu */
  "app.zrusenieNaplanovane": "Účet je naplánován ke zrušení {termin} — za {dni}.",
  "spolocne.den1": "den",
  "spolocne.den2": "dny",
  "spolocne.den5": "dní",

  /* množné tvary */
  "app.cakajuceFaktury": "V telefonu čeká {pocet} na odeslání. Připojte se a otevřete Vystavené faktury — potom se dá odhlásit.",
  "spolocne.faktura1": "faktura",
  "spolocne.faktura2": "faktury",
  "spolocne.faktura5": "faktur",

  /* appka — drobnosti */
  "app.odstranitStranu": "Odstranit stranu {n}",

  /* ponuky — prázdny zoznam */
  "ponuky.ziadnePopis2": "Nabídku uděláte stejně jako fakturu — a když ji zákazník přijme, jedním klepnutím z ní faktura vznikne.",

  /* drobnosti — kroky a stavy */
  "nf.oprava": "Oprava {cislo}",
  "nf.fakturaCislo": "Faktura {cislo}",
  "faktury.pracujem": "Pracuji…",
  "faktury.pripravujemPdf": "Připravuji PDF…",
  "pd.odosielam": "Odesílám…",

  /* vystavené faktúry */
  "faktury.cakaNaOdoslanie": "Čeká na odeslání: {pocet}",

  /* prijaté doklady — úhrada */
  "pd.uhradeneZUctuDna": "Uhrazeno z účtu {den}",
  "pd.uhradeneSkratka": "uhrazeno z účtu {den}",

  /* súhrny */
  "nf.zakladDph": "základ {zaklad} · DPH {dph}",
  "nf.odpocitaSa": "odečte se {suma}",

  /* šablónové texty */
  "banka.kFakture": "k faktuře {cislo}",
  "banka.aktualizovane": "Aktualizováno {ked}",
  "jz.bezi": "běží {trvanie}",
  "jz.ukladaSaNa": "Ukládá se na {auto} — změníš výběrem vozidla níže.",

  /* povolení pro knihu jízd (Android) */
  "pov.nadpis": "Aby se jízdy zapisovaly samy",
  "pov.uvod": "Kniha jízd měří trasu na pozadí — i když máte zhasnutý displej a telefon v kapse. Bez toho by se kilometry nedopočítaly. Polohu používáme jen k výpočtu jízdy, nikam ji neposíláme.",
  "pov.poloha": "Poloha — aby šlo jízdu vůbec změřit.",
  "pov.notifikacie": "Oznámení — aby se aplikace po jízdě zeptala, zda byla služební.",
  "pov.pohyb": "Pohybové senzory — aby se jízda rozpoznala rychleji.",
  "pov.vzdy": "Poloha „Vždy“ — bez ní se se zhasnutým displejem neměří nic.",
  "pov.povolit": "Povolit",
  "pov.pytamSa": "Ptám se…",
  "pov.neskor": "Později",
  "app.spustam": "Spouštím Faktero… ({faza}) · {balicek}",
  "app.startZasekol": "Start se zasekl na kroku „{faza}“.",
  "app.balicek": "balíček {peciatka}",
  "app.hotovoStran": "Hotovo — {pocet} stran",
  "app.poloziekZDokladu": "{pocet} položek z dokladu",
  "nf.zFaktury": "Z faktury {cislo}",
  "nf.polozkyZFaktury": "Položky z faktury {cislo}",
  "nf.opravena": "Faktura {cislo} opravena",
  "nf.icoS": "IČO {ico}",
  "nf.zuctovanaZaloha": "Zúčtovaná záloha {cislo}",
  "nf.dni": "{d} dní",
  "nf.zalohaCislo": "Záloha {cislo}",
  "nf.odoslaneNa": "Odesláno na {email}",
  "ponuky.vytvorena": "Nabídka {cislo} vytvořena.",
  "ponuky.vytvoritSuma": "Vytvořit nabídku · {suma}",
  "ponuky.nazovSuboru": "Cenová nabídka {cislo}",
  "pd.odoslaneDoklady": "Odeslané doklady: {pocet}",
  "pd.cakaNaOdoslanie": "Čeká na odeslání: {pocet}",
  "spolocne.doklad1": "doklad",
  "spolocne.doklad2": "doklady",
  "spolocne.doklad5": "dokladů",
  "pd.najdenePlatby": "Našli jsme platby k dokladům ({pocet})",
  "pd.polozkyPocet": "Položky ({pocet})",
  "faktury.zmazana": "Faktura {cislo} smazána",
  "faktury.upomienkaOdoslana": "{n}. upomínka odeslána",
  "faktury.poslatUpomienku": "Poslat {n}. upomínku",
  "faktury.zatialOdoslane": "Zatím odesláno: {pocet}",
  "faktury.naozajZmazat": "Opravdu smazat fakturu {cislo}?",

  /* spodná lišta */
  "tab.prehlad": "Přehled",
  "tab.doklady": "Doklady",
  "tab.jazdy": "Jízdy",

  /* prehľad a vzhľad */
  "ph.nazov": "Přehled",
  "ph.neuhradene": "Neuhrazené",
  "ph.poSplatnosti": "Po splatnosti",
  "ph.rychleAkcie": "Rychlé akce",
  "ph.faktura": "Faktura",
  "ph.skenovat": "Skenovat",
  "ph.zacatJazdu": "Začít jízdu",
  "ph.naVybavenie": "K vyřízení",
  "ph.poslednaAktivita": "Poslední aktivita",
  "ph.fakturyPoSplatnosti": "{pocet} po splatnosti",
  "ph.dokladyNaKontrolu": "{pocet} čeká na kontrolu",
  "ph.jazdaNeukoncena": "Jízda není ukončena",
  "ph.vsetkoVybavene": "Nic nečeká",
  "ph.vsetkoVybavenePopis": "Faktury jsou uhrazené a doklady zkontrolované.",
  "ph.ziadnaAktivita": "Zatím se nic nedělo",
  "ph.ziadnaAktivitaPopis": "První faktura nebo doklad se objeví tady.",
  "ph.fakturaCislo": "Faktura {cislo}",
  "ph.doklad": "Přijatý doklad",
  "ph.dnes": "Dnes",
  "ph.vcera": "Včera",
  "ph.vzhlad": "Vzhled",
  "ph.svetly": "Světlý",
  "ph.tmavy": "Tmavý",
  "ph.podlaSystemu": "Podle systému",

  /* filtre faktúr */
  "faktury.filterVsetky": "Všechny",
  "faktury.filterNeuhradene": "Neuhrazené",
  "faktury.filterPoSplatnosti": "Po splatnosti",
  "faktury.filterUhradene": "Uhrazené",
  "faktury.splatnostSkratka": "splatnost {den}",
  "faktury.hladatKratke": "Hledat",
  "faktury.filtre": "Filtry",

  /* skener — režimy */
  "sken.doklad": "Doklad",
  "sken.qrKod": "QR kód",
  "sken.naskenujteDoklad": "Naskenujte doklad",
  "sken.automaticky": "Doklad se naskenuje automaticky",
  "sken.namierteQr": "Namiřte na QR kód",
  "sken.qrSaPrecita": "Kód se přečte sám, netřeba nic mačkat",
  "sken.nastavenie": "Nastavení dokladu",

  /* banka — párovanie */
  "banka.sparovane": "Spárováno",
  "banka.sparovat": "Spárovat",

  /* krokovník novej faktúry */
  "nf.krokOdberatel": "Odběratel",
  "nf.krokPolozky": "Položky",
  "nf.krokKontrola": "Kontrola",
  "nf.nedavniOdberatelia": "Nedávní odběratelé",
  "nf.vsetciOdberatelia": "Všichni odběratelé",
  "nf.pokracovat": "Pokračovat",

  "spolocne.spat": "Zpět",
  "spolocne.ulozit": "Uložit",
  "spolocne.zrusit": "Zrušit",
  "spolocne.nacitavam": "Načítám…",
  "spolocne.km": "km",

  /* samostatná aplikace Kniha jízd */
  "kj.nazov": "Kniha jízd",
  "kj.tabPrehlad": "Přehled",
  "kj.tabHistoria": "Historie",
  "kj.tabVozidla": "Vozidla",
  "kj.tentoMesiac": "Tento měsíc",
  "kj.sluzobne": "Služební",
  "kj.sukromne": "Soukromé",
  "kj.posledneJazdy": "Poslední jízdy",
  "kj.vyberVozidla": "Vyberte vozidlo",
  "kj.vyberVozidlaPopis": "Kniha jízd se vede po vozidlech.",
  "kj.mojeVozidlo": "Moje vozidlo",
  "kj.mojeVozidloPopis": "Ťuknutím vyberete auto, které aplikace nabídne při jízdě.",
  "kj.nastavitAkoMoje": "Nastavit jako moje",
  "kj.jazd1": "jízda",
  "kj.jazd2": "jízdy",
  "kj.jazd5": "jízd",
  "kj.bezJazd": "Tento měsíc zatím bez jízdy",
  "kj.bezJazdPopis": "První spustíte zeleným tlačítkem dole.",
};
