import type { Kluc } from "./sk";

/** Čeština. Čo tu chýba, spadne na slovenčinu. */
export const cs: Partial<Record<Kluc, string>> = {
  "tab.skener": "Skener",
  "tab.faktury": "Faktury",
  "tab.vytvorit": "Vytvořit",
  "tab.banka": "Banka",
  "tab.jazda": "Kniha jízd",
  "tab.navigacia": "Hlavní navigace",

  "panel.nastavenia": "Nastavení",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Změnit firmu",
  "panel.bezFirmy": "Bez firmy",
  "panel.prehladAgend": "Přehled agend",
  "panel.vystaveneFaktury": "Vystavené faktury",
  "panel.cenovePonuky": "Cenové nabídky",
  "panel.prijateDoklady": "Přijaté doklady",
  "panel.pomoc": "Nápověda",
  "panel.nastavenieAplikacie": "Nastavení aplikace",
  "panel.navody": "Návody k Fakteru",
  "panel.otvoriVPrehliadaci": "Otevře se v prohlížeči",
  "panel.blocky": "Účtenky a pokladna",
  "panel.nahlasitChybu": "Nahlásit chybu nebo návrh",
  "panel.otvoritNaWebe": "Otevřít Faktero na webu",
  "panel.pravne": "Právní dokumenty",
  "panel.odhlasit": "Odhlásit se",
  "panel.zavriet": "Zavřít",
  "panel.jazyk": "Jazyk",

  "domov.novaFaktura": "Nová faktura",
  "domov.novaFakturaPopis": "Odběratel, položky, splatnost — a rovnou odeslat",
  "domov.vystaveneFaktury": "Vystavené faktury",
  "domov.vystaveneFakturyPopis": "Kdo ještě nezaplatil, PDF a odeslání",
  "domov.blocek": "Účtenka s QR kódem",
  "domov.blocekPopis": "Načte se z Finanční správy i s položkami",
  "domov.fakturaPdf": "Faktura v PDF",
  "domov.fakturaPdfPopis": "Vyberte soubor z telefonu nebo z cloudu",
  "domov.viacstranovy": "Vícestránkový doklad",
  "domov.viacstranovyPopis": "Stranu po straně, uloží se jako jedno PDF",
  "domov.prijateDoklady": "Přijaté doklady",
  "domov.prijateDokladyPopis": "Účtenky a faktury, které jste už naskenovali",
  "domov.pohybyNaUcte": "Pohyby na účtu",
  "domov.pohybyNaUctePopis": "Jestli přišly peníze — zůstatek a poslední platby",
  "domov.novaJazda": "Nová jízda",
  "domov.novaJazdaPopis": "Kilometry změří telefon, stačí start a stop",

  "jazdy.historia": "Historie jízd",
  "jazdy.charakter": "Charakter jízdy",
  "jazdy.sluzobna": "Služební",
  "jazdy.sukromna": "Soukromá",
  "jazdy.oznacenaSukromna": "Označena jako soukromá.",
  "jazdy.oznacenaSluzobna": "Označena jako služební.",
  "jazdy.jazda": "Jízda",
  "jazdy.spolu": "Celkem",
  "jazdy.starsie": "Starší jízdy",
  "jazdy.ziadne": "Zatím žádné jízdy",

  "ponuky.nazov": "Cenové nabídky",
  "ponuky.nova": "Nová nabídka",
  "ponuky.novaDlha": "Nová cenová nabídka",
  "ponuky.ziadne": "Zatím žádná cenová nabídka",
  "ponuky.ziadnePopis":
    "Nabídku uděláte stejně jako fakturu — a když ji zákazník přijme, jedním ťuknutím z ní faktura vznikne.",
  "ponuky.vytvorit": "Vytvořit nabídku",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Sdílet",
  "ponuky.odoslat": "Odeslat",
  "ponuky.naFakturu": "Na fakturu",
  "ponuky.platiDo": "platí do",
  "ponuky.stav.vyfakturovana": "Vyfakturovaná",
  "ponuky.stav.zamietnuta": "Zamítnutá",
  "ponuky.stav.prijata": "Přijatá",
  "ponuky.stav.poPlatnosti": "Po platnosti",
  "ponuky.stav.odoslana": "Odeslaná",
  "ponuky.stav.navrh": "Návrh",
  "ponuky.odberatel": "Odběratel",
  "ponuky.polozky": "Položky",
  "ponuky.pridajPolozku": "Přidat položku",
  "ponuky.vystavena": "Vystavena",
  "ponuky.poznamka": "Poznámka",
  "ponuky.zaklad": "Základ",
  "ponuky.dph": "DPH",
  "ponuky.hladatOdberatela": "Hledat odběratele…",
  "ponuky.novyOdberatel": "Nový odběratel",
  "ponuky.nikNenajdeny": "Nikdo se nenašel.",
  "ponuky.zmenit": "změnit",

  "spolocne.spat": "Zpět",
  "spolocne.ulozit": "Uložit",
  "spolocne.zrusit": "Zrušit",
  "spolocne.nacitavam": "Načítám…",
  "spolocne.km": "km",
};
