import type { Kluc } from "./sk";

/** Deutsch. Was hier fehlt, fällt auf Slowakisch zurück. */
export const de: Partial<Record<Kluc, string>> = {
  "tab.skener": "Scannen",
  "tab.faktury": "Rechnungen",
  "tab.vytvorit": "Erstellen",
  "tab.banka": "Bank",
  "tab.jazda": "Fahrtenbuch",
  "tab.navigacia": "Hauptnavigation",
  "panel.nastavenia": "Einstellungen",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Firma wechseln",
  "panel.bezFirmy": "Keine Firma",
  "panel.prehladAgend": "Alle Bereiche",
  "panel.vystaveneFaktury": "Ausgestellte Rechnungen",
  "panel.cenovePonuky": "Angebote",
  "panel.prijateDoklady": "Eingegangene Belege",
  "panel.pomoc": "Hilfe",
  "panel.nastavenieAplikacie": "App-Einstellungen",
  "panel.navody": "Faktero-Anleitungen",
  "panel.otvoriVPrehliadaci": "Wird im Browser geöffnet",
  "panel.blocky": "Belege und Kasse",
  "panel.nahlasitChybu": "Fehler oder Idee melden",
  "panel.otvoritNaWebe": "Faktero im Web öffnen",
  "panel.pravne": "Rechtliche Dokumente",
  "panel.odhlasit": "Abmelden",
  "panel.zavriet": "Schließen",
  "panel.jazyk": "Sprache",
  "domov.novaFaktura": "Neue Rechnung",
  "domov.novaFakturaPopis": "Kunde, Positionen, Fälligkeit — und direkt senden",
  "domov.vystaveneFaktury": "Ausgestellte Rechnungen",
  "domov.vystaveneFakturyPopis": "Wer noch nicht bezahlt hat, PDF und Versand",
  "domov.blocek": "Beleg mit QR-Code",
  "domov.blocekPopis": "Wird von der Finanzverwaltung geladen, samt Positionen",
  "domov.fakturaPdf": "Rechnung als PDF",
  "domov.fakturaPdfPopis": "Datei vom Telefon oder aus der Cloud wählen",
  "domov.viacstranovy": "Mehrseitiger Beleg",
  "domov.viacstranovyPopis": "Seite für Seite, gespeichert als ein PDF",
  "domov.prijateDoklady": "Eingegangene Belege",
  "domov.prijateDokladyPopis": "Belege und Rechnungen, die Sie bereits gescannt haben",
  "domov.pohybyNaUcte": "Kontobewegungen",
  "domov.pohybyNaUctePopis": "Ob das Geld angekommen ist — Saldo und letzte Zahlungen",
  "domov.novaJazda": "Neue Fahrt",
  "domov.novaJazdaPopis": "Das Telefon misst die Strecke, nur Start und Stopp",
  "jazdy.historia": "Fahrtenverlauf",
  "jazdy.charakter": "Art der Fahrt",
  "jazdy.sluzobna": "Geschäftlich",
  "jazdy.sukromna": "Privat",
  "jazdy.oznacenaSukromna": "Als privat markiert.",
  "jazdy.oznacenaSluzobna": "Als geschäftlich markiert.",
  "jazdy.jazda": "Fahrt",
  "jazdy.spolu": "Gesamt",
  "jazdy.starsie": "Ältere Fahrten",
  "jazdy.ziadne": "Noch keine Fahrten",
  "ponuky.nazov": "Angebote",
  "ponuky.nova": "Neues Angebot",
  "ponuky.novaDlha": "Neues Angebot",
  "ponuky.ziadne": "Noch keine Angebote",
  "ponuky.ziadnePopis":
    "Ein Angebot erstellen Sie wie eine Rechnung — und wenn der Kunde es annimmt, wird mit einem Tippen eine Rechnung daraus.",
  "ponuky.vytvorit": "Angebot erstellen",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Teilen",
  "ponuky.odoslat": "Senden",
  "ponuky.naFakturu": "Zur Rechnung",
  "ponuky.platiDo": "gültig bis",
  "ponuky.stav.vyfakturovana": "Abgerechnet",
  "ponuky.stav.zamietnuta": "Abgelehnt",
  "ponuky.stav.prijata": "Angenommen",
  "ponuky.stav.poPlatnosti": "Abgelaufen",
  "ponuky.stav.odoslana": "Gesendet",
  "ponuky.stav.navrh": "Entwurf",
  "ponuky.odberatel": "Kunde",
  "ponuky.polozky": "Positionen",
  "ponuky.pridajPolozku": "Position hinzufügen",
  "ponuky.vystavena": "Ausgestellt",
  "ponuky.poznamka": "Notiz",
  "ponuky.zaklad": "Nettobetrag",
  "ponuky.dph": "USt.",
  "ponuky.hladatOdberatela": "Kunden suchen…",
  "ponuky.novyOdberatel": "Neuer Kunde",
  "ponuky.nikNenajdeny": "Nichts gefunden.",
  "ponuky.zmenit": "ändern",
  "domov.skupina.fakturacia": "Rechnungen",
  "domov.skupina.skenovanie": "Belege scannen",
  "domov.skupina.banka": "Bank",
  "domov.skupina.jazdy": "Fahrtenbuch",

  /* vystavené faktúry */
  "faktury.nazov": "Ausgestellte Rechnungen",
  "faktury.hladat": "Nummer oder Kunde suchen",
  "faktury.nacitavam": "Rechnungen werden geladen…",
  "faktury.ziadne": "Noch keine Rechnungen",
  "faktury.vystavPrvu": "Erste Rechnung ausstellen",
  "faktury.nicSaNenaslo": "Nichts gefunden",
  "faktury.bezOdberatela": "Ohne Kunde",
  "faktury.stav.navrh": "Entwurf",
  "faktury.stav.vystavena": "Ausgestellt",
  "faktury.stav.odoslana": "Gesendet",
  "faktury.stav.uhradena": "Bezahlt",
  "faktury.stav.neuhradena": "Offen",
  "faktury.stav.splatna": "Fällig",
  "faktury.stav.poSplatnosti": "Überfällig",
  "faktury.stav.stornovana": "Storniert",
  "faktury.otvoritPdf": "PDF öffnen",
  "faktury.zdielat": "Rechnung teilen",
  "faktury.zdielatPopis": "Per WhatsApp, Messenger senden oder in Dateien speichern",
  "faktury.poslatEmailom": "Per E-Mail senden",
  "faktury.oznacitUhradenu": "Als bezahlt markieren",
  "faktury.oznacitPopis": "Wenn die Zahlung außerhalb des Bankabgleichs kam",
  "faktury.oznacenaUhradena": "Als bezahlt markiert",
  "faktury.upravit": "Rechnung bearbeiten",
  "faktury.upravitPopis": "Positionen, Daten und Notiz",
  "faktury.zmazat": "Rechnung löschen",
  "faktury.zmazatPopis":
    "Sie verschwindet aus der Liste, die Nummer bleibt aber vergeben — in der Nummernfolge entsteht keine Lücke.",
  "faktury.zmazatKratke": "Löschen",
  "faktury.ponechat": "Behalten",
  "faktury.mazem": "Wird gelöscht…",
  "faktury.naPrezretie": "Rechnungsvorschau",
  "faktury.bezPripojenia": "Offline — die zuletzt geladenen Rechnungen werden angezeigt.",
  "faktury.bezPripojeniaNacitanie": "Ohne Verbindung lassen sich Rechnungen nicht laden",
  "faktury.odlozenaVystavena": "Die zurückgestellte Rechnung wurde ausgestellt.",
  "faktury.odosluSaSamy": "Sie werden von selbst gesendet, sobald wieder Empfang da ist.",
  "faktury.chybaNacitania": "Die Rechnungen konnten nicht geladen werden.",
  "faktury.chybaMazania": "Die Rechnung konnte nicht gelöscht werden.",
  "faktury.chybaPdf": "Das PDF konnte nicht erstellt werden.",
  "faktury.chybaZdielania": "Das Teilen ist fehlgeschlagen.",
  "faktury.chybaUpomienky": "Die Mahnung konnte nicht gesendet werden.",

  "spolocne.spat": "Zurück",
  "spolocne.ulozit": "Speichern",
  "spolocne.zrusit": "Abbrechen",
  "spolocne.nacitavam": "Wird geladen…",
  "spolocne.km": "km",
};
