import type { Kluc } from "./sk";

/** Deutsch. Was hier fehlt, fällt auf Slowakisch zurück. */
export const de: Partial<Record<Kluc, string>> = {
  "tab.skener": "Scannen",
  "tab.faktury": "Rechnungen",
  "tab.vytvorit": "Erstellen",
  "tab.banka": "Bank",
  "tab.jazda": "Fahrtenbuch",
  "tab.navigacia": "Hauptnavigation",
  "panel.nastavenia": "Einstellungen",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Firma wechseln",
  "panel.bezFirmy": "Keine Firma",
  "panel.prehladAgend": "Alle Bereiche",
  "panel.vystaveneFaktury": "Ausgestellte Rechnungen",
  "panel.cenovePonuky": "Angebote",
  "panel.prijateDoklady": "Eingegangene Belege",
  "panel.pomoc": "Hilfe",
  "panel.nastavenieAplikacie": "App-Einstellungen",
  "panel.navody": "Faktero-Anleitungen",
  "panel.otvoriVPrehliadaci": "Wird im Browser geöffnet",
  "panel.blocky": "Belege und Kasse",
  "panel.nahlasitChybu": "Fehler oder Idee melden",
  "panel.otvoritNaWebe": "Faktero im Web öffnen",
  "panel.pravne": "Rechtliche Dokumente",
  "panel.odhlasit": "Abmelden",
  "panel.zavriet": "Schließen",
  "panel.jazyk": "Sprache",
  "domov.novaFaktura": "Neue Rechnung",
  "domov.novaFakturaPopis": "Kunde, Positionen, Fälligkeit — und direkt senden",
  "domov.vystaveneFaktury": "Ausgestellte Rechnungen",
  "domov.vystaveneFakturyPopis": "Wer noch nicht bezahlt hat, PDF und Versand",
  "domov.blocek": "Beleg mit QR-Code",
  "domov.blocekPopis": "Wird von der Finanzverwaltung geladen, samt Positionen",
  "domov.fakturaPdf": "Rechnung als PDF",
  "domov.fakturaPdfPopis": "Datei vom Telefon oder aus der Cloud wählen",
  "domov.viacstranovy": "Mehrseitiger Beleg",
  "domov.viacstranovyPopis": "Seite für Seite, gespeichert als ein PDF",
  "domov.prijateDoklady": "Eingegangene Belege",
  "domov.prijateDokladyPopis": "Belege und Rechnungen, die Sie bereits gescannt haben",
  "domov.pohybyNaUcte": "Kontobewegungen",
  "domov.pohybyNaUctePopis": "Ob das Geld angekommen ist — Saldo und letzte Zahlungen",
  "domov.novaJazda": "Neue Fahrt",
  "domov.novaJazdaPopis": "Das Telefon misst die Strecke, nur Start und Stopp",
  "jazdy.historia": "Fahrtenverlauf",
  "jazdy.charakter": "Art der Fahrt",
  "jazdy.sluzobna": "Geschäftlich",
  "jazdy.sukromna": "Privat",
  "jazdy.oznacenaSukromna": "Als privat markiert.",
  "jazdy.oznacenaSluzobna": "Als geschäftlich markiert.",
  "jazdy.jazda": "Fahrt",
  "jazdy.spolu": "Gesamt",
  "jazdy.starsie": "Ältere Fahrten",
  "jazdy.ziadne": "Noch keine Fahrten",
  "ponuky.nazov": "Angebote",
  "ponuky.nova": "Neues Angebot",
  "ponuky.novaDlha": "Neues Angebot",
  "ponuky.ziadne": "Noch keine Angebote",
  "ponuky.ziadnePopis":
    "Ein Angebot erstellen Sie wie eine Rechnung — und wenn der Kunde es annimmt, wird mit einem Tippen eine Rechnung daraus.",
  "ponuky.vytvorit": "Angebot erstellen",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Teilen",
  "ponuky.odoslat": "Senden",
  "ponuky.naFakturu": "Zur Rechnung",
  "ponuky.platiDo": "gültig bis",
  "ponuky.stav.vyfakturovana": "Abgerechnet",
  "ponuky.stav.zamietnuta": "Abgelehnt",
  "ponuky.stav.prijata": "Angenommen",
  "ponuky.stav.poPlatnosti": "Abgelaufen",
  "ponuky.stav.odoslana": "Gesendet",
  "ponuky.stav.navrh": "Entwurf",
  "ponuky.odberatel": "Kunde",
  "ponuky.polozky": "Positionen",
  "ponuky.pridajPolozku": "Position hinzufügen",
  "ponuky.vystavena": "Ausgestellt",
  "ponuky.poznamka": "Notiz",
  "ponuky.zaklad": "Nettobetrag",
  "ponuky.dph": "USt.",
  "ponuky.hladatOdberatela": "Kunden suchen…",
  "ponuky.novyOdberatel": "Neuer Kunde",
  "ponuky.nikNenajdeny": "Nichts gefunden.",
  "ponuky.zmenit": "ändern",
  "spolocne.spat": "Zurück",
  "spolocne.ulozit": "Speichern",
  "spolocne.zrusit": "Abbrechen",
  "spolocne.nacitavam": "Wird geladen…",
  "spolocne.km": "km",
};
