import type { Kluc } from "./sk";

/** English. Anything missing falls back to Slovak. */
export const en: Partial<Record<Kluc, string>> = {
  "tab.skener": "Scan",
  "tab.faktury": "Invoices",
  "tab.vytvorit": "Create",
  "tab.banka": "Bank",
  "tab.jazda": "Mileage",
  "tab.navigacia": "Main navigation",

  "panel.nastavenia": "Settings",
  "panel.firma": "Company",
  "panel.zmenitFirmu": "Switch company",
  "panel.bezFirmy": "No company",
  "panel.prehladAgend": "All sections",
  "panel.vystaveneFaktury": "Issued invoices",
  "panel.cenovePonuky": "Quotes",
  "panel.prijateDoklady": "Received documents",
  "panel.pomoc": "Help",
  "panel.nastavenieAplikacie": "App settings",
  "panel.navody": "Faktero guides",
  "panel.otvoriVPrehliadaci": "Opens in the browser",
  "panel.blocky": "Receipts and cash",
  "panel.nahlasitChybu": "Report a bug or idea",
  "panel.otvoritNaWebe": "Open Faktero on the web",
  "panel.pravne": "Legal documents",
  "panel.odhlasit": "Sign out",
  "panel.zavriet": "Close",
  "panel.jazyk": "Language",

  "domov.novaFaktura": "New invoice",
  "domov.novaFakturaPopis": "Customer, items, due date — and send it right away",
  "domov.vystaveneFaktury": "Issued invoices",
  "domov.vystaveneFakturyPopis": "Who hasn't paid, PDF and sending",
  "domov.blocek": "Receipt with a QR code",
  "domov.blocekPopis": "Loaded from the tax authority, items included",
  "domov.fakturaPdf": "Invoice as PDF",
  "domov.fakturaPdfPopis": "Pick a file from the phone or the cloud",
  "domov.viacstranovy": "Multi-page document",
  "domov.viacstranovyPopis": "Page by page, saved as one PDF",
  "domov.prijateDoklady": "Received documents",
  "domov.prijateDokladyPopis": "Receipts and invoices you have already scanned",
  "domov.pohybyNaUcte": "Account activity",
  "domov.pohybyNaUctePopis": "Whether the money arrived — balance and recent payments",
  "domov.novaJazda": "New trip",
  "domov.novaJazdaPopis": "The phone measures the distance, just start and stop",

  "jazdy.historia": "Trip history",
  "jazdy.charakter": "Trip type",
  "jazdy.sluzobna": "Business",
  "jazdy.sukromna": "Personal",
  "jazdy.oznacenaSukromna": "Marked as personal.",
  "jazdy.oznacenaSluzobna": "Marked as business.",
  "jazdy.jazda": "Trip",
  "jazdy.spolu": "Total",
  "jazdy.starsie": "Older trips",
  "jazdy.ziadne": "No trips yet",

  "ponuky.nazov": "Quotes",
  "ponuky.nova": "New quote",
  "ponuky.novaDlha": "New quote",
  "ponuky.ziadne": "No quotes yet",
  "ponuky.ziadnePopis":
    "You make a quote the same way as an invoice — and when the customer accepts it, one tap turns it into one.",
  "ponuky.vytvorit": "Create quote",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Share",
  "ponuky.odoslat": "Send",
  "ponuky.naFakturu": "To invoice",
  "ponuky.platiDo": "valid until",
  "ponuky.stav.vyfakturovana": "Invoiced",
  "ponuky.stav.zamietnuta": "Rejected",
  "ponuky.stav.prijata": "Accepted",
  "ponuky.stav.poPlatnosti": "Expired",
  "ponuky.stav.odoslana": "Sent",
  "ponuky.stav.navrh": "Draft",
  "ponuky.odberatel": "Customer",
  "ponuky.polozky": "Items",
  "ponuky.pridajPolozku": "Add item",
  "ponuky.vystavena": "Issued",
  "ponuky.poznamka": "Note",
  "ponuky.zaklad": "Subtotal",
  "ponuky.dph": "VAT",
  "ponuky.hladatOdberatela": "Search customers…",
  "ponuky.novyOdberatel": "New customer",
  "ponuky.nikNenajdeny": "Nothing found.",
  "ponuky.zmenit": "change",

  "domov.skupina.fakturacia": "Invoicing",
  "domov.skupina.skenovanie": "Scanning documents",
  "domov.skupina.banka": "Bank",
  "domov.skupina.jazdy": "Mileage",

  /* vystavené faktúry */
  "faktury.nazov": "Issued invoices",
  "faktury.hladat": "Search number or customer",
  "faktury.nacitavam": "Loading invoices…",
  "faktury.ziadne": "No invoices yet",
  "faktury.vystavPrvu": "Issue your first invoice",
  "faktury.nicSaNenaslo": "Nothing found",
  "faktury.bezOdberatela": "No customer",
  "faktury.stav.navrh": "Draft",
  "faktury.stav.vystavena": "Issued",
  "faktury.stav.odoslana": "Sent",
  "faktury.stav.uhradena": "Paid",
  "faktury.stav.neuhradena": "Unpaid",
  "faktury.stav.splatna": "Due",
  "faktury.stav.poSplatnosti": "Overdue",
  "faktury.stav.stornovana": "Cancelled",
  "faktury.otvoritPdf": "Open PDF",
  "faktury.zdielat": "Share invoice",
  "faktury.zdielatPopis": "Send it via WhatsApp, Messenger or save to files",
  "faktury.poslatEmailom": "Send by e-mail",
  "faktury.oznacitUhradenu": "Mark as paid",
  "faktury.oznacitPopis": "When the payment arrived outside bank matching",
  "faktury.oznacenaUhradena": "Marked as paid",
  "faktury.upravit": "Edit invoice",
  "faktury.upravitPopis": "Items, dates and note",
  "faktury.zmazat": "Delete invoice",
  "faktury.zmazatPopis":
    "It disappears from the list, but the number stays taken — no gap in the sequence.",
  "faktury.zmazatKratke": "Delete",
  "faktury.ponechat": "Keep",
  "faktury.mazem": "Deleting…",
  "faktury.naPrezretie": "Invoice preview",
  "faktury.bezPripojenia": "Offline — showing the last loaded invoices.",
  "faktury.bezPripojeniaNacitanie": "Invoices cannot be loaded while offline",
  "faktury.odlozenaVystavena": "The queued invoice has been issued.",
  "faktury.odosluSaSamy":
    "They will send themselves as soon as there is a signal. No need to think about it.",
  "faktury.chybaNacitania": "The invoices could not be loaded.",
  "faktury.chybaMazania": "The invoice could not be deleted.",
  "faktury.chybaPdf": "The PDF could not be prepared.",
  "faktury.chybaZdielania": "Sharing failed.",
  "faktury.chybaUpomienky": "The reminder could not be sent.",

  "spolocne.spat": "Back",
  "spolocne.ulozit": "Save",
  "spolocne.zrusit": "Cancel",
  "spolocne.nacitavam": "Loading…",
  "spolocne.km": "km",
};
