import type { Kluc } from "./sk";

/** English. Anything missing falls back to Slovak. */
export const en: Partial<Record<Kluc, string>> = {
  "tab.skener": "Scan",
  "tab.faktury": "Invoices",
  "tab.vytvorit": "Create",
  "tab.banka": "Bank",
  "tab.jazda": "Mileage",
  "tab.navigacia": "Main navigation",

  "panel.nastavenia": "Settings",
  "panel.firma": "Company",
  "panel.zmenitFirmu": "Switch company",
  "panel.bezFirmy": "No company",
  "panel.prehladAgend": "All sections",
  "panel.vystaveneFaktury": "Issued invoices",
  "panel.cenovePonuky": "Quotes",
  "panel.prijateDoklady": "Received documents",
  "panel.pomoc": "Help",
  "panel.nastavenieAplikacie": "App settings",
  "panel.navody": "Faktero guides",
  "panel.otvoriVPrehliadaci": "Opens in the browser",
  "panel.blocky": "Receipts and cash",
  "panel.nahlasitChybu": "Report a bug or idea",
  "panel.otvoritNaWebe": "Open Faktero on the web",
  "panel.pravne": "Legal documents",
  "panel.odhlasit": "Sign out",
  "panel.zavriet": "Close",
  "panel.jazyk": "Language",

  "domov.novaFaktura": "New invoice",
  "domov.novaFakturaPopis": "Customer, items, due date — and send it right away",
  "domov.vystaveneFaktury": "Issued invoices",
  "domov.vystaveneFakturyPopis": "Who hasn't paid, PDF and sending",
  "domov.blocek": "Receipt with a QR code",
  "domov.blocekPopis": "Loaded from the tax authority, items included",
  "domov.fakturaPdf": "Invoice as PDF",
  "domov.fakturaPdfPopis": "Pick a file from the phone or the cloud",
  "domov.viacstranovy": "Multi-page document",
  "domov.viacstranovyPopis": "Page by page, saved as one PDF",
  "domov.prijateDoklady": "Received documents",
  "domov.prijateDokladyPopis": "Receipts and invoices you have already scanned",
  "domov.pohybyNaUcte": "Account activity",
  "domov.pohybyNaUctePopis": "Whether the money arrived — balance and recent payments",
  "domov.novaJazda": "New trip",
  "domov.novaJazdaPopis": "The phone measures the distance, just start and stop",

  "jazdy.historia": "Trip history",
  "jazdy.charakter": "Trip type",
  "jazdy.sluzobna": "Business",
  "jazdy.sukromna": "Personal",
  "jazdy.oznacenaSukromna": "Marked as personal.",
  "jazdy.oznacenaSluzobna": "Marked as business.",
  "jazdy.jazda": "Trip",
  "jazdy.spolu": "Total",
  "jazdy.starsie": "Older trips",
  "jazdy.ziadne": "No trips yet",

  "ponuky.nazov": "Quotes",
  "ponuky.nova": "New quote",
  "ponuky.novaDlha": "New quote",
  "ponuky.ziadne": "No quotes yet",
  "ponuky.ziadnePopis":
    "You make a quote the same way as an invoice — and when the customer accepts it, one tap turns it into one.",
  "ponuky.vytvorit": "Create quote",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Share",
  "ponuky.odoslat": "Send",
  "ponuky.naFakturu": "To invoice",
  "ponuky.platiDo": "valid until",
  "ponuky.stav.vyfakturovana": "Invoiced",
  "ponuky.stav.zamietnuta": "Rejected",
  "ponuky.stav.prijata": "Accepted",
  "ponuky.stav.poPlatnosti": "Expired",
  "ponuky.stav.odoslana": "Sent",
  "ponuky.stav.navrh": "Draft",
  "ponuky.odberatel": "Customer",
  "ponuky.polozky": "Items",
  "ponuky.pridajPolozku": "Add item",
  "ponuky.vystavena": "Issued",
  "ponuky.poznamka": "Note",
  "ponuky.zaklad": "Subtotal",
  "ponuky.dph": "VAT",
  "ponuky.hladatOdberatela": "Search customers…",
  "ponuky.novyOdberatel": "New customer",
  "ponuky.nikNenajdeny": "Nothing found.",
  "ponuky.zmenit": "change",

  "domov.skupina.fakturacia": "Invoicing",
  "domov.skupina.skenovanie": "Scanning documents",
  "domov.skupina.banka": "Bank",
  "domov.skupina.jazdy": "Mileage",

  /* vystavené faktúry */
  "faktury.nazov": "Issued invoices",
  "faktury.hladat": "Search number or customer",
  "faktury.nacitavam": "Loading invoices…",
  "faktury.ziadne": "No invoices yet",
  "faktury.vystavPrvu": "Issue your first invoice",
  "faktury.nicSaNenaslo": "Nothing found",
  "faktury.bezOdberatela": "No customer",
  "faktury.stav.navrh": "Draft",
  "faktury.stav.vystavena": "Issued",
  "faktury.stav.odoslana": "Sent",
  "faktury.stav.uhradena": "Paid",
  "faktury.stav.neuhradena": "Unpaid",
  "faktury.stav.splatna": "Due",
  "faktury.stav.poSplatnosti": "Overdue",
  "faktury.stav.stornovana": "Cancelled",
  "faktury.otvoritPdf": "Open PDF",
  "faktury.zdielat": "Share invoice",
  "faktury.zdielatPopis": "Send it via WhatsApp, Messenger or save to files",
  "faktury.poslatEmailom": "Send by e-mail",
  "faktury.oznacitUhradenu": "Mark as paid",
  "faktury.oznacitPopis": "When the payment arrived outside bank matching",
  "faktury.oznacenaUhradena": "Marked as paid",
  "faktury.upravit": "Edit invoice",
  "faktury.upravitPopis": "Items, dates and note",
  "faktury.zmazat": "Delete invoice",
  "faktury.zmazatPopis":
    "It disappears from the list, but the number stays taken — no gap in the sequence.",
  "faktury.zmazatKratke": "Delete",
  "faktury.ponechat": "Keep",
  "faktury.mazem": "Deleting…",
  "faktury.naPrezretie": "Invoice preview",
  "faktury.bezPripojenia": "Offline — showing the last loaded invoices.",
  "faktury.bezPripojeniaNacitanie": "Invoices cannot be loaded while offline",
  "faktury.odlozenaVystavena": "The queued invoice has been issued.",
  "faktury.odosluSaSamy":
    "They will send themselves as soon as there is a signal. No need to think about it.",
  "faktury.chybaNacitania": "The invoices could not be loaded.",
  "faktury.chybaMazania": "The invoice could not be deleted.",
  "faktury.chybaPdf": "The PDF could not be prepared.",
  "faktury.chybaZdielania": "Sharing failed.",
  "faktury.chybaUpomienky": "The reminder could not be sent.",

  /* nová faktúra */
  "nf.komuFakturujete": "Who are you invoicing?",
  "nf.zaCoFakturujete": "What are you invoicing for?",
  "nf.skontrolujte": "Check the invoice",
  "nf.skontrolujteZalohovu": "Check the proforma",
  "nf.krok": "Step {n} of 3",
  "nf.krokZalohova": "Step 1 of 3 · proforma",
  "nf.faktura": "Invoice",
  "nf.zalohova": "Proforma",
  "nf.odberatel": "Customer",
  "nf.hladatOdberatela": "Search customers",
  "nf.novyOdberatel": "New customer",
  "nf.ziadnyOdberatel": "You don't have any customers yet.",
  "nf.nicSaNenaslo": "Nothing found.",
  "nf.nacitavamOdberatelov": "Loading customers…",
  "nf.nazov": "Name",
  "nf.zadajteNazov": "Enter the customer name.",
  "nf.podlaIco": "The name and address are filled in from the company ID",
  "nf.hladamVRegistri": "Searching the registry…",
  "nf.udajeDoplnene": "Details filled in from the registry",
  "nf.psc": "Postcode",
  "nf.email": "The invoice can be sent to this address right away",
  "nf.odberatelPridany": "Customer added",
  "nf.chybaOdberatela": "The customer could not be saved.",
  "nf.polozky": "Items",
  "nf.nazovPolozky": "Item name",
  "nf.mnozstvo": "Quantity",
  "nf.pridajtePolozku": "Add an item",
  "nf.odstranitPolozku": "Remove item",
  "nf.zCennika": "From price list",
  "nf.vlastna": "Custom",
  "nf.cennik": "Price list",
  "nf.hladatPolozku": "Search items",
  "nf.zopakovatPoslednu": "Repeat the last invoice",
  "nf.splatnost": "Due date",
  "nf.splatnostSkor": "The due date cannot be before the issue date.",
  "nf.sposobUhrady": "Payment method",
  "nf.hotovost": "Cash",
  "nf.poznamkaNad": "Note above the items",
  "nf.poznamkaPod": "Note below the items",
  "nf.priklad": "For example: as per order no. 2026/114",
  "nf.zaklad": "Subtotal",
  "nf.naUhradu": "Amount due",
  "nf.dalej": "Next",
  "nf.zrusit": "Cancel",
  "nf.zavriet": "Close",
  "nf.ulozitPokracovat": "Save and continue",
  "nf.ulozitZmeny": "Save changes",
  "nf.ukladam": "Saving…",
  "nf.ukladamZmeny": "Saving changes…",
  "nf.vystavit": "Issue invoice",
  "nf.vystavitZalohovu": "Issue proforma invoice",
  "nf.vystavujem": "Issuing the invoice…",
  "nf.vystavena": "Invoice issued",
  "nf.maCislo": "The invoice has been numbered",
  "nf.odlozena": "The invoice is queued on the phone",
  "nf.naPrezretie": "Invoice preview",
  "nf.otvoritPdf": "Open PDF",
  "nf.zdielat": "Share invoice",
  "nf.zdielatPopis": "Send it via WhatsApp, Messenger or save to files",
  "nf.poslatEmailom": "Send by e-mail",
  "nf.odoslane": "Sent",
  "nf.odosielam": "Sending the invoice…",
  "nf.bezEmailu":
    "The customer has no e-mail, so the invoice cannot be sent. Add one on their card.",
  "nf.zalohy": "Unapplied proformas for this customer",
  "nf.hladamZalohy": "Looking for proformas…",
  "nf.ziadnaZaloha": "No proforma to apply",
  "nf.pridatZalohovu": "Add proforma invoice",
  "nf.bezPripojenia": "Offline — working with the last loaded data.",
  "nf.bezPripojeniaVystavit":
    "Without a connection and without saved customers an invoice cannot be issued. Open this screen once while online.",
  "nf.zalohovaBezPripojenia": "A proforma invoice cannot be issued while offline.",
  "nf.opravaBezPripojenia": "Editing an invoice requires a connection.",
  "nf.chybaPodkladov": "The data could not be loaded.",
  "nf.chybaNacitania": "The invoice could not be loaded.",
  "nf.chybaVystavenia": "The invoice could not be issued.",
  "nf.chybaZmien": "The changes could not be saved.",
  "nf.chybaPdf": "The PDF could not be prepared.",
  "nf.chybaZdielania": "Sharing failed.",

  /* prijaté doklady a banka */
  "pd.nazov": "Received documents",
  "pd.hladat": "Search supplier or number",
  "pd.nacitavam": "Loading documents…",
  "pd.ziadne": "No documents yet",
  "pd.ziadnePopis": "Scanned receipts and invoices will appear here.",
  "pd.nicSaNenaslo": "Nothing found",
  "pd.skusteInak": "Try a different search.",
  "pd.bezDodavatela": "No supplier",
  "pd.neprecitany": "Unread document",
  "pd.zFinancnejSpravy": "From the tax authority",
  "pd.sQrKodom": "· with QR code",
  "pd.cisloDokladu": "Document number",
  "pd.poznamka": "Note",
  "pd.sposobUhrady": "Payment method",
  "pd.hotovost": "Cash",
  "pd.kartou": "By card",
  "pd.prevodom": "Bank transfer",
  "pd.sposobZmeneny": "Payment method changed",
  "pd.otvoritPdf": "Open PDF",
  "pd.nacitavamPrilohu": "Loading attachment…",
  "pd.presunut": "Move to received invoices",
  "pd.presuvam": "Moving…",
  "pd.presunuty": "The document is now among received invoices.",
  "pd.zmazat": "Delete document",
  "pd.zmazatKratke": "Delete",
  "pd.naozajZmazat": "Really delete this document?",
  "pd.nedaSaVratit": "This cannot be undone.",
  "pd.zmazany": "Document deleted",
  "pd.ponechat": "Keep",
  "pd.zrusit": "Cancel",
  "pd.sparovat": "Match",
  "pd.anoPatriKSebe": "Yes, they belong together",
  "pd.uhradenyZUctu": "Marked as paid from the account.",
  "pd.parovanieZrusene": "Matching cancelled.",
  "pd.chybaParovania": "The match could not be made.",
  "pd.chybaZrusenia": "It could not be cancelled.",
  "pd.chybaNacitania": "The documents could not be loaded.",
  "pd.bezPripojenia": "Documents cannot be loaded while offline",
  "pd.odlozeneOdoslu": "Queued receipts will send themselves once the signal is back.",
  "pd.bezSignalu": "No signal yet — I will try again on my own.",
  "pd.zahodit": "Discard queued document",
  "pd.odoslat": "Send",
  "banka.ucet": "Account",
  "banka.vsetky": "All",
  "banka.nacitavam": "Loading transactions…",
  "banka.ziadnePohyby": "No transactions yet",
  "banka.stiahnut": "Fetch from the bank",
  "banka.stahujem": "Fetching from the bank…",
  "banka.ziadneNove": "No new transactions.",
  "banka.prijataPlatba": "Incoming payment",
  "banka.odchadzajucaPlatba": "Outgoing payment",
  "banka.dnes": "Today",
  "banka.vcera": "Yesterday",
  "banka.nesynchronizovane": "not synced yet",
  "banka.bezUctu": "The company has no bank account connected",
  "banka.pripojenieNaWebe":
    "The account is connected on the web — the bank requires a login and consent that is hard to complete on a phone.",
  "banka.bezPripojenia": "Accounts cannot be loaded while offline",
  "banka.lenSoSignalom":
    "Balances and transactions can only be viewed with a signal — nothing is stored on the phone.",
  "banka.neodpovedala": "The bank did not respond. Try again in a moment.",
  "banka.chybaNacitania": "The transactions could not be loaded.",

  /* kniha jázd */
  "jz.novaJazda": "New trip",
  "jz.zacatJazdu": "Start trip",
  "jz.jazdaBezi": "Trip in progress",
  "jz.jazdaPozastavena": "Trip paused",
  "jz.meranieNebezi": "not measuring yet",
  "jz.pozastavene": "paused — movement is not counted",
  "jz.pozastavitMeranie": "Pause measuring",
  "jz.pokracovatVMerani": "Resume measuring",
  "jz.tuknutimPozastavite": "Tap the circle to pause measuring",
  "jz.tuknutimPokracujete": "Tap the circle to resume",
  "jz.ukoncitAUlozit": "Finish and save trip",
  "jz.ukladamJazdu": "Saving the trip…",
  "jz.ucelCesty": "Purpose",
  "jz.ucelPriklad": "e.g. service at a customer",
  "jz.ulozeneSluzobna": "Saved as business",
  "jz.ulozeneSukromna": "Saved as personal",
  "jz.bezSignaluOdoslana": "The trip recorded offline has been sent",
  "jz.chybaUlozenia": "The trip could not be saved.",
  "jz.chybaGps": "GPS could not be started.",
  "jz.chybaPokracovania": "Measuring could not be resumed.",
  "jz.rozpoznanaBezi": "A detected trip is running",
  "jz.ukoncitJazdu": "Finish trip",
  "jz.ukoncujem": "Finishing…",
  "jz.zahodit": "Discard",
  "jz.zahoditOtazka": "Discard this trip? It will not be recorded.",
  "jz.ukoncena": "Trip finished — classify it below.",
  "jz.zahodena": "Trip discarded.",
  "jz.vozidloPreJazdu": "Vehicle for the detected trip",
  "jz.telefonNevie": "The phone does not know which car you got into — check it for every trip.",
  "jz.rozpoznavat": "Detect trips automatically",
  "jz.detekciaZapnuta": "Trip detection is on",
  "jz.detekciaNemaAkoBezat": "Detection is on, but it cannot run",
  "jz.vyzadujePolohu": "Requires the „Always“ location permission.",
  "jz.akoFunguje": "How detection works",
  "jz.ukazatTrasu": "Show route",
  "jz.skrytTrasu": "Hide route",
  "jz.historia": "history",
  "jz.noveVozidlo": "New vehicle",
  "jz.pridatVozidlo": "Add vehicle",
  "jz.vozidloPridane": "Vehicle added",
  "jz.chybaVozidla": "The vehicle could not be added.",
  "jz.zadajteNazovVozidla": "Enter the vehicle name.",
  "jz.evidencneCislo": "Registration number",
  "jz.nazovVozidlaPriklad": "e.g. Škoda Octavia",
  "jz.ukladamVozidlo": "Saving the vehicle…",
  "jz.nacitavamVozidla": "Loading vehicles…",
  "jz.bezVozidla": "The company has no vehicle",
  "jz.pridajteHo": "Add one here — a name and plate are enough, the rest can be filled in on the web.",
  "jz.commander": "This car trips come from Commander",
  "jz.bezPripojenia": "Vehicles cannot be loaded while offline",
  "jz.bezZoznamu": "No list is stored on the phone yet. Open this screen once while online.",
  "jz.nepovinneCena": "Optional, but without it the trip cost comes out as zero.",

  /* skener, notifikácie, čísla dopredu */
  "jz.nahravamJazdu": "Recording trip",
  "jz.spustenaRucne": "started manually",
  "jz.otvoritPrebiehajucu": "Open trip in progress",
  "qr.namierte": "Point at the QR code",
  "qr.zrusitSkenovanie": "Cancel scanning",
  "qr.kameraNejde": "The camera could not be started. Try taking a photo of the receipt.",
  "qr.kameraZamietnuta": "Camera access is denied. Allow it in your phone settings.",
  "push.nazov": "Notifications",
  "push.zistujem": "Checking…",
  "push.zaregistrovane": "This device is registered, notifications will arrive.",
  "push.neznameZariadenie": "The server does not know this device yet.",
  "push.povolenieVTelefone": "Permission on the phone:",
  "push.lenVApke": "mobile app only",
  "push.pluginNedostupny": "plugin unavailable",
  "push.registraciaZlyhala": "registration failed",
  "push.zaregistrovatZnova": "Register again",
  "push.skusitZaregistrovat": "Try registering",
  "spolocne.chyba": "Error",
  "cisla.nazov": "Issue invoices offline with a number",
  "cisla.vypnutePopis": "Without it, an offline invoice is queued and issued automatically once you are online — it gets its number only then.",
  "cisla.zapnutePopis": "Numbers ready: {pocet}. An invoice issued offline gets its number right away, so you can hand it over on the spot.",
  "cisla.zapnut": "Turn on",
  "cisla.vypnut": "Turn off",
  "cisla.vypnute": "Turned off. Unused numbers were returned to the sequence.",
  "cisla.zapnute": "Turned on. The app has {pocet} numbers ready.",
  "cisla.trebaPripojenie": "Turning it on needs a connection — the app requests the numbers from the server.",
  "cisla.nepodariloVypytat": "The numbers could not be requested. Try again in a moment.",
  "cisla.nepodariloPrepnut": "It could not be switched.",

  /* skener, firma, registrácia */
  "sken.naskenujte": "Scan the QR code on the receipt",
  "sken.aleboOdfotte": "or take a photo of the receipt",
  "sken.kameraNejde": "You can still photograph the receipt or pick it from files — the buttons below work.",
  "sken.odfotit": "Take a photo",
  "sken.zGalerie": "From gallery",
  "sken.uhrada": "Payment",
  "sken.karta": "Card",
  "sken.kategoria": "Expense category",
  "sken.nezaradene": "Uncategorised",
  "sken.pdfSubor": "PDF file",
  "sken.viacstranovy": "Multi-page",
  "vf.vytvorteSiFirmu": "Create your company",
  "vf.pridatFirmu": "Add a company",
  "vf.podnadpis": "These details appear on your invoices",
  "vf.vytvaram": "Creating…",
  "vf.vytvoritFirmu": "Create company",
  "vf.uvod": "The name is enough — everything else can be added later in settings. Enter the company ID and we will pull the address and tax numbers from the register.",
  "vf.nazovFirmy": "Company name",
  "vf.ico": "Company ID",
  "vf.dic": "Tax ID",
  "vf.icDph": "VAT ID",
  "vf.ulica": "Street and number",
  "vf.mesto": "City",
  "vf.psc": "Postcode",
  "vf.iban": "IBAN",
  "vf.ibanHint": "Your customer pays by it — you can add it later.",
  "vf.email": "E-mail",
  "vf.telefon": "Phone",
  "vf.hladamVRegistri": "Searching the register…",
  "vf.trebaPripojenie": "Creating a company needs a connection. Try again when you have signal.",
  "vf.nepodariloVytvorit": "The company could not be created.",
  "vf.vytvorena": "The company was created.",
  "vf.chyba.nazov": "Enter the company name.",
  "vf.chyba.ico": "The company ID has 6 to 8 digits.",
  "vf.chyba.email": "Enter a valid company e-mail.",
  "vf.chyba.iban": "The IBAN is not in a valid format.",
  "reg.potvrdteEmail": "Confirm your e-mail",
  "reg.potvrdenieText": "The account {email} has been created. We sent it a link — open it and come back here. The app notices the confirmation on its own; if not, use the button below. You cannot sign in without confirming.",
  "reg.spamPriecinok": "If the e-mail does not arrive within a few minutes, check your spam folder.",
  "reg.overujem": "Checking…",
  "reg.uzSomPotvrdil": "I have confirmed, continue",
  "reg.posielam": "Sending…",
  "reg.poslatZnova": "Send the e-mail again",
  "reg.spatNaPrihlasenie": "Back to sign-in",
  "reg.vytvorteSiUcet": "Create your account",
  "reg.zadarmo": "30 days free on the Premium plan. No card needed.",
  "reg.meno": "Full name",
  "reg.email": "E-mail",
  "reg.heslo": "Password (at least 8 characters)",
  "reg.suhlasPodmienky": "I agree to the {odkaz}.",
  "reg.obchodnePodmienky": "Terms and Conditions",
  "reg.suhlasGdpr": "I acknowledge the {odkaz}.",
  "reg.spracuvanieUdajov": "Privacy Notice",
  "reg.vytvaram": "Creating…",
  "reg.vytvoritUcet": "Create account",
  "reg.uzMamUcet": "I already have an account, sign in",
  "reg.ucetJeVytvoreny": "Your account has been created.",
  "reg.registraciaZlyhala": "Registration failed.",
  "reg.nepotvrdene": "It is not confirmed yet. Open the link from the e-mail and try again.",
  "reg.emailPoslanyZnova": "We sent the e-mail again.",
  "reg.chyba.meno": "Enter your full name.",
  "reg.chyba.email": "Enter a valid e-mail.",
  "reg.chyba.heslo": "The password must have at least 8 characters.",
  "reg.chyba.suhlasy": "Confirm both consents.",

  /* cenové ponuky */
  "ponuky.bezEmailu": "The customer has no e-mail. Add one on their record.",
  "ponuky.odoslatOtazka": "Send quote {cislo} to {email}?",
  "ponuky.odoslana": "The quote was sent.",
  "ponuky.uzFakturovana": "An invoice has already been created from this quote.",
  "ponuky.naFakturuOtazka": "Create an invoice from quote {cislo}?",
  "ponuky.fakturaVytvorena": "The invoice was created.",
  "ponuky.platiDoSkratka": "valid until {den}",
  "ponuky.vyberteOdberatela": "Choose a customer.",
  "ponuky.doplntePolozku": "Add at least one item.",
  "ponuky.platnostPredVystavenim": "Validity cannot end before the issue date.",
  "ponuky.nepodariloVytvorit": "The quote could not be created.",
  "ponuky.vytvaram": "Creating the quote…",

  /* kniha jázd — zvyšok */
  "jz.odCasu": "From {cas}. When you have arrived, end it — otherwise it stops on its own only after five minutes of standing.",
  "jz.rozpoznalaJazdu": "The app detected a trip",
  "jz.rozpoznalaJazdy": "The app detected trips ({pocet})",
  "jz.commanderZvysok": ", so the phone does not have to measure them — pick another car, or leave detection off.",
  "jz.typJazdy": "Trip type",
  "jz.vozidlo": "Vehicle",
  "jz.nazovVozidla": "Name",
  "jz.spotreba": "Consumption (l/100 km)",
  "jz.spotrebaPriklad": "e.g. 6.5",
  "jz.vsimneSi": "The app notices the trip on its own and asks in a notification whether it was for business.",
  "jz.lenPocasPouzivania": "If you allowed location only “while using the app”, keep the app open — once the screen goes off the phone stops measuring and the distance would come out wrong. With “Always” it keeps measuring in your pocket.",
  "jz.vyberteVozidlo": "Choose a vehicle.",
  "jz.odoslanychJazd": "{pocet} trips recorded offline were sent",
  "jz.rozpoznanaUlozena": "Detected trip saved — {km} km, {auto}",
  "jz.bezPolohy": "We measured no location, so the trip was not saved. Try outdoors — indoors the location is inaccurate — and set location access to “Always”.",
  "jz.ulozenaVTelefone": "Trip saved on the phone — {km} km. It will be sent once you are online.",
  "jz.ulozenaKm": "Trip saved — {km} km",
  "jz.historiaVozidla": "Trip history — {auto}",

  /* bočný panel */
  "panel.nadpis": "Settings panel",
  "panel.prihlasenyAko": "Signed in as",
  "panel.vsetkoNaJednej": "Everything the app can do, on one screen",
  "panel.ucetPamat": "Account and its closure, storage, connection, version",
  "panel.ekasaPopis": "How eKasa receipts are read",
  "panel.napisteNam": "Tell us what is broken or what would help",
  "panel.zvysokAplikacie": "Invoices, stock and the rest of the app",
  "panel.pravnePopis": "Terms, privacy and the rest — opens in the browser",
  "panel.biometria": "Biometric sign-in",
  "panel.biometriaZapnuta": "Asks when the app starts",
  "panel.biometriaVypnuta": "Off",
  "panel.biometriaNedostupna": "Biometrics are not available on this device.",
  "panel.rychleZapnute": "Quick sign-in turned on",
  "panel.rychleVypnute": "Quick sign-in turned off",
  "panel.nepodariloZapnut": "Could not be turned on",

  /* doklady, faktúry, jazdy, banka — zvyšok */
  "pd.doklad": "Receipt",
  "pd.ico": "Company ID",
  "pd.icDph": "VAT ID",
  "faktury.vystavenychPocet": "Invoices issued: {pocet}.",
  "faktury.neuhradene": "Unpaid",
  "faktury.odosluSaSamy2": "They will be sent on their own as soon as you have signal. Nothing to remember.",
  "faktury.bezZoznamu": "No list is stored on the phone yet. Open this screen once with internet and it will work offline afterwards.",
  "faktury.vystavena": "Issued",
  "faktury.splatna": "Due",
  "faktury.uhradena": "Paid",
  "faktury.odoslana": "Sent",
  "faktury.cisloOstava": "It disappears from the list, but the number stays taken — no gap appears in the sequence.",
  "jazdy.nacitavam": "Loading trips…",
  "jazdy.prvaPribudne": "The first one appears after you end a measurement — or is pulled from the GPS unit when the vehicle is connected.",
  "jazdy.spoluCelaHistoria": "Total for the whole history",
  "jazdy.spoluPoslednych": "Total for the last {pocet} trips",
  "jazdy.nacitatStarsie": "Load older trips",
  "jazdy.chybaStarsich": "Older trips could not be loaded.",
  "banka.nazov": "Bank",
  "banka.vsetkyUcty": "All",
  "banka.ucetSkratka": "account",

  /* banka — prepínač účtov */
  "banka.ucetVelke": "Account",
  "banka.zostatokSpolu": "Total balance",

  /* nová faktúra — zvyšok */
  "nf.zalohovaVysvetlenie": "A proforma invoice is a request for payment, not a tax document — it stays out of VAT and gets a number from its own sequence. Once paid, you issue a regular invoice and settle the deposit on it.",
  "nf.ico": "Company ID",
  "nf.ulica": "Street",
  "nf.mesto": "City",
  "nf.dic": "Tax ID",
  "nf.icDph": "VAT ID",
  "nf.emailPole": "E-mail",
  "nf.spolu": "Total",
  "nf.dph": "VAT",
  "nf.vystavenie": "Issue date",
  "nf.bezIbanu": "The company has no IBAN — there will be nowhere to pay on the invoice. Add it on the web in the company settings.",
  "nf.ziadnaZalohaPopis": "This customer has no unsettled proforma invoice. To issue one, choose {zalohova} in the first step of a new invoice.",
  "nf.cisloJeVase": "The number is yours and will not be given to anyone else — you can hand it to the customer. The PDF is created and the invoice sent on its own once you have signal.",
  "nf.odlozenaPopis": "It will be issued with a number on its own once you have signal. It has no number yet, so you cannot dictate it to the customer — if you need that, turn on issuing with numbers in advance in the settings.",
  "nf.hotovo": "Done",
  "nf.pripravujemPdf": "Preparing the PDF…",
  "nf.bezPripojeniaNadpis": "Offline",

  /* hlavná obrazovka appky */
  "app.chybaObrazovky": "This screen could not be opened.",
  "app.slabePripojenie": "It is usually a weak connection. Try again, or sign in anew.",
  "app.skusitZnova": "Try again",
  "app.prihlasitNanovo": "Sign in anew",
  "app.diagnostika": "Diagnostics",
  "app.diagnostikaPopis": "What the app sees on the phone — bundle, storage, connection.",
  "app.novaVerzia": "A newer version of the app is available — tap to update",
  "app.prihlasenie": "Sign in",
  "app.prihlasteSa": "Sign in to your Faktero account.",
  "app.odomknutBiometriou": "Unlock with biometrics",
  "app.nemateUcet": "No account yet?",
  "app.zaregistrujteSa": "Sign up",
  "app.zabudnuteHeslo": "Reset a forgotten password at faktero.sk.",
  "app.zamknute": "Faktero is locked",
  "app.odomknitePokracujte": "Unlock it with biometrics and pick up where you left off.",
  "app.pridatDalsiuFirmu": "Add another company",
  "app.odvolatZiadost": "Withdraw the request",
  "app.zFakturyPrecita": "The supplier, date, amount and VAT are read from the invoice. Check the data before saving.",
  "app.vyberteUhradu": "Choose a payment method",
  "app.povinne": "Required",
  "app.vyberteMoznost": "Choose one of the options — the receipt cannot be saved without it.",
  "app.hotovostnyDoklad": "A cash receipt reduces the cash balance.",
  "app.fotkaDokladu": "Photo of the receipt",
  "app.prilozenePdf": "Attached PDF",
  "app.odfotitZnova": "Take another photo",
  "app.otvaram": "Opening…",
  "app.skenerDokladov": "Receipt scanner",
  "app.ucet": "Account",
  "app.email": "E-mail",
  "app.heslo": "Password",
  "app.vyberteFirmu": "Choose a company",
  "app.doVybranejFirmy": "Receipts are saved to the selected company",
  "app.staciNazov": "The name is enough, the rest can be added later",
  "app.fakturyADoklady": "Invoices and receipts",
  "app.citamDoklad": "Reading the receipt…",
  "app.ukladamDoklad": "Saving the receipt…",
  "app.nasnimatQr": "Scan the QR code",
  "app.namierteNaBlocek": "Point at the QR code on the receipt",
  "app.odfotitBlocek": "Photograph the whole receipt",
  "app.qrNaFotke": "The QR code is found in the photo too",
  "app.vybratSubor": "Choose a file",
  "app.pdfAleboObrazok": "PDF or image of the invoice",
  "app.stranySaSpoja": "The pages are merged into one PDF",
  "app.skontrolujteDoklad": "Check the receipt",
  "app.odfotitDoklad": "Photograph the receipt",
  "app.papierovyDoklad": "You have to keep the paper receipt anyway — the photo replaces it",
  "app.vyplnteEmailHeslo": "Fill in both the e-mail and the password.",
  "app.prilohaNenahrata": "The attachment could not be uploaded, the receipt will be saved without it.",
  "app.dokladUlozeny": "Receipt saved",
  "app.bezPripojeniaFirmy": "No connection, and no list of companies is stored on the phone yet. Open the app once with internet.",
  "app.fakturaOdoslana": "The invoice issued offline has been sent.",
  "app.odoslanychOdlozenych": "Queued invoices sent: {pocet}.",
  "app.jazdaUlozena": "Detected trip saved",
  "app.jazdUlozenych": "{pocet} detected trips saved",
  "app.prihlasenieZlyhalo": "Sign-in failed.",
  "app.prihlasujem": "Signing in…",
  "app.prihlasitSa": "Sign in",
  "app.odomykam": "Unlocking…",
  "app.odomknut": "Unlock",
  "app.bezFirmy": "No company belongs to this account yet. Without one the receipts have nowhere to go — create it right here.",
  "app.blocekQr": "Receipt with a QR code",
  "app.fakturaPdf": "Invoice as PDF",
  "app.viacstranovyDoklad": "Multi-page receipt",
  "app.nepodariloPrecitat": "The receipt could not be read.",
  "app.citanieZlyhalo": "Reading failed.",
  "app.spojenieStranZlyhalo": "Merging the pages failed.",
  "app.bezSignaluOdosleSa": "Offline — the receipt will be sent on its own once you are connected.",
  "app.spojenieVypadlo": "The connection dropped — the receipt will be sent later on its own.",
  "app.ulozenieZlyhalo": "Saving failed.",
  "app.odfotitPrvuStranu": "Photograph the first page",
  "app.pridatDalsiuStranu": "Add another page",
  "app.zatialStran": "{pocet} pages so far",
  "app.dokladOdfotteCely": "Photograph the whole receipt",
  "app.precitaneZDokladu": "Read from the receipt",
  "app.ulozitDoklad": "Save the receipt",
  "app.neznamyPredajca": "Unknown merchant",
  "app.zDokladuZatvorka": "(read from the receipt)",
  "app.zTohoDph": "of which VAT {suma}",
  "app.bezPripojeniaKratke": "offline",
  "app.bezOdpovede": "no response",

  /* zrušenie účtu */
  "app.zrusenieNaplanovane": "The account is scheduled for closure on {termin} — in {dni}.",
  "spolocne.den1": "day",
  "spolocne.den2": "days",
  "spolocne.den5": "days",

  /* množné tvary */
  "app.cakajuceFaktury": "{pocet} are waiting on the phone to be sent. Go online and open Issued invoices — then you can sign out.",
  "spolocne.faktura1": "invoice",
  "spolocne.faktura2": "invoices",
  "spolocne.faktura5": "invoices",

  /* appka — drobnosti */
  "app.odstranitStranu": "Remove page {n}",

  /* ponuky — prázdny zoznam */
  "ponuky.ziadnePopis2": "You make a quote the same way as an invoice — and once the customer accepts it, one tap turns it into an invoice.",

  /* drobnosti — kroky a stavy */
  "nf.oprava": "Editing {cislo}",
  "nf.fakturaCislo": "Invoice {cislo}",
  "faktury.pracujem": "Working…",
  "faktury.pripravujemPdf": "Preparing the PDF…",
  "pd.odosielam": "Sending…",

  /* vystavené faktúry */
  "faktury.cakaNaOdoslanie": "Waiting to be sent: {pocet}",

  /* prijaté doklady — úhrada */
  "pd.uhradeneZUctuDna": "Paid from the account on {den}",
  "pd.uhradeneSkratka": "paid from the account on {den}",

  /* súhrny */
  "nf.zakladDph": "net {zaklad} · VAT {dph}",
  "nf.odpocitaSa": "{suma} will be deducted",

  /* šablónové texty */
  "banka.kFakture": "for invoice {cislo}",
  "banka.aktualizovane": "Updated {ked}",
  "jz.bezi": "running {trvanie}",
  "jz.ukladaSaNa": "It is saved to {auto} — change it by picking another vehicle below.",

  /* permissions for the logbook (Android) */
  "pov.nadpis": "So trips record themselves",
  "pov.uvod": "The logbook measures your route in the background — even with the screen off and the phone in your pocket. Without that the distance cannot be worked out. Location is used only to measure the trip; we never send it anywhere.",
  "pov.poloha": "Location — so the trip can be measured at all.",
  "pov.notifikacie": "Notifications — so the app can ask whether the trip was for business.",
  "pov.pohyb": "Motion sensors — so a drive is recognised sooner.",
  "pov.vzdy": "Location „Always“ — without it nothing is measured once the screen goes off.",
  "pov.povolit": "Allow",
  "pov.pytamSa": "Asking…",
  "pov.neskor": "Later",
  "app.spustam": "Starting Faktero… ({faza}) · {balicek}",
  "app.startZasekol": "Startup got stuck at step “{faza}”.",
  "app.balicek": "bundle {peciatka}",
  "app.hotovoStran": "Done — {pocet} pages",
  "app.poloziekZDokladu": "{pocet} items from the receipt",
  "nf.zFaktury": "From invoice {cislo}",
  "nf.polozkyZFaktury": "Items from invoice {cislo}",
  "nf.opravena": "Invoice {cislo} corrected",
  "nf.icoS": "Company ID {ico}",
  "nf.zuctovanaZaloha": "Deposit settled {cislo}",
  "nf.dni": "{d} days",
  "nf.zalohaCislo": "Deposit {cislo}",
  "nf.odoslaneNa": "Sent to {email}",
  "ponuky.vytvorena": "Quote {cislo} created.",
  "ponuky.vytvoritSuma": "Create quote · {suma}",
  "ponuky.nazovSuboru": "Quote {cislo}",
  "pd.odoslaneDoklady": "Receipts sent: {pocet}",
  "pd.cakaNaOdoslanie": "Waiting to be sent: {pocet}",
  "spolocne.doklad1": "receipt",
  "spolocne.doklad2": "receipts",
  "spolocne.doklad5": "receipts",
  "pd.najdenePlatby": "We found payments for receipts ({pocet})",
  "pd.polozkyPocet": "Items ({pocet})",
  "faktury.zmazana": "Invoice {cislo} deleted",
  "faktury.upomienkaOdoslana": "Reminder {n} sent",
  "faktury.poslatUpomienku": "Send reminder {n}",
  "faktury.zatialOdoslane": "Sent so far: {pocet}",
  "faktury.naozajZmazat": "Really delete invoice {cislo}?",

  /* spodná lišta */
  "tab.prehlad": "Overview",
  "tab.doklady": "Receipts",
  "tab.jazdy": "Trips",

  /* prehľad a vzhľad */
  "ph.nazov": "Overview",
  "ph.neuhradene": "Unpaid",
  "ph.poSplatnosti": "Overdue",
  "ph.rychleAkcie": "Quick actions",
  "ph.faktura": "Invoice",
  "ph.skenovat": "Scan",
  "ph.zacatJazdu": "Start a trip",
  "ph.naVybavenie": "To handle",
  "ph.poslednaAktivita": "Recent activity",
  "ph.fakturyPoSplatnosti": "{pocet} overdue",
  "ph.dokladyNaKontrolu": "{pocet} waiting to be checked",
  "ph.jazdaNeukoncena": "A trip is not finished",
  "ph.vsetkoVybavene": "Nothing is waiting",
  "ph.vsetkoVybavenePopis": "Invoices are paid and receipts are checked.",
  "ph.ziadnaAktivita": "Nothing has happened yet",
  "ph.ziadnaAktivitaPopis": "Your first invoice or receipt will appear here.",
  "ph.fakturaCislo": "Invoice {cislo}",
  "ph.doklad": "Received receipt",
  "ph.dnes": "Today",
  "ph.vcera": "Yesterday",
  "ph.vzhlad": "Appearance",
  "ph.svetly": "Light",
  "ph.tmavy": "Dark",
  "ph.podlaSystemu": "Match system",

  /* filtre faktúr */
  "faktury.filterVsetky": "All",
  "faktury.filterNeuhradene": "Unpaid",
  "faktury.filterPoSplatnosti": "Overdue",
  "faktury.filterUhradene": "Paid",
  "faktury.splatnostSkratka": "due {den}",
  "faktury.hladatKratke": "Search",
  "faktury.filtre": "Filters",

  /* skener — režimy */
  "sken.doklad": "Receipt",
  "sken.qrKod": "QR code",
  "sken.naskenujteDoklad": "Scan the receipt",
  "sken.automaticky": "The receipt is scanned automatically",
  "sken.namierteQr": "Point at the QR code",
  "sken.qrSaPrecita": "The code is read on its own, no need to press anything",
  "sken.nastavenie": "Receipt settings",

  /* banka — párovanie */
  "banka.sparovane": "Matched",
  "banka.sparovat": "Match",

  /* krokovník novej faktúry */
  "nf.krokOdberatel": "Customer",
  "nf.krokPolozky": "Items",
  "nf.krokKontrola": "Review",
  "nf.nedavniOdberatelia": "Recent customers",
  "nf.vsetciOdberatelia": "All customers",
  "nf.pokracovat": "Continue",

  "spolocne.spat": "Back",
  "spolocne.ulozit": "Save",
  "spolocne.zrusit": "Cancel",
  "spolocne.nacitavam": "Loading…",
  "spolocne.km": "km",

  /* standalone Mileage log app */
  "kj.nazov": "Mileage log",
  "kj.tabPrehlad": "Overview",
  "kj.tabHistoria": "History",
  "kj.tabVozidla": "Vehicles",
  "kj.tentoMesiac": "This month",
  "kj.sluzobne": "Business",
  "kj.sukromne": "Private",
  "kj.posledneJazdy": "Recent trips",
  "kj.vyberVozidla": "Choose a vehicle",
  "kj.vyberVozidlaPopis": "The log is kept per vehicle.",
  "kj.mojeVozidlo": "My vehicle",
  "kj.mojeVozidloPopis": "Tap to pick the car the app offers when you drive.",
  "kj.nastavitAkoMoje": "Set as mine",
  "kj.jazd1": "trip",
  "kj.jazd2": "trips",
  "kj.jazd5": "trips",
  "kj.bezJazd": "No trips this month yet",
  "kj.bezJazdPopis": "Start one with the green button below.",
};
