import type { Kluc } from "./sk";

/** English. Anything missing falls back to Slovak. */
export const en: Partial<Record<Kluc, string>> = {
  "tab.skener": "Scan",
  "tab.faktury": "Invoices",
  "tab.vytvorit": "Create",
  "tab.banka": "Bank",
  "tab.jazda": "Mileage",
  "tab.navigacia": "Main navigation",

  "panel.nastavenia": "Settings",
  "panel.firma": "Company",
  "panel.zmenitFirmu": "Switch company",
  "panel.bezFirmy": "No company",
  "panel.prehladAgend": "All sections",
  "panel.vystaveneFaktury": "Issued invoices",
  "panel.cenovePonuky": "Quotes",
  "panel.prijateDoklady": "Received documents",
  "panel.pomoc": "Help",
  "panel.nastavenieAplikacie": "App settings",
  "panel.navody": "Faktero guides",
  "panel.otvoriVPrehliadaci": "Opens in the browser",
  "panel.blocky": "Receipts and cash",
  "panel.nahlasitChybu": "Report a bug or idea",
  "panel.otvoritNaWebe": "Open Faktero on the web",
  "panel.pravne": "Legal documents",
  "panel.odhlasit": "Sign out",
  "panel.zavriet": "Close",
  "panel.jazyk": "Language",

  "domov.novaFaktura": "New invoice",
  "domov.novaFakturaPopis": "Customer, items, due date — and send it right away",
  "domov.vystaveneFaktury": "Issued invoices",
  "domov.vystaveneFakturyPopis": "Who hasn't paid, PDF and sending",
  "domov.blocek": "Receipt with a QR code",
  "domov.blocekPopis": "Loaded from the tax authority, items included",
  "domov.fakturaPdf": "Invoice as PDF",
  "domov.fakturaPdfPopis": "Pick a file from the phone or the cloud",
  "domov.viacstranovy": "Multi-page document",
  "domov.viacstranovyPopis": "Page by page, saved as one PDF",
  "domov.prijateDoklady": "Received documents",
  "domov.prijateDokladyPopis": "Receipts and invoices you have already scanned",
  "domov.pohybyNaUcte": "Account activity",
  "domov.pohybyNaUctePopis": "Whether the money arrived — balance and recent payments",
  "domov.novaJazda": "New trip",
  "domov.novaJazdaPopis": "The phone measures the distance, just start and stop",

  "jazdy.historia": "Trip history",
  "jazdy.charakter": "Trip type",
  "jazdy.sluzobna": "Business",
  "jazdy.sukromna": "Personal",
  "jazdy.oznacenaSukromna": "Marked as personal.",
  "jazdy.oznacenaSluzobna": "Marked as business.",
  "jazdy.jazda": "Trip",
  "jazdy.spolu": "Total",
  "jazdy.starsie": "Older trips",
  "jazdy.ziadne": "No trips yet",

  "ponuky.nazov": "Quotes",
  "ponuky.nova": "New quote",
  "ponuky.novaDlha": "New quote",
  "ponuky.ziadne": "No quotes yet",
  "ponuky.ziadnePopis":
    "You make a quote the same way as an invoice — and when the customer accepts it, one tap turns it into one.",
  "ponuky.vytvorit": "Create quote",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Share",
  "ponuky.odoslat": "Send",
  "ponuky.naFakturu": "To invoice",
  "ponuky.platiDo": "valid until",
  "ponuky.stav.vyfakturovana": "Invoiced",
  "ponuky.stav.zamietnuta": "Rejected",
  "ponuky.stav.prijata": "Accepted",
  "ponuky.stav.poPlatnosti": "Expired",
  "ponuky.stav.odoslana": "Sent",
  "ponuky.stav.navrh": "Draft",
  "ponuky.odberatel": "Customer",
  "ponuky.polozky": "Items",
  "ponuky.pridajPolozku": "Add item",
  "ponuky.vystavena": "Issued",
  "ponuky.poznamka": "Note",
  "ponuky.zaklad": "Subtotal",
  "ponuky.dph": "VAT",
  "ponuky.hladatOdberatela": "Search customers…",
  "ponuky.novyOdberatel": "New customer",
  "ponuky.nikNenajdeny": "Nothing found.",
  "ponuky.zmenit": "change",

  "spolocne.spat": "Back",
  "spolocne.ulozit": "Save",
  "spolocne.zrusit": "Cancel",
  "spolocne.nacitavam": "Loading…",
  "spolocne.km": "km",
};
