import type { Kluc } from "./sk";

/** Magyar. Ami itt hiányzik, szlovákul jelenik meg. */
export const hu: Partial<Record<Kluc, string>> = {
  "tab.skener": "Szkenner",
  "tab.faktury": "Számlák",
  "tab.vytvorit": "Létrehozás",
  "tab.banka": "Bank",
  "tab.jazda": "Útnyilvántartás",
  "tab.navigacia": "Fő navigáció",
  "panel.nastavenia": "Beállítások",
  "panel.firma": "Cég",
  "panel.zmenitFirmu": "Cég váltása",
  "panel.bezFirmy": "Nincs cég",
  "panel.prehladAgend": "Összes terület",
  "panel.vystaveneFaktury": "Kiállított számlák",
  "panel.cenovePonuky": "Árajánlatok",
  "panel.prijateDoklady": "Beérkezett bizonylatok",
  "panel.pomoc": "Súgó",
  "panel.nastavenieAplikacie": "Alkalmazás beállításai",
  "panel.navody": "Faktero útmutatók",
  "panel.otvoriVPrehliadaci": "Böngészőben nyílik meg",
  "panel.blocky": "Blokkok és pénztár",
  "panel.nahlasitChybu": "Hiba vagy ötlet bejelentése",
  "panel.otvoritNaWebe": "Faktero megnyitása a weben",
  "panel.pravne": "Jogi dokumentumok",
  "panel.odhlasit": "Kijelentkezés",
  "panel.zavriet": "Bezárás",
  "panel.jazyk": "Nyelv",
  "domov.novaFaktura": "Új számla",
  "domov.novaFakturaPopis": "Vevő, tételek, fizetési határidő — és rögtön küldhető",
  "domov.vystaveneFaktury": "Kiállított számlák",
  "domov.vystaveneFakturyPopis": "Ki nem fizetett még, PDF és küldés",
  "domov.blocek": "Blokk QR-kóddal",
  "domov.blocekPopis": "Az adóhatóságtól töltődik be, tételekkel együtt",
  "domov.fakturaPdf": "Számla PDF-ben",
  "domov.fakturaPdfPopis": "Válasszon fájlt a telefonról vagy a felhőből",
  "domov.viacstranovy": "Többoldalas bizonylat",
  "domov.viacstranovyPopis": "Oldalanként, egyetlen PDF-be mentve",
  "domov.prijateDoklady": "Beérkezett bizonylatok",
  "domov.prijateDokladyPopis": "Blokkok és számlák, amelyeket már beolvasott",
  "domov.pohybyNaUcte": "Számlaforgalom",
  "domov.pohybyNaUctePopis": "Megérkezett-e a pénz — egyenleg és utolsó fizetések",
  "domov.novaJazda": "Új út",
  "domov.novaJazdaPopis": "A telefon méri a távolságot, csak indítás és leállítás",
  "jazdy.historia": "Utak előzményei",
  "jazdy.charakter": "Az út jellege",
  "jazdy.sluzobna": "Hivatalos",
  "jazdy.sukromna": "Magán",
  "jazdy.oznacenaSukromna": "Magánútként megjelölve.",
  "jazdy.oznacenaSluzobna": "Hivatalos útként megjelölve.",
  "jazdy.jazda": "Út",
  "jazdy.spolu": "Összesen",
  "jazdy.starsie": "Korábbi utak",
  "jazdy.ziadne": "Még nincsenek utak",
  "ponuky.nazov": "Árajánlatok",
  "ponuky.nova": "Új ajánlat",
  "ponuky.novaDlha": "Új árajánlat",
  "ponuky.ziadne": "Még nincs árajánlat",
  "ponuky.ziadnePopis":
    "Az ajánlatot ugyanúgy készíti el, mint a számlát — és ha a vevő elfogadja, egyetlen érintéssel számla lesz belőle.",
  "ponuky.vytvorit": "Ajánlat létrehozása",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Megosztás",
  "ponuky.odoslat": "Küldés",
  "ponuky.naFakturu": "Számlává",
  "ponuky.platiDo": "érvényes eddig",
  "ponuky.stav.vyfakturovana": "Kiszámlázva",
  "ponuky.stav.zamietnuta": "Elutasítva",
  "ponuky.stav.prijata": "Elfogadva",
  "ponuky.stav.poPlatnosti": "Lejárt",
  "ponuky.stav.odoslana": "Elküldve",
  "ponuky.stav.navrh": "Piszkozat",
  "ponuky.odberatel": "Vevő",
  "ponuky.polozky": "Tételek",
  "ponuky.pridajPolozku": "Tétel hozzáadása",
  "ponuky.vystavena": "Kiállítva",
  "ponuky.poznamka": "Megjegyzés",
  "ponuky.zaklad": "Nettó",
  "ponuky.dph": "ÁFA",
  "ponuky.hladatOdberatela": "Vevő keresése…",
  "ponuky.novyOdberatel": "Új vevő",
  "ponuky.nikNenajdeny": "Nincs találat.",
  "ponuky.zmenit": "módosítás",
  "domov.skupina.fakturacia": "Számlázás",
  "domov.skupina.skenovanie": "Bizonylatok beolvasása",
  "domov.skupina.banka": "Bank",
  "domov.skupina.jazdy": "Útnyilvántartás",

  /* vystavené faktúry */
  "faktury.nazov": "Kiállított számlák",
  "faktury.hladat": "Szám vagy vevő keresése",
  "faktury.nacitavam": "Számlák betöltése…",
  "faktury.ziadne": "Még nincsenek számlák",
  "faktury.vystavPrvu": "Első számla kiállítása",
  "faktury.nicSaNenaslo": "Nincs találat",
  "faktury.bezOdberatela": "Nincs vevő",
  "faktury.stav.navrh": "Piszkozat",
  "faktury.stav.vystavena": "Kiállítva",
  "faktury.stav.odoslana": "Elküldve",
  "faktury.stav.uhradena": "Kifizetve",
  "faktury.stav.neuhradena": "Kifizetetlen",
  "faktury.stav.splatna": "Esedékes",
  "faktury.stav.poSplatnosti": "Lejárt",
  "faktury.stav.stornovana": "Sztornózva",
  "faktury.otvoritPdf": "PDF megnyitása",
  "faktury.zdielat": "Számla megosztása",
  "faktury.zdielatPopis": "Küldje el WhatsAppon, Messengeren, vagy mentse fájlba",
  "faktury.poslatEmailom": "Küldés e-mailben",
  "faktury.oznacitUhradenu": "Megjelölés kifizetettként",
  "faktury.oznacitPopis": "Ha a fizetés a banki párosításon kívül érkezett",
  "faktury.oznacenaUhradena": "Kifizetettként megjelölve",
  "faktury.upravit": "Számla szerkesztése",
  "faktury.upravitPopis": "Tételek, dátumok és megjegyzés",
  "faktury.zmazat": "Számla törlése",
  "faktury.zmazatPopis":
    "Eltűnik a listáról, de a szám foglalt marad — a számsorban nem keletkezik hézag.",
  "faktury.zmazatKratke": "Törlés",
  "faktury.ponechat": "Megtartás",
  "faktury.mazem": "Törlés…",
  "faktury.naPrezretie": "Számla megtekintése",
  "faktury.bezPripojenia": "Nincs kapcsolat — a legutóbb betöltött számlák láthatók.",
  "faktury.bezPripojeniaNacitanie": "Kapcsolat nélkül a számlák nem tölthetők be",
  "faktury.odlozenaVystavena": "A halasztott számla kiállításra került.",
  "faktury.odosluSaSamy": "Automatikusan elküldi, amint van jel. Nem kell rá gondolni.",
  "faktury.chybaNacitania": "A számlákat nem sikerült betölteni.",
  "faktury.chybaMazania": "A számlát nem sikerült törölni.",
  "faktury.chybaPdf": "A PDF-et nem sikerült elkészíteni.",
  "faktury.chybaZdielania": "A megosztás nem sikerült.",
  "faktury.chybaUpomienky": "Az emlékeztetőt nem sikerült elküldeni.",

  /* nová faktúra */
  "nf.komuFakturujete": "Kinek számláz?",
  "nf.zaCoFakturujete": "Miért számláz?",
  "nf.skontrolujte": "Ellenőrizze a számlát",
  "nf.skontrolujteZalohovu": "Ellenőrizze az előlegszámlát",
  "nf.krok": "{n}. lépés a 3-ból",
  "nf.krokZalohova": "1. lépés a 3-ból · előleg",
  "nf.faktura": "Számla",
  "nf.zalohova": "Előleg",
  "nf.odberatel": "Vevő",
  "nf.hladatOdberatela": "Vevő keresése",
  "nf.novyOdberatel": "Új vevő",
  "nf.ziadnyOdberatel": "Még nincs egyetlen vevője sem.",
  "nf.nicSaNenaslo": "Nincs találat.",
  "nf.nacitavamOdberatelov": "Vevők betöltése…",
  "nf.nazov": "Név",
  "nf.zadajteNazov": "Adja meg a vevő nevét.",
  "nf.podlaIco": "Az adószám alapján kitöltjük a nevet és a címet",
  "nf.hladamVRegistri": "Keresés a nyilvántartásban…",
  "nf.udajeDoplnene": "Az adatok a nyilvántartásból származnak",
  "nf.psc": "Irányítószám",
  "nf.email": "Erre a címre a számla azonnal elküldhető",
  "nf.odberatelPridany": "Vevő hozzáadva",
  "nf.chybaOdberatela": "A vevőt nem sikerült menteni.",
  "nf.polozky": "Tételek",
  "nf.nazovPolozky": "Tétel neve",
  "nf.mnozstvo": "Mennyiség",
  "nf.pridajtePolozku": "Adjon hozzá tételt",
  "nf.odstranitPolozku": "Tétel eltávolítása",
  "nf.zCennika": "Az árlistából",
  "nf.vlastna": "Egyéni",
  "nf.cennik": "Árlista",
  "nf.hladatPolozku": "Tétel keresése",
  "nf.zopakovatPoslednu": "Utolsó számla megismétlése",
  "nf.splatnost": "Fizetési határidő",
  "nf.splatnostSkor": "A fizetési határidő nem lehet korábbi a kiállításnál.",
  "nf.sposobUhrady": "Fizetési mód",
  "nf.hotovost": "Készpénz",
  "nf.poznamkaNad": "Megjegyzés a tételek felett",
  "nf.poznamkaPod": "Megjegyzés a tételek alatt",
  "nf.priklad": "Például: a 2026/114 sz. megrendelés szerint",
  "nf.zaklad": "Nettó",
  "nf.naUhradu": "Fizetendő",
  "nf.dalej": "Tovább",
  "nf.zrusit": "Mégse",
  "nf.zavriet": "Bezárás",
  "nf.ulozitPokracovat": "Mentés és folytatás",
  "nf.ulozitZmeny": "Módosítások mentése",
  "nf.ukladam": "Mentés…",
  "nf.ukladamZmeny": "Módosítások mentése…",
  "nf.vystavit": "Számla kiállítása",
  "nf.vystavitZalohovu": "Előlegszámla kiállítása",
  "nf.vystavujem": "Számla kiállítása…",
  "nf.vystavena": "Számla kiállítva",
  "nf.maCislo": "A számla számot kapott",
  "nf.odlozena": "A számla a telefonon várakozik",
  "nf.naPrezretie": "Számla megtekintése",
  "nf.otvoritPdf": "PDF megnyitása",
  "nf.zdielat": "Számla megosztása",
  "nf.zdielatPopis": "Küldje el WhatsAppon, Messengeren, vagy mentse fájlba",
  "nf.poslatEmailom": "Küldés e-mailben",
  "nf.odoslane": "Elküldve",
  "nf.odosielam": "Számla küldése…",
  "nf.bezEmailu":
    "A vevőnek nincs e-mail címe, így a számla nem küldhető. Adja meg a vevő adatlapján.",
  "nf.zalohy": "A vevő el nem számolt előlegei",
  "nf.hladamZalohy": "Előlegek keresése…",
  "nf.ziadnaZaloha": "Nincs elszámolható előlegszámla",
  "nf.pridatZalohovu": "Előlegszámla hozzáadása",
  "nf.bezPripojenia": "Nincs kapcsolat — a legutóbb betöltött adatokkal dolgozom.",
  "nf.bezPripojeniaVystavit":
    "Kapcsolat és mentett vevők nélkül nem állítható ki számla. Nyissa meg egyszer ezt a képernyőt internettel.",
  "nf.zalohovaBezPripojenia": "Előlegszámla kapcsolat nélkül nem állítható ki.",
  "nf.opravaBezPripojenia": "A számla javításához kapcsolat szükséges.",
  "nf.chybaPodkladov": "Az adatokat nem sikerült betölteni.",
  "nf.chybaNacitania": "A számlát nem sikerült betölteni.",
  "nf.chybaVystavenia": "A számlát nem sikerült kiállítani.",
  "nf.chybaZmien": "A módosításokat nem sikerült menteni.",
  "nf.chybaPdf": "A PDF-et nem sikerült elkészíteni.",
  "nf.chybaZdielania": "A megosztás nem sikerült.",

  /* prijaté doklady a banka */
  "pd.nazov": "Beérkezett bizonylatok",
  "pd.hladat": "Szállító vagy szám keresése",
  "pd.nacitavam": "Bizonylatok betöltése…",
  "pd.ziadne": "Még nincsenek bizonylatok",
  "pd.ziadnePopis": "A beolvasott blokkok és számlák itt jelennek meg.",
  "pd.nicSaNenaslo": "Nincs találat",
  "pd.skusteInak": "Próbáljon másképp keresni.",
  "pd.bezDodavatela": "Nincs szállító",
  "pd.neprecitany": "Beolvasatlan bizonylat",
  "pd.zFinancnejSpravy": "Az adóhatóságtól",
  "pd.sQrKodom": "· QR-kóddal",
  "pd.cisloDokladu": "Bizonylatszám",
  "pd.poznamka": "Megjegyzés",
  "pd.sposobUhrady": "Fizetési mód",
  "pd.hotovost": "Készpénz",
  "pd.kartou": "Kártyával",
  "pd.prevodom": "Átutalással",
  "pd.sposobZmeneny": "Fizetési mód módosítva",
  "pd.otvoritPdf": "PDF megnyitása",
  "pd.nacitavamPrilohu": "Melléklet betöltése…",
  "pd.presunut": "Áthelyezés a bejövő számlák közé",
  "pd.presuvam": "Áthelyezés…",
  "pd.presunuty": "A bizonylat a bejövő számlák között van.",
  "pd.zmazat": "Bizonylat törlése",
  "pd.zmazatKratke": "Törlés",
  "pd.naozajZmazat": "Biztosan törli ezt a bizonylatot?",
  "pd.nedaSaVratit": "Ez nem vonható vissza.",
  "pd.zmazany": "Bizonylat törölve",
  "pd.ponechat": "Megtartás",
  "pd.zrusit": "Mégse",
  "pd.sparovat": "Párosítás",
  "pd.anoPatriKSebe": "Igen, összetartoznak",
  "pd.uhradenyZUctu": "Számláról kifizetettként megjelölve.",
  "pd.parovanieZrusene": "A párosítás visszavonva.",
  "pd.chybaParovania": "A párosítás nem sikerült.",
  "pd.chybaZrusenia": "Nem sikerült visszavonni.",
  "pd.chybaNacitania": "A bizonylatokat nem sikerült betölteni.",
  "pd.bezPripojenia": "Kapcsolat nélkül a bizonylatok nem tölthetők be",
  "pd.odlozeneOdoslu":
    "A halasztott blokkok automatikusan elküldik magukat, amint visszatér a jel.",
  "pd.bezSignalu": "Egyelőre nincs jel — magamtól újra próbálom.",
  "pd.zahodit": "Halasztott bizonylat elvetése",
  "pd.odoslat": "Küldés",
  "banka.ucet": "Számla",
  "banka.vsetky": "Összes",
  "banka.nacitavam": "Tranzakciók betöltése…",
  "banka.ziadnePohyby": "Még nincsenek tranzakciók",
  "banka.stiahnut": "Letöltés a bankból",
  "banka.stahujem": "Letöltés a bankból…",
  "banka.ziadneNove": "Nincsenek új tranzakciók.",
  "banka.prijataPlatba": "Bejövő fizetés",
  "banka.odchadzajucaPlatba": "Kimenő fizetés",
  "banka.dnes": "Ma",
  "banka.vcera": "Tegnap",
  "banka.nesynchronizovane": "még nincs szinkronizálva",
  "banka.bezUctu": "A cégnek nincs csatlakoztatott bankszámlája",
  "banka.pripojenieNaWebe":
    "A számlát a weben lehet csatlakoztatni — a bank bejelentkezést és hozzájárulást kér, ami telefonon nehezen intézhető.",
  "banka.bezPripojenia": "Kapcsolat nélkül a számlák nem tölthetők be",
  "banka.lenSoSignalom":
    "Az egyenlegek és tranzakciók csak jellel tekinthetők meg — a telefonon semmi nem tárolódik.",
  "banka.neodpovedala": "A bank most nem válaszolt. Próbálja meg kicsit később.",
  "banka.chybaNacitania": "A tranzakciókat nem sikerült betölteni.",

  "spolocne.spat": "Vissza",
  "spolocne.ulozit": "Mentés",
  "spolocne.zrusit": "Mégse",
  "spolocne.nacitavam": "Betöltés…",
  "spolocne.km": "km",
};
