import type { Kluc } from "./sk";

/** Magyar. Ami itt hiányzik, szlovákul jelenik meg. */
export const hu: Partial<Record<Kluc, string>> = {
  "tab.skener": "Szkenner",
  "tab.faktury": "Számlák",
  "tab.vytvorit": "Létrehozás",
  "tab.banka": "Bank",
  "tab.jazda": "Útnyilvántartás",
  "tab.navigacia": "Fő navigáció",
  "panel.nastavenia": "Beállítások",
  "panel.firma": "Cég",
  "panel.zmenitFirmu": "Cég váltása",
  "panel.bezFirmy": "Nincs cég",
  "panel.prehladAgend": "Összes terület",
  "panel.vystaveneFaktury": "Kiállított számlák",
  "panel.cenovePonuky": "Árajánlatok",
  "panel.prijateDoklady": "Beérkezett bizonylatok",
  "panel.pomoc": "Súgó",
  "panel.nastavenieAplikacie": "Alkalmazás beállításai",
  "panel.navody": "Faktero útmutatók",
  "panel.otvoriVPrehliadaci": "Böngészőben nyílik meg",
  "panel.blocky": "Blokkok és pénztár",
  "panel.nahlasitChybu": "Hiba vagy ötlet bejelentése",
  "panel.otvoritNaWebe": "Faktero megnyitása a weben",
  "panel.pravne": "Jogi dokumentumok",
  "panel.odhlasit": "Kijelentkezés",
  "panel.zavriet": "Bezárás",
  "panel.jazyk": "Nyelv",
  "domov.novaFaktura": "Új számla",
  "domov.novaFakturaPopis": "Vevő, tételek, fizetési határidő — és rögtön küldhető",
  "domov.vystaveneFaktury": "Kiállított számlák",
  "domov.vystaveneFakturyPopis": "Ki nem fizetett még, PDF és küldés",
  "domov.blocek": "Blokk QR-kóddal",
  "domov.blocekPopis": "Az adóhatóságtól töltődik be, tételekkel együtt",
  "domov.fakturaPdf": "Számla PDF-ben",
  "domov.fakturaPdfPopis": "Válasszon fájlt a telefonról vagy a felhőből",
  "domov.viacstranovy": "Többoldalas bizonylat",
  "domov.viacstranovyPopis": "Oldalanként, egyetlen PDF-be mentve",
  "domov.prijateDoklady": "Beérkezett bizonylatok",
  "domov.prijateDokladyPopis": "Blokkok és számlák, amelyeket már beolvasott",
  "domov.pohybyNaUcte": "Számlaforgalom",
  "domov.pohybyNaUctePopis": "Megérkezett-e a pénz — egyenleg és utolsó fizetések",
  "domov.novaJazda": "Új út",
  "domov.novaJazdaPopis": "A telefon méri a távolságot, csak indítás és leállítás",
  "jazdy.historia": "Utak előzményei",
  "jazdy.charakter": "Az út jellege",
  "jazdy.sluzobna": "Hivatalos",
  "jazdy.sukromna": "Magán",
  "jazdy.oznacenaSukromna": "Magánútként megjelölve.",
  "jazdy.oznacenaSluzobna": "Hivatalos útként megjelölve.",
  "jazdy.jazda": "Út",
  "jazdy.spolu": "Összesen",
  "jazdy.starsie": "Korábbi utak",
  "jazdy.ziadne": "Még nincsenek utak",
  "ponuky.nazov": "Árajánlatok",
  "ponuky.nova": "Új ajánlat",
  "ponuky.novaDlha": "Új árajánlat",
  "ponuky.ziadne": "Még nincs árajánlat",
  "ponuky.ziadnePopis":
    "Az ajánlatot ugyanúgy készíti el, mint a számlát — és ha a vevő elfogadja, egyetlen érintéssel számla lesz belőle.",
  "ponuky.vytvorit": "Ajánlat létrehozása",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Megosztás",
  "ponuky.odoslat": "Küldés",
  "ponuky.naFakturu": "Számlává",
  "ponuky.platiDo": "érvényes eddig",
  "ponuky.stav.vyfakturovana": "Kiszámlázva",
  "ponuky.stav.zamietnuta": "Elutasítva",
  "ponuky.stav.prijata": "Elfogadva",
  "ponuky.stav.poPlatnosti": "Lejárt",
  "ponuky.stav.odoslana": "Elküldve",
  "ponuky.stav.navrh": "Piszkozat",
  "ponuky.odberatel": "Vevő",
  "ponuky.polozky": "Tételek",
  "ponuky.pridajPolozku": "Tétel hozzáadása",
  "ponuky.vystavena": "Kiállítva",
  "ponuky.poznamka": "Megjegyzés",
  "ponuky.zaklad": "Nettó",
  "ponuky.dph": "ÁFA",
  "ponuky.hladatOdberatela": "Vevő keresése…",
  "ponuky.novyOdberatel": "Új vevő",
  "ponuky.nikNenajdeny": "Nincs találat.",
  "ponuky.zmenit": "módosítás",
  "domov.skupina.fakturacia": "Számlázás",
  "domov.skupina.skenovanie": "Bizonylatok beolvasása",
  "domov.skupina.banka": "Bank",
  "domov.skupina.jazdy": "Útnyilvántartás",

  /* vystavené faktúry */
  "faktury.nazov": "Kiállított számlák",
  "faktury.hladat": "Szám vagy vevő keresése",
  "faktury.nacitavam": "Számlák betöltése…",
  "faktury.ziadne": "Még nincsenek számlák",
  "faktury.vystavPrvu": "Első számla kiállítása",
  "faktury.nicSaNenaslo": "Nincs találat",
  "faktury.bezOdberatela": "Nincs vevő",
  "faktury.stav.navrh": "Piszkozat",
  "faktury.stav.vystavena": "Kiállítva",
  "faktury.stav.odoslana": "Elküldve",
  "faktury.stav.uhradena": "Kifizetve",
  "faktury.stav.neuhradena": "Kifizetetlen",
  "faktury.stav.splatna": "Esedékes",
  "faktury.stav.poSplatnosti": "Lejárt",
  "faktury.stav.stornovana": "Sztornózva",
  "faktury.otvoritPdf": "PDF megnyitása",
  "faktury.zdielat": "Számla megosztása",
  "faktury.zdielatPopis": "Küldje el WhatsAppon, Messengeren, vagy mentse fájlba",
  "faktury.poslatEmailom": "Küldés e-mailben",
  "faktury.oznacitUhradenu": "Megjelölés kifizetettként",
  "faktury.oznacitPopis": "Ha a fizetés a banki párosításon kívül érkezett",
  "faktury.oznacenaUhradena": "Kifizetettként megjelölve",
  "faktury.upravit": "Számla szerkesztése",
  "faktury.upravitPopis": "Tételek, dátumok és megjegyzés",
  "faktury.zmazat": "Számla törlése",
  "faktury.zmazatPopis":
    "Eltűnik a listáról, de a szám foglalt marad — a számsorban nem keletkezik hézag.",
  "faktury.zmazatKratke": "Törlés",
  "faktury.ponechat": "Megtartás",
  "faktury.mazem": "Törlés…",
  "faktury.naPrezretie": "Számla megtekintése",
  "faktury.bezPripojenia": "Nincs kapcsolat — a legutóbb betöltött számlák láthatók.",
  "faktury.bezPripojeniaNacitanie": "Kapcsolat nélkül a számlák nem tölthetők be",
  "faktury.odlozenaVystavena": "A halasztott számla kiállításra került.",
  "faktury.odosluSaSamy": "Automatikusan elküldi, amint van jel. Nem kell rá gondolni.",
  "faktury.chybaNacitania": "A számlákat nem sikerült betölteni.",
  "faktury.chybaMazania": "A számlát nem sikerült törölni.",
  "faktury.chybaPdf": "A PDF-et nem sikerült elkészíteni.",
  "faktury.chybaZdielania": "A megosztás nem sikerült.",
  "faktury.chybaUpomienky": "Az emlékeztetőt nem sikerült elküldeni.",

  /* nová faktúra */
  "nf.komuFakturujete": "Kinek számláz?",
  "nf.zaCoFakturujete": "Miért számláz?",
  "nf.skontrolujte": "Ellenőrizze a számlát",
  "nf.skontrolujteZalohovu": "Ellenőrizze az előlegszámlát",
  "nf.krok": "{n}. lépés a 3-ból",
  "nf.krokZalohova": "1. lépés a 3-ból · előleg",
  "nf.faktura": "Számla",
  "nf.zalohova": "Előleg",
  "nf.odberatel": "Vevő",
  "nf.hladatOdberatela": "Vevő keresése",
  "nf.novyOdberatel": "Új vevő",
  "nf.ziadnyOdberatel": "Még nincs egyetlen vevője sem.",
  "nf.nicSaNenaslo": "Nincs találat.",
  "nf.nacitavamOdberatelov": "Vevők betöltése…",
  "nf.nazov": "Név",
  "nf.zadajteNazov": "Adja meg a vevő nevét.",
  "nf.podlaIco": "Az adószám alapján kitöltjük a nevet és a címet",
  "nf.hladamVRegistri": "Keresés a nyilvántartásban…",
  "nf.udajeDoplnene": "Az adatok a nyilvántartásból származnak",
  "nf.psc": "Irányítószám",
  "nf.email": "Erre a címre a számla azonnal elküldhető",
  "nf.odberatelPridany": "Vevő hozzáadva",
  "nf.chybaOdberatela": "A vevőt nem sikerült menteni.",
  "nf.polozky": "Tételek",
  "nf.nazovPolozky": "Tétel neve",
  "nf.mnozstvo": "Mennyiség",
  "nf.pridajtePolozku": "Adjon hozzá tételt",
  "nf.odstranitPolozku": "Tétel eltávolítása",
  "nf.zCennika": "Az árlistából",
  "nf.vlastna": "Egyéni",
  "nf.cennik": "Árlista",
  "nf.hladatPolozku": "Tétel keresése",
  "nf.zopakovatPoslednu": "Utolsó számla megismétlése",
  "nf.splatnost": "Fizetési határidő",
  "nf.splatnostSkor": "A fizetési határidő nem lehet korábbi a kiállításnál.",
  "nf.sposobUhrady": "Fizetési mód",
  "nf.hotovost": "Készpénz",
  "nf.poznamkaNad": "Megjegyzés a tételek felett",
  "nf.poznamkaPod": "Megjegyzés a tételek alatt",
  "nf.priklad": "Például: a 2026/114 sz. megrendelés szerint",
  "nf.zaklad": "Nettó",
  "nf.naUhradu": "Fizetendő",
  "nf.dalej": "Tovább",
  "nf.zrusit": "Mégse",
  "nf.zavriet": "Bezárás",
  "nf.ulozitPokracovat": "Mentés és folytatás",
  "nf.ulozitZmeny": "Módosítások mentése",
  "nf.ukladam": "Mentés…",
  "nf.ukladamZmeny": "Módosítások mentése…",
  "nf.vystavit": "Számla kiállítása",
  "nf.vystavitZalohovu": "Előlegszámla kiállítása",
  "nf.vystavujem": "Számla kiállítása…",
  "nf.vystavena": "Számla kiállítva",
  "nf.maCislo": "A számla számot kapott",
  "nf.odlozena": "A számla a telefonon várakozik",
  "nf.naPrezretie": "Számla megtekintése",
  "nf.otvoritPdf": "PDF megnyitása",
  "nf.zdielat": "Számla megosztása",
  "nf.zdielatPopis": "Küldje el WhatsAppon, Messengeren, vagy mentse fájlba",
  "nf.poslatEmailom": "Küldés e-mailben",
  "nf.odoslane": "Elküldve",
  "nf.odosielam": "Számla küldése…",
  "nf.bezEmailu":
    "A vevőnek nincs e-mail címe, így a számla nem küldhető. Adja meg a vevő adatlapján.",
  "nf.zalohy": "A vevő el nem számolt előlegei",
  "nf.hladamZalohy": "Előlegek keresése…",
  "nf.ziadnaZaloha": "Nincs elszámolható előlegszámla",
  "nf.pridatZalohovu": "Előlegszámla hozzáadása",
  "nf.bezPripojenia": "Nincs kapcsolat — a legutóbb betöltött adatokkal dolgozom.",
  "nf.bezPripojeniaVystavit":
    "Kapcsolat és mentett vevők nélkül nem állítható ki számla. Nyissa meg egyszer ezt a képernyőt internettel.",
  "nf.zalohovaBezPripojenia": "Előlegszámla kapcsolat nélkül nem állítható ki.",
  "nf.opravaBezPripojenia": "A számla javításához kapcsolat szükséges.",
  "nf.chybaPodkladov": "Az adatokat nem sikerült betölteni.",
  "nf.chybaNacitania": "A számlát nem sikerült betölteni.",
  "nf.chybaVystavenia": "A számlát nem sikerült kiállítani.",
  "nf.chybaZmien": "A módosításokat nem sikerült menteni.",
  "nf.chybaPdf": "A PDF-et nem sikerült elkészíteni.",
  "nf.chybaZdielania": "A megosztás nem sikerült.",

  /* prijaté doklady a banka */
  "pd.nazov": "Beérkezett bizonylatok",
  "pd.hladat": "Szállító vagy szám keresése",
  "pd.nacitavam": "Bizonylatok betöltése…",
  "pd.ziadne": "Még nincsenek bizonylatok",
  "pd.ziadnePopis": "A beolvasott blokkok és számlák itt jelennek meg.",
  "pd.nicSaNenaslo": "Nincs találat",
  "pd.skusteInak": "Próbáljon másképp keresni.",
  "pd.bezDodavatela": "Nincs szállító",
  "pd.neprecitany": "Beolvasatlan bizonylat",
  "pd.zFinancnejSpravy": "Az adóhatóságtól",
  "pd.sQrKodom": "· QR-kóddal",
  "pd.cisloDokladu": "Bizonylatszám",
  "pd.poznamka": "Megjegyzés",
  "pd.sposobUhrady": "Fizetési mód",
  "pd.hotovost": "Készpénz",
  "pd.kartou": "Kártyával",
  "pd.prevodom": "Átutalással",
  "pd.sposobZmeneny": "Fizetési mód módosítva",
  "pd.otvoritPdf": "PDF megnyitása",
  "pd.nacitavamPrilohu": "Melléklet betöltése…",
  "pd.presunut": "Áthelyezés a bejövő számlák közé",
  "pd.presuvam": "Áthelyezés…",
  "pd.presunuty": "A bizonylat a bejövő számlák között van.",
  "pd.zmazat": "Bizonylat törlése",
  "pd.zmazatKratke": "Törlés",
  "pd.naozajZmazat": "Biztosan törli ezt a bizonylatot?",
  "pd.nedaSaVratit": "Ez nem vonható vissza.",
  "pd.zmazany": "Bizonylat törölve",
  "pd.ponechat": "Megtartás",
  "pd.zrusit": "Mégse",
  "pd.sparovat": "Párosítás",
  "pd.anoPatriKSebe": "Igen, összetartoznak",
  "pd.uhradenyZUctu": "Számláról kifizetettként megjelölve.",
  "pd.parovanieZrusene": "A párosítás visszavonva.",
  "pd.chybaParovania": "A párosítás nem sikerült.",
  "pd.chybaZrusenia": "Nem sikerült visszavonni.",
  "pd.chybaNacitania": "A bizonylatokat nem sikerült betölteni.",
  "pd.bezPripojenia": "Kapcsolat nélkül a bizonylatok nem tölthetők be",
  "pd.odlozeneOdoslu":
    "A halasztott blokkok automatikusan elküldik magukat, amint visszatér a jel.",
  "pd.bezSignalu": "Egyelőre nincs jel — magamtól újra próbálom.",
  "pd.zahodit": "Halasztott bizonylat elvetése",
  "pd.odoslat": "Küldés",
  "banka.ucet": "Számla",
  "banka.vsetky": "Összes",
  "banka.nacitavam": "Tranzakciók betöltése…",
  "banka.ziadnePohyby": "Még nincsenek tranzakciók",
  "banka.stiahnut": "Letöltés a bankból",
  "banka.stahujem": "Letöltés a bankból…",
  "banka.ziadneNove": "Nincsenek új tranzakciók.",
  "banka.prijataPlatba": "Bejövő fizetés",
  "banka.odchadzajucaPlatba": "Kimenő fizetés",
  "banka.dnes": "Ma",
  "banka.vcera": "Tegnap",
  "banka.nesynchronizovane": "még nincs szinkronizálva",
  "banka.bezUctu": "A cégnek nincs csatlakoztatott bankszámlája",
  "banka.pripojenieNaWebe":
    "A számlát a weben lehet csatlakoztatni — a bank bejelentkezést és hozzájárulást kér, ami telefonon nehezen intézhető.",
  "banka.bezPripojenia": "Kapcsolat nélkül a számlák nem tölthetők be",
  "banka.lenSoSignalom":
    "Az egyenlegek és tranzakciók csak jellel tekinthetők meg — a telefonon semmi nem tárolódik.",
  "banka.neodpovedala": "A bank most nem válaszolt. Próbálja meg kicsit később.",
  "banka.chybaNacitania": "A tranzakciókat nem sikerült betölteni.",

  /* kniha jázd */
  "jz.novaJazda": "Új út",
  "jz.zacatJazdu": "Út indítása",
  "jz.jazdaBezi": "Út folyamatban",
  "jz.jazdaPozastavena": "Út szüneteltetve",
  "jz.meranieNebezi": "a mérés még nem fut",
  "jz.pozastavene": "szüneteltetve — a mozgás nem számít bele",
  "jz.pozastavitMeranie": "Mérés szüneteltetése",
  "jz.pokracovatVMerani": "Mérés folytatása",
  "jz.tuknutimPozastavite": "Érintse meg a kört a szüneteltetéshez",
  "jz.tuknutimPokracujete": "Érintse meg a kört a folytatáshoz",
  "jz.ukoncitAUlozit": "Út befejezése és mentése",
  "jz.ukladamJazdu": "Út mentése…",
  "jz.ucelCesty": "Az út célja",
  "jz.ucelPriklad": "pl. szerviz a vevőnél",
  "jz.ulozeneSluzobna": "Hivatalosként mentve",
  "jz.ulozeneSukromna": "Magánútként mentve",
  "jz.bezSignaluOdoslana": "A kapcsolat nélkül rögzített út elküldve",
  "jz.chybaUlozenia": "Az utat nem sikerült menteni.",
  "jz.chybaGps": "A GPS-t nem sikerült elindítani.",
  "jz.chybaPokracovania": "A mérést nem sikerült folytatni.",
  "jz.rozpoznanaBezi": "Felismert út van folyamatban",
  "jz.ukoncitJazdu": "Út befejezése",
  "jz.ukoncujem": "Befejezés…",
  "jz.zahodit": "Elvetés",
  "jz.zahoditOtazka": "Elveti ezt az utat? Nem kerül rögzítésre.",
  "jz.ukoncena": "Az út befejezve — sorolja be alább.",
  "jz.zahodena": "Út elvetve.",
  "jz.vozidloPreJazdu": "Jármű a felismert úthoz",
  "jz.telefonNevie": "A telefon nem tudja, melyik autóba ült be — ellenőrizze minden útnál.",
  "jz.rozpoznavat": "Utak automatikus felismerése",
  "jz.detekciaZapnuta": "Az útfelismerés be van kapcsolva",
  "jz.detekciaNemaAkoBezat": "A felismerés be van kapcsolva, de nem tud futni",
  "jz.vyzadujePolohu": "„Mindig“ helyhozzáférés szükséges.",
  "jz.akoFunguje": "Hogyan működik a felismerés",
  "jz.ukazatTrasu": "Útvonal megjelenítése",
  "jz.skrytTrasu": "Útvonal elrejtése",
  "jz.historia": "előzmények",
  "jz.noveVozidlo": "Új jármű",
  "jz.pridatVozidlo": "Jármű hozzáadása",
  "jz.vozidloPridane": "Jármű hozzáadva",
  "jz.chybaVozidla": "A járművet nem sikerült hozzáadni.",
  "jz.zadajteNazovVozidla": "Adja meg a jármű nevét.",
  "jz.evidencneCislo": "Rendszám",
  "jz.nazovVozidlaPriklad": "pl. Škoda Octavia",
  "jz.ukladamVozidlo": "Jármű mentése…",
  "jz.nacitavamVozidla": "Járművek betöltése…",
  "jz.bezVozidla": "A cégnek nincs járműve",
  "jz.pridajteHo": "Adja hozzá itt — elég a név és a rendszám, a többi a weben pótolható.",
  "jz.commander": "Ennek az autónak az útjait a Commander hozza",
  "jz.bezPripojenia": "Kapcsolat nélkül a járművek nem tölthetők be",
  "jz.bezZoznamu": "A telefonon még nincs mentett lista. Nyissa meg egyszer ezt a képernyőt internettel.",
  "jz.nepovinneCena": "Nem kötelező, de nélküle az út költsége nulla lesz.",

  /* skener, notifikácie, čísla dopredu */
  "jz.nahravamJazdu": "Út rögzítése folyamatban",
  "jz.spustenaRucne": "kézzel indítva",
  "jz.otvoritPrebiehajucu": "Folyamatban lévő út megnyitása",
  "qr.namierte": "Irányítsa a QR-kódra",
  "qr.zrusitSkenovanie": "Beolvasás megszakítása",
  "qr.kameraNejde": "A kamerát nem sikerült elindítani. Próbálja lefényképezni a bizonylatot.",
  "qr.kameraZamietnuta": "A kamerához való hozzáférés le van tiltva. Engedélyezze a telefon beállításaiban.",
  "push.nazov": "Értesítések",
  "push.zistujem": "Ellenőrzés…",
  "push.zaregistrovane": "Az eszköz regisztrálva van, az értesítések meg fognak érkezni.",
  "push.neznameZariadenie": "A kiszolgáló még nem ismeri ezt az eszközt.",
  "push.povolenieVTelefone": "Engedély a telefonon:",
  "push.lenVApke": "csak a mobilalkalmazásban",
  "push.pluginNedostupny": "a bővítmény nem érhető el",
  "push.registraciaZlyhala": "a regisztráció nem sikerült",
  "push.zaregistrovatZnova": "Regisztrálás újra",
  "push.skusitZaregistrovat": "Regisztráció megkísérlése",
  "spolocne.chyba": "Hiba",
  "cisla.nazov": "Számla kiállítása jel nélkül, számmal együtt",
  "cisla.vypnutePopis": "E nélkül a jel nélkül kiállított számla várakozik, és a kapcsolat helyreálltakor állítja ki magát — a számot csak akkor kapja meg.",
  "cisla.zapnutePopis": "Előkészített számok: {pocet}. A jel nélkül kiállított számla azonnal számot kap, így a helyszínen átadható.",
  "cisla.zapnut": "Bekapcsolás",
  "cisla.vypnut": "Kikapcsolás",
  "cisla.vypnute": "Kikapcsolva. A fel nem használt számok visszakerültek a sorba.",
  "cisla.zapnute": "Bekapcsolva. Az alkalmazásnak {pocet} száma áll készen.",
  "cisla.trebaPripojenie": "A bekapcsoláshoz kapcsolat kell — az alkalmazás a kiszolgálótól kéri a számokat.",
  "cisla.nepodariloVypytat": "A számokat nem sikerült lekérni. Próbálja meg kicsit később.",
  "cisla.nepodariloPrepnut": "Nem sikerült átkapcsolni.",

  /* skener, firma, registrácia */
  "sken.naskenujte": "Olvassa be a blokk QR-kódját",
  "sken.aleboOdfotte": "vagy fényképezze le a bizonylatot",
  "sken.kameraNejde": "A bizonylatot így is lefényképezheti vagy kiválaszthatja a fájlok közül — az alábbi gombok működnek.",
  "sken.odfotit": "Fényképezés",
  "sken.zGalerie": "Galériából",
  "sken.uhrada": "Fizetés",
  "sken.karta": "Kártya",
  "sken.kategoria": "Költségkategória",
  "sken.nezaradene": "Besorolatlan",
  "sken.pdfSubor": "PDF-fájl",
  "sken.viacstranovy": "Többoldalas",
  "vf.vytvorteSiFirmu": "Hozza létre a cégét",
  "vf.pridatFirmu": "Cég hozzáadása",
  "vf.podnadpis": "Ezek az adatok jelennek meg a számlákon",
  "vf.vytvaram": "Létrehozás…",
  "vf.vytvoritFirmu": "Cég létrehozása",
  "vf.uvod": "A név elég — a többit később bármikor kiegészítheti a beállításokban. Ha megadja a cégjegyzékszámot, a címet és az adószámokat a nyilvántartásból töltjük be.",
  "vf.nazovFirmy": "Cégnév",
  "vf.ico": "Cégjegyzékszám",
  "vf.dic": "Adószám",
  "vf.icDph": "Közösségi adószám",
  "vf.ulica": "Utca és házszám",
  "vf.mesto": "Város",
  "vf.psc": "Irányítószám",
  "vf.iban": "IBAN",
  "vf.ibanHint": "Az ügyfél erre fizet — később is megadhatja.",
  "vf.email": "E-mail",
  "vf.telefon": "Telefon",
  "vf.hladamVRegistri": "Keresés a nyilvántartásban…",
  "vf.trebaPripojenie": "A cég létrehozásához kapcsolat szükséges. Próbálja újra, ha van térerő.",
  "vf.nepodariloVytvorit": "A céget nem sikerült létrehozni.",
  "vf.vytvorena": "A cég létrejött.",
  "vf.chyba.nazov": "Adja meg a cég nevét.",
  "vf.chyba.ico": "A cégjegyzékszám 6–8 számjegyű.",
  "vf.chyba.email": "Adjon meg érvényes céges e-mailt.",
  "vf.chyba.iban": "Az IBAN formátuma nem megfelelő.",
  "reg.potvrdteEmail": "Erősítse meg az e-mailjét",
  "reg.potvrdenieText": "A(z) {email} fiók létrejött. Küldtünk rá egy hivatkozást — nyissa meg, és térjen ide vissza. Az alkalmazás magától észreveszi a megerősítést; ha mégsem, használja az alábbi gombot. Megerősítés nélkül nem lehet bejelentkezni.",
  "reg.spamPriecinok": "Ha az e-mail pár percen belül nem érkezik meg, nézze meg a levélszemét mappát.",
  "reg.overujem": "Ellenőrzés…",
  "reg.uzSomPotvrdil": "Megerősítettem, tovább",
  "reg.posielam": "Küldés…",
  "reg.poslatZnova": "E-mail újraküldése",
  "reg.spatNaPrihlasenie": "Vissza a bejelentkezéshez",
  "reg.vytvorteSiUcet": "Hozzon létre fiókot",
  "reg.zadarmo": "30 nap ingyen a Premium csomagban. Bankkártya nélkül.",
  "reg.meno": "Teljes név",
  "reg.email": "E-mail",
  "reg.heslo": "Jelszó (legalább 8 karakter)",
  "reg.suhlasPodmienky": "Elfogadom a következőt: {odkaz}.",
  "reg.obchodnePodmienky": "Általános Szerződési Feltételek",
  "reg.suhlasGdpr": "Tudomásul veszem a következőt: {odkaz}.",
  "reg.spracuvanieUdajov": "Személyes adatok kezelése",
  "reg.vytvaram": "Létrehozás…",
  "reg.vytvoritUcet": "Fiók létrehozása",
  "reg.uzMamUcet": "Van már fiókom, bejelentkezés",
  "reg.ucetJeVytvoreny": "A fiók létrejött.",
  "reg.registraciaZlyhala": "A regisztráció nem sikerült.",
  "reg.nepotvrdene": "Még nincs megerősítve. Nyissa meg az e-mailben kapott hivatkozást, és próbálja újra.",
  "reg.emailPoslanyZnova": "Újraküldtük az e-mailt.",
  "reg.chyba.meno": "Adja meg a teljes nevét.",
  "reg.chyba.email": "Adjon meg érvényes e-mailt.",
  "reg.chyba.heslo": "A jelszónak legalább 8 karakterből kell állnia.",
  "reg.chyba.suhlasy": "Erősítse meg mindkét hozzájárulást.",

  /* cenové ponuky */
  "ponuky.bezEmailu": "Az ügyfélnek nincs e-mail-címe. Adja meg az adatlapján.",
  "ponuky.odoslatOtazka": "Elküldi a(z) {cislo} árajánlatot ide: {email}?",
  "ponuky.odoslana": "Az árajánlatot elküldtük.",
  "ponuky.uzFakturovana": "Ebből az árajánlatból már készült számla.",
  "ponuky.naFakturuOtazka": "Készít számlát a(z) {cislo} árajánlatból?",
  "ponuky.fakturaVytvorena": "A számla elkészült.",
  "ponuky.platiDoSkratka": "érvényes eddig: {den}",
  "ponuky.vyberteOdberatela": "Válasszon ügyfelet.",
  "ponuky.doplntePolozku": "Adjon hozzá legalább egy tételt.",
  "ponuky.platnostPredVystavenim": "Az érvényesség nem lehet a kiállítás előtt.",
  "ponuky.nepodariloVytvorit": "Az árajánlatot nem sikerült létrehozni.",
  "ponuky.vytvaram": "Árajánlat létrehozása…",

  /* kniha jázd — zvyšok */
  "jz.odCasu": "{cas} óta. Ha megérkezett, zárja le — különben csak öt perc állás után áll le magától.",
  "jz.rozpoznalaJazdu": "Az alkalmazás felismert egy utat",
  "jz.rozpoznalaJazdy": "Az alkalmazás utakat ismert fel ({pocet})",
  "jz.commanderZvysok": ", így a telefonnak nem kell mérnie — válasszon másik autót, vagy hagyja kikapcsolva a felismerést.",
  "jz.typJazdy": "Út típusa",
  "jz.vozidlo": "Jármű",
  "jz.nazovVozidla": "Név",
  "jz.spotreba": "Fogyasztás (l/100 km)",
  "jz.spotrebaPriklad": "pl. 6,5",
  "jz.vsimneSi": "Az alkalmazás magától észreveszi az utat, és értesítésben kérdezi meg, hogy üzleti volt-e.",
  "jz.lenPocasPouzivania": "Ha a helymeghatározást csak „az alkalmazás használata közben” engedélyezte, hagyja nyitva az alkalmazást — a képernyő kikapcsolása után a telefon leállítja a mérést, és a kilométerek hibásak lennének. Az „Mindig” beállítással a zsebben is mér.",
  "jz.vyberteVozidlo": "Válasszon járművet.",
  "jz.odoslanychJazd": "{pocet} jel nélkül rögzített utat elküldtünk",
  "jz.rozpoznanaUlozena": "Felismert út mentve — {km} km, {auto}",
  "jz.bezPolohy": "Nem mértünk helyzetet, ezért az utat nem mentettük. Próbálja szabadban — épületben a helymeghatározás pontatlan —, és állítsa a hozzáférést „Mindig” értékre.",
  "jz.ulozenaVTelefone": "Az utat a telefonon mentettük — {km} km. Kapcsolat esetén elküldjük.",
  "jz.ulozenaKm": "Út mentve — {km} km",
  "jz.historiaVozidla": "Útnyilvántartás — {auto}",

  /* bočný panel */
  "panel.nadpis": "Beállítások panel",
  "panel.prihlasenyAko": "Bejelentkezve mint",
  "panel.vsetkoNaJednej": "Minden, amit az alkalmazás tud, egy képernyőn",
  "panel.ucetPamat": "Fiók és megszüntetése, tárhely, kapcsolat, verzió",
  "panel.ekasaPopis": "Hogyan olvassuk be az eKasa bizonylatokat",
  "panel.napisteNam": "Írja meg, mi nem működik, vagy mi segítene",
  "panel.zvysokAplikacie": "Számlák, készlet és az alkalmazás többi része",
  "panel.pravnePopis": "Feltételek, adatvédelem és a többi — a böngészőben nyílik meg",
  "panel.biometria": "Biometrikus bejelentkezés",
  "panel.biometriaZapnuta": "Az alkalmazás indításakor kérdez",
  "panel.biometriaVypnuta": "Kikapcsolva",
  "panel.biometriaNedostupna": "A biometria ezen az eszközön nem érhető el.",
  "panel.rychleZapnute": "Gyors bejelentkezés bekapcsolva",
  "panel.rychleVypnute": "Gyors bejelentkezés kikapcsolva",
  "panel.nepodariloZapnut": "Nem sikerült bekapcsolni",

  /* doklady, faktúry, jazdy, banka — zvyšok */
  "pd.doklad": "Bizonylat",
  "pd.ico": "Cégjegyzékszám",
  "pd.icDph": "Közösségi adószám",
  "faktury.vystavenychPocet": "Kiállított számlák: {pocet}.",
  "faktury.neuhradene": "Kifizetetlen",
  "faktury.odosluSaSamy2": "Maguktól elküldődnek, amint van térerő. Nem kell rá gondolnia.",
  "faktury.bezZoznamu": "A telefonon még nincs mentett lista. Nyissa meg egyszer ezt a képernyőt internettel, utána offline is működik.",
  "faktury.vystavena": "Kiállítva",
  "faktury.splatna": "Esedékes",
  "faktury.uhradena": "Kifizetve",
  "faktury.odoslana": "Elküldve",
  "faktury.cisloOstava": "Eltűnik a listáról, de a szám foglalt marad — a számsorban nem keletkezik lyuk.",
  "jazdy.nacitavam": "Utak betöltése…",
  "jazdy.prvaPribudne": "Az első a mérés befejezése után jelenik meg — vagy a GPS-egységből töltődik be, ha a jármű csatlakoztatva van.",
  "jazdy.spoluCelaHistoria": "Összesen a teljes előzményre",
  "jazdy.spoluPoslednych": "Összesen az utolsó {pocet} útra",
  "jazdy.nacitatStarsie": "Régebbi utak betöltése",
  "jazdy.chybaStarsich": "A régebbi utakat nem sikerült betölteni.",
  "banka.nazov": "Bank",
  "banka.vsetkyUcty": "Összes",
  "banka.ucetSkratka": "számla",

  /* banka — prepínač účtov */
  "banka.ucetVelke": "Számla",
  "banka.zostatokSpolu": "Teljes egyenleg",

  /* nová faktúra — zvyšok */
  "nf.zalohovaVysvetlenie": "A díjbekérő fizetési felszólítás, nem adóügyi bizonylat — nem kerül be az áfába, és saját számsorból kap számot. Fizetés után rendes számlát állít ki, és azon számolja el az előleget.",
  "nf.ico": "Cégjegyzékszám",
  "nf.ulica": "Utca",
  "nf.mesto": "Város",
  "nf.dic": "Adószám",
  "nf.icDph": "Közösségi adószám",
  "nf.emailPole": "E-mail",
  "nf.spolu": "Összesen",
  "nf.dph": "Áfa",
  "nf.vystavenie": "Kiállítás",
  "nf.bezIbanu": "A cégnek nincs IBAN-ja — a számlán nem lesz hova fizetni. Adja meg a weben, a cég beállításaiban.",
  "nf.ziadnaZalohaPopis": "Ennek az ügyfélnek nincs elszámolatlan díjbekérője. Úgy állíthat ki egyet, hogy az új számla első lépésében a(z) {zalohova} lehetőséget választja.",
  "nf.cisloJeVase": "A szám az Öné, és senki másnak nem adjuk ki — nyugodtan átadhatja az ügyfélnek. A PDF elkészül, és a számla magától elmegy, amint van térerő.",
  "nf.odlozenaPopis": "Amint van térerő, magától kiállítódik számmal együtt. Egyelőre nincs száma, így nem tudja bediktálni az ügyfélnek — ha erre szüksége van, kapcsolja be a beállításokban az előre kiadott számokat.",
  "nf.hotovo": "Kész",
  "nf.pripravujemPdf": "PDF előkészítése…",
  "nf.bezPripojeniaNadpis": "Nincs kapcsolat",

  /* hlavná obrazovka appky */
  "app.chybaObrazovky": "Ezt a képernyőt nem sikerült megnyitni.",
  "app.slabePripojenie": "Általában gyenge kapcsolat okozza. Próbálja újra, vagy jelentkezzen be újra.",
  "app.skusitZnova": "Újrapróbálás",
  "app.prihlasitNanovo": "Bejelentkezés újra",
  "app.diagnostika": "Diagnosztika",
  "app.diagnostikaPopis": "Amit az alkalmazás lát a telefonon — csomag, tárhely, kapcsolat.",
  "app.novaVerzia": "Újabb alkalmazásverzió érhető el — koppintson a frissítéshez",
  "app.prihlasenie": "Bejelentkezés",
  "app.prihlasteSa": "Jelentkezzen be a Faktero-fiókjába.",
  "app.odomknutBiometriou": "Feloldás biometriával",
  "app.nemateUcet": "Nincs még fiókja?",
  "app.zaregistrujteSa": "Regisztráljon",
  "app.zabudnuteHeslo": "Elfelejtett jelszavát a faktero.sk oldalon állíthatja vissza.",
  "app.zamknute": "A Faktero zárolva van",
  "app.odomknitePokracujte": "Oldja fel biometriával, és folytassa ott, ahol abbahagyta.",
  "app.pridatDalsiuFirmu": "További cég hozzáadása",
  "app.odvolatZiadost": "Kérelem visszavonása",
  "app.zFakturyPrecita": "A számláról beolvassuk a szállítót, a dátumot, az összeget és az áfát. Mentés előtt ellenőrizze az adatokat.",
  "app.vyberteUhradu": "Válasszon fizetési módot",
  "app.povinne": "Kötelező",
  "app.vyberteMoznost": "Válasszon egy lehetőséget — enélkül a bizonylat nem menthető.",
  "app.hotovostnyDoklad": "A készpénzes bizonylat csökkenti a pénztár egyenlegét.",
  "app.fotkaDokladu": "A bizonylat fényképe",
  "app.prilozenePdf": "Csatolt PDF",
  "app.odfotitZnova": "Új fénykép",
  "app.otvaram": "Megnyitás…",
  "app.skenerDokladov": "Bizonylatolvasó",
  "app.ucet": "Fiók",
  "app.email": "E-mail",
  "app.heslo": "Jelszó",
  "app.vyberteFirmu": "Válasszon céget",
  "app.doVybranejFirmy": "A bizonylatok a kiválasztott céghez kerülnek",
  "app.staciNazov": "A név elég, a többit később is kiegészítheti",
  "app.fakturyADoklady": "Számlák és bizonylatok",
  "app.citamDoklad": "Bizonylat beolvasása…",
  "app.ukladamDoklad": "Bizonylat mentése…",
  "app.nasnimatQr": "QR-kód beolvasása",
  "app.namierteNaBlocek": "Irányítsa a blokk QR-kódjára",
  "app.odfotitBlocek": "A teljes blokk lefényképezése",
  "app.qrNaFotke": "A QR-kód a fényképen is megtalálható",
  "app.vybratSubor": "Fájl kiválasztása",
  "app.pdfAleboObrazok": "A számla PDF-je vagy képe",
  "app.stranySaSpoja": "Az oldalak egy PDF-be kerülnek",
  "app.skontrolujteDoklad": "Ellenőrizze a bizonylatot",
  "app.odfotitDoklad": "Bizonylat fényképezése",
  "app.papierovyDoklad": "A papírbizonylatot amúgy is meg kell őrizni — a fénykép helyettesíti",
  "app.vyplnteEmailHeslo": "Töltse ki az e-mailt és a jelszót is.",
  "app.prilohaNenahrata": "A mellékletet nem sikerült feltölteni, a bizonylatot enélkül mentem.",
  "app.dokladUlozeny": "Bizonylat mentve",
  "app.bezPripojeniaFirmy": "Nincs kapcsolat, és a telefonon még nincs cégjegyzék. Nyissa meg egyszer az alkalmazást internettel.",
  "app.fakturaOdoslana": "A jel nélkül kiállított számlát elküldtük.",
  "app.odoslanychOdlozenych": "Elküldött várakozó számlák: {pocet}.",
  "app.jazdaUlozena": "Felismert út mentve",
  "app.jazdUlozenych": "{pocet} felismert út mentve",
  "app.prihlasenieZlyhalo": "A bejelentkezés nem sikerült.",
  "app.prihlasujem": "Bejelentkezés…",
  "app.prihlasitSa": "Bejelentkezés",
  "app.odomykam": "Feloldás…",
  "app.odomknut": "Feloldás",
  "app.bezFirmy": "Ehhez a fiókhoz még nem tartozik cég. Enélkül a bizonylatoknak nincs hova kerülniük — hozza létre itt.",
  "app.blocekQr": "Blokk QR-kóddal",
  "app.fakturaPdf": "Számla PDF-ben",
  "app.viacstranovyDoklad": "Többoldalas bizonylat",
  "app.nepodariloPrecitat": "A bizonylatot nem sikerült beolvasni.",
  "app.citanieZlyhalo": "A beolvasás nem sikerült.",
  "app.spojenieStranZlyhalo": "Az oldalak egyesítése nem sikerült.",
  "app.bezSignaluOdosleSa": "Nincs térerő — a bizonylat magától elmegy, amint van kapcsolat.",
  "app.spojenieVypadlo": "A kapcsolat megszakadt — a bizonylat később magától elmegy.",
  "app.ulozenieZlyhalo": "A mentés nem sikerült.",
  "app.odfotitPrvuStranu": "Az első oldal fényképezése",
  "app.pridatDalsiuStranu": "További oldal hozzáadása",
  "app.zatialStran": "Eddig {pocet} oldal",
  "app.dokladOdfotteCely": "Fényképezze le az egész bizonylatot",
  "app.precitaneZDokladu": "A bizonylatról beolvasva",
  "app.ulozitDoklad": "Bizonylat mentése",
  "app.neznamyPredajca": "Ismeretlen eladó",
  "app.zDokladuZatvorka": "(a bizonylatról beolvasva)",
  "app.zTohoDph": "ebből áfa: {suma}",
  "app.bezPripojeniaKratke": "nincs kapcsolat",
  "app.bezOdpovede": "nincs válasz",

  /* zrušenie účtu */
  "app.zrusenieNaplanovane": "A fiók megszüntetése {termin} napra van ütemezve — {dni} múlva.",
  "spolocne.den1": "nap",
  "spolocne.den2": "nap",
  "spolocne.den5": "nap",

  /* množné tvary */
  "app.cakajuceFaktury": "{pocet} vár a telefonon elküldésre. Csatlakozzon, és nyissa meg a Kiállított számlákat — utána ki tud jelentkezni.",
  "spolocne.faktura1": "számla",
  "spolocne.faktura2": "számla",
  "spolocne.faktura5": "számla",

  /* appka — drobnosti */
  "app.odstranitStranu": "{n}. oldal eltávolítása",

  /* ponuky — prázdny zoznam */
  "ponuky.ziadnePopis2": "Az árajánlatot ugyanúgy készíti, mint a számlát — és ha az ügyfél elfogadja, egy koppintással számla lesz belőle.",

  /* drobnosti — kroky a stavy */
  "nf.oprava": "{cislo} javítása",
  "nf.fakturaCislo": "{cislo} számla",
  "faktury.pracujem": "Dolgozom…",
  "faktury.pripravujemPdf": "PDF előkészítése…",
  "pd.odosielam": "Küldés…",

  /* vystavené faktúry */
  "faktury.cakaNaOdoslanie": "Küldésre vár: {pocet}",

  /* prijaté doklady — úhrada */
  "pd.uhradeneZUctuDna": "Számláról fizetve: {den}",
  "pd.uhradeneSkratka": "számláról fizetve: {den}",

  /* súhrny */
  "nf.zakladDph": "nettó {zaklad} · áfa {dph}",
  "nf.odpocitaSa": "levonásra kerül: {suma}",

  /* šablónové texty */
  "banka.kFakture": "{cislo} számlához",
  "banka.aktualizovane": "Frissítve: {ked}",
  "jz.bezi": "fut {trvanie}",
  "jz.ukladaSaNa": "A(z) {auto} járműre mentjük — lentebb másik járművet választhat.",

  /* engedélyek az útnyilvántartáshoz (Android) */
  "pov.nadpis": "Hogy az utak maguktól rögzüljenek",
  "pov.uvod": "Az útnyilvántartás a háttérben méri az útvonalat — akkor is, ha a kijelző sötét és a telefon a zsebben van. E nélkül a kilométerek nem jönnének ki. A helyadatot csak az út kiszámításához használjuk, sehová nem küldjük.",
  "pov.poloha": "Helyadat — hogy az utat egyáltalán mérni lehessen.",
  "pov.notifikacie": "Értesítések — hogy az alkalmazás az út után megkérdezhesse, üzleti volt-e.",
  "pov.pohyb": "Mozgásérzékelők — hogy az utat gyorsabban felismerje.",
  "pov.vzdy": "Helyadat „Mindig“ — enélkül sötét kijelzőnél semmi sem mérhető.",
  "pov.povolit": "Engedélyezés",
  "pov.pytamSa": "Kérdezem…",
  "pov.neskor": "Később",
  "pov.vzdyNastavenia": "Még egy dolog: a „Mindig“ helyhozzáférést az Android csak a beállításokban engedi átkapcsolni. Megnyitjuk — válassza az Engedélyek → Helyadatok → Mindig engedélyezve lehetőséget.",
  "pov.otvoritNastavenia": "Beállítások megnyitása",
  "pov.hotovo": "Kész",
  "pov.zvysokNastavenia": "Ezt ablakból már nem lehet engedélyezni — az Android csak az alkalmazás beállításaiban kínálja. Megnyitjuk; keresse az Engedélyek pontot.",
  "app.spustam": "A Faktero indítása… ({faza}) · {balicek}",
  "app.startZasekol": "Az indítás elakadt a(z) „{faza}” lépésnél.",
  "app.balicek": "csomag {peciatka}",
  "app.hotovoStran": "Kész — {pocet} oldal",
  "app.poloziekZDokladu": "{pocet} tétel a bizonylatról",
  "nf.zFaktury": "{cislo} számláról",
  "nf.polozkyZFaktury": "Tételek a(z) {cislo} számláról",
  "nf.opravena": "{cislo} számla javítva",
  "nf.icoS": "Cégjegyzékszám: {ico}",
  "nf.zuctovanaZaloha": "Elszámolt előleg: {cislo}",
  "nf.dni": "{d} nap",
  "nf.zalohaCislo": "Előleg {cislo}",
  "nf.odoslaneNa": "Elküldve ide: {email}",
  "ponuky.vytvorena": "{cislo} árajánlat létrehozva.",
  "ponuky.vytvoritSuma": "Árajánlat létrehozása · {suma}",
  "ponuky.nazovSuboru": "{cislo} árajánlat",
  "pd.odoslaneDoklady": "Elküldött bizonylatok: {pocet}",
  "pd.cakaNaOdoslanie": "Küldésre vár: {pocet}",
  "spolocne.doklad1": "bizonylat",
  "spolocne.doklad2": "bizonylat",
  "spolocne.doklad5": "bizonylat",
  "pd.najdenePlatby": "Találtunk fizetéseket a bizonylatokhoz ({pocet})",
  "pd.polozkyPocet": "Tételek ({pocet})",
  "faktury.zmazana": "{cislo} számla törölve",
  "faktury.upomienkaOdoslana": "{n}. emlékeztető elküldve",
  "faktury.poslatUpomienku": "{n}. emlékeztető küldése",
  "faktury.zatialOdoslane": "Eddig elküldve: {pocet}",
  "faktury.naozajZmazat": "Biztosan törli a(z) {cislo} számlát?",

  /* spodná lišta */
  "tab.prehlad": "Áttekintés",
  "tab.doklady": "Bizonylatok",
  "tab.jazdy": "Utak",

  /* prehľad a vzhľad */
  "ph.nazov": "Áttekintés",
  "ph.neuhradene": "Kifizetetlen",
  "ph.poSplatnosti": "Lejárt",
  "ph.rychleAkcie": "Gyors műveletek",
  "ph.faktura": "Számla",
  "ph.skenovat": "Beolvasás",
  "ph.zacatJazdu": "Út indítása",
  "ph.naVybavenie": "Elintézendő",
  "ph.poslednaAktivita": "Legutóbbi tevékenység",
  "ph.fakturyPoSplatnosti": "{pocet} lejárt",
  "ph.dokladyNaKontrolu": "{pocet} ellenőrzésre vár",
  "ph.jazdaNeukoncena": "Egy út nincs lezárva",
  "ph.vsetkoVybavene": "Semmi nem vár",
  "ph.vsetkoVybavenePopis": "A számlák kifizetve, a bizonylatok ellenőrizve.",
  "ph.ziadnaAktivita": "Eddig nem történt semmi",
  "ph.ziadnaAktivitaPopis": "Az első számla vagy bizonylat itt jelenik meg.",
  "ph.fakturaCislo": "{cislo} számla",
  "ph.doklad": "Beérkezett bizonylat",
  "ph.dnes": "Ma",
  "ph.vcera": "Tegnap",
  "ph.vzhlad": "Megjelenés",
  "ph.svetly": "Világos",
  "ph.tmavy": "Sötét",
  "ph.podlaSystemu": "Rendszer szerint",

  /* filtre faktúr */
  "faktury.filterVsetky": "Összes",
  "faktury.filterNeuhradene": "Kifizetetlen",
  "faktury.filterPoSplatnosti": "Lejárt",
  "faktury.filterUhradene": "Kifizetve",
  "faktury.splatnostSkratka": "esedékes: {den}",
  "faktury.hladatKratke": "Keresés",
  "faktury.filtre": "Szűrők",

  /* skener — režimy */
  "sken.doklad": "Bizonylat",
  "sken.qrKod": "QR-kód",
  "sken.naskenujteDoklad": "Olvassa be a bizonylatot",
  "sken.automaticky": "A bizonylat beolvasása automatikus",
  "sken.namierteQr": "Irányítsa a QR-kódra",
  "sken.qrSaPrecita": "A kódot magától beolvassa, nem kell megnyomnia semmit",
  "sken.nastavenie": "Bizonylat beállításai",

  /* banka — párovanie */
  "banka.sparovane": "Párosítva",
  "banka.sparovat": "Párosítás",

  /* krokovník novej faktúry */
  "nf.krokOdberatel": "Ügyfél",
  "nf.krokPolozky": "Tételek",
  "nf.krokKontrola": "Ellenőrzés",
  "nf.nedavniOdberatelia": "Legutóbbi ügyfelek",
  "nf.vsetciOdberatelia": "Összes ügyfél",
  "nf.pokracovat": "Tovább",

  "spolocne.spat": "Vissza",
  "spolocne.ulozit": "Mentés",
  "spolocne.zrusit": "Mégse",
  "spolocne.nacitavam": "Betöltés…",
  "spolocne.km": "km",

  /* önálló Útnyilvántartás alkalmazás */
  "kj.nazov": "Útnyilvántartás",
  "kj.tabPrehlad": "Áttekintés",
  "kj.tabHistoria": "Előzmények",
  "kj.tabVozidla": "Járművek",
  "kj.tentoMesiac": "Ebben a hónapban",
  "kj.sluzobne": "Üzleti",
  "kj.sukromne": "Magán",
  "kj.posledneJazdy": "Legutóbbi utak",
  "kj.vyberVozidla": "Válasszon járművet",
  "kj.vyberVozidlaPopis": "Az útnyilvántartás járművenként készül.",
  "kj.mojeVozidlo": "Az én járművem",
  "kj.mojeVozidloPopis": "Koppintson arra az autóra, amelyet az alkalmazás az úthoz felajánl.",
  "kj.nastavitAkoMoje": "Beállítás sajátként",
  "kj.jazd1": "út",
  "kj.jazd2": "út",
  "kj.jazd5": "út",
  "kj.bezJazd": "Ebben a hónapban még nincs út",
  "kj.bezJazdPopis": "Az elsőt az alábbi zöld gombbal indíthatja.",
};
