import type { Kluc } from "./sk";

/** Magyar. Ami itt hiányzik, szlovákul jelenik meg. */
export const hu: Partial<Record<Kluc, string>> = {
  "tab.skener": "Szkenner",
  "tab.faktury": "Számlák",
  "tab.vytvorit": "Létrehozás",
  "tab.banka": "Bank",
  "tab.jazda": "Útnyilvántartás",
  "tab.navigacia": "Fő navigáció",
  "panel.nastavenia": "Beállítások",
  "panel.firma": "Cég",
  "panel.zmenitFirmu": "Cég váltása",
  "panel.bezFirmy": "Nincs cég",
  "panel.prehladAgend": "Összes terület",
  "panel.vystaveneFaktury": "Kiállított számlák",
  "panel.cenovePonuky": "Árajánlatok",
  "panel.prijateDoklady": "Beérkezett bizonylatok",
  "panel.pomoc": "Súgó",
  "panel.nastavenieAplikacie": "Alkalmazás beállításai",
  "panel.navody": "Faktero útmutatók",
  "panel.otvoriVPrehliadaci": "Böngészőben nyílik meg",
  "panel.blocky": "Blokkok és pénztár",
  "panel.nahlasitChybu": "Hiba vagy ötlet bejelentése",
  "panel.otvoritNaWebe": "Faktero megnyitása a weben",
  "panel.pravne": "Jogi dokumentumok",
  "panel.odhlasit": "Kijelentkezés",
  "panel.zavriet": "Bezárás",
  "panel.jazyk": "Nyelv",
  "domov.novaFaktura": "Új számla",
  "domov.novaFakturaPopis": "Vevő, tételek, fizetési határidő — és rögtön küldhető",
  "domov.vystaveneFaktury": "Kiállított számlák",
  "domov.vystaveneFakturyPopis": "Ki nem fizetett még, PDF és küldés",
  "domov.blocek": "Blokk QR-kóddal",
  "domov.blocekPopis": "Az adóhatóságtól töltődik be, tételekkel együtt",
  "domov.fakturaPdf": "Számla PDF-ben",
  "domov.fakturaPdfPopis": "Válasszon fájlt a telefonról vagy a felhőből",
  "domov.viacstranovy": "Többoldalas bizonylat",
  "domov.viacstranovyPopis": "Oldalanként, egyetlen PDF-be mentve",
  "domov.prijateDoklady": "Beérkezett bizonylatok",
  "domov.prijateDokladyPopis": "Blokkok és számlák, amelyeket már beolvasott",
  "domov.pohybyNaUcte": "Számlaforgalom",
  "domov.pohybyNaUctePopis": "Megérkezett-e a pénz — egyenleg és utolsó fizetések",
  "domov.novaJazda": "Új út",
  "domov.novaJazdaPopis": "A telefon méri a távolságot, csak indítás és leállítás",
  "jazdy.historia": "Utak előzményei",
  "jazdy.charakter": "Az út jellege",
  "jazdy.sluzobna": "Hivatalos",
  "jazdy.sukromna": "Magán",
  "jazdy.oznacenaSukromna": "Magánútként megjelölve.",
  "jazdy.oznacenaSluzobna": "Hivatalos útként megjelölve.",
  "jazdy.jazda": "Út",
  "jazdy.spolu": "Összesen",
  "jazdy.starsie": "Korábbi utak",
  "jazdy.ziadne": "Még nincsenek utak",
  "ponuky.nazov": "Árajánlatok",
  "ponuky.nova": "Új ajánlat",
  "ponuky.novaDlha": "Új árajánlat",
  "ponuky.ziadne": "Még nincs árajánlat",
  "ponuky.ziadnePopis":
    "Az ajánlatot ugyanúgy készíti el, mint a számlát — és ha a vevő elfogadja, egyetlen érintéssel számla lesz belőle.",
  "ponuky.vytvorit": "Ajánlat létrehozása",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Megosztás",
  "ponuky.odoslat": "Küldés",
  "ponuky.naFakturu": "Számlává",
  "ponuky.platiDo": "érvényes eddig",
  "ponuky.stav.vyfakturovana": "Kiszámlázva",
  "ponuky.stav.zamietnuta": "Elutasítva",
  "ponuky.stav.prijata": "Elfogadva",
  "ponuky.stav.poPlatnosti": "Lejárt",
  "ponuky.stav.odoslana": "Elküldve",
  "ponuky.stav.navrh": "Piszkozat",
  "ponuky.odberatel": "Vevő",
  "ponuky.polozky": "Tételek",
  "ponuky.pridajPolozku": "Tétel hozzáadása",
  "ponuky.vystavena": "Kiállítva",
  "ponuky.poznamka": "Megjegyzés",
  "ponuky.zaklad": "Nettó",
  "ponuky.dph": "ÁFA",
  "ponuky.hladatOdberatela": "Vevő keresése…",
  "ponuky.novyOdberatel": "Új vevő",
  "ponuky.nikNenajdeny": "Nincs találat.",
  "ponuky.zmenit": "módosítás",
  "spolocne.spat": "Vissza",
  "spolocne.ulozit": "Mentés",
  "spolocne.zrusit": "Mégse",
  "spolocne.nacitavam": "Betöltés…",
  "spolocne.km": "km",
};
