/**
 * Slovenské znenie — **zdroj pravdy**.
 *
 * Kľúč je cesta k miestu, kde text stojí (`tab.faktury`), nie samotná veta.
 * Vetou ako kľúčom sa preklady rozsypú pri prvej oprave preklepu v origináli.
 *
 * Ostatné jazyky sú `Partial<typeof sk>` — čo v nich chýba, spadne na
 * slovenčinu. Chýbajúci preklad tak vyzerá ako chýbajúci preklad, nie ako
 * pokazená appka.
 */
export const sk = {
  /* spodná lišta */
  "tab.skener": "Skener",
  "tab.faktury": "Faktúry",
  "tab.vytvorit": "Vytvoriť",
  "tab.banka": "Banka",
  "tab.jazda": "Kniha jázd",
  "tab.navigacia": "Hlavná navigácia",

  /* bočný panel */
  "panel.nastavenia": "Nastavenia",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Zmeniť firmu",
  "panel.bezFirmy": "Bez firmy",
  "panel.prehladAgend": "Prehľad agend",
  "panel.vystaveneFaktury": "Vystavené faktúry",
  "panel.cenovePonuky": "Cenové ponuky",
  "panel.prijateDoklady": "Prijaté doklady",
  "panel.pomoc": "Pomoc",
  "panel.nastavenieAplikacie": "Nastavenie aplikácie",
  "panel.navody": "Návody k Fakteru",
  "panel.otvoriVPrehliadaci": "Otvorí sa v prehliadači",
  "panel.blocky": "Bločky a pokladňa",
  "panel.nahlasitChybu": "Nahlásiť chybu alebo návrh",
  "panel.otvoritNaWebe": "Otvoriť Faktero na webe",
  "panel.pravne": "Právne dokumenty",
  "panel.odhlasit": "Odhlásiť sa",
  "panel.zavriet": "Zavrieť",
  "panel.jazyk": "Jazyk",

  /* domovská obrazovka */
  "domov.novaFaktura": "Nová faktúra",
  "domov.novaFakturaPopis": "Odberateľ, položky, splatnosť — a rovno odoslať",
  "domov.vystaveneFaktury": "Vystavené faktúry",
  "domov.vystaveneFakturyPopis": "Kto ešte nezaplatil, PDF a odoslanie",
  "domov.blocek": "Bloček s QR kódom",
  "domov.blocekPopis": "Načíta sa z Finančnej správy aj s položkami",
  "domov.fakturaPdf": "Faktúra v PDF",
  "domov.fakturaPdfPopis": "Vyberte súbor z telefónu alebo z cloudu",
  "domov.viacstranovy": "Viacstranový doklad",
  "domov.viacstranovyPopis": "Strana po strane, uloží sa ako jedno PDF",
  "domov.prijateDoklady": "Prijaté doklady",
  "domov.prijateDokladyPopis": "Bločky a faktúry, ktoré ste už naskenovali",
  "domov.pohybyNaUcte": "Pohyby na účte",
  "domov.pohybyNaUctePopis": "Či prišli peniaze — zostatok a posledné platby",
  "domov.novaJazda": "Nová jazda",
  "domov.novaJazdaPopis": "Kilometre odmeria telefón, stačí štart a stop",

  /* kniha jázd — história */
  "jazdy.historia": "História jázd",
  "jazdy.charakter": "Charakter jazdy",
  "jazdy.sluzobna": "Služobná",
  "jazdy.sukromna": "Súkromná",
  "jazdy.oznacenaSukromna": "Označená ako súkromná.",
  "jazdy.oznacenaSluzobna": "Označená ako služobná.",
  "jazdy.jazda": "Jazda",
  "jazdy.spolu": "Spolu",
  "jazdy.starsie": "Staršie jazdy",
  "jazdy.ziadne": "Zatiaľ žiadne jazdy",

  /* cenové ponuky */
  "ponuky.nazov": "Cenové ponuky",
  "ponuky.nova": "Nová ponuka",
  "ponuky.novaDlha": "Nová cenová ponuka",
  "ponuky.ziadne": "Zatiaľ žiadna cenová ponuka",
  "ponuky.ziadnePopis":
    "Ponuku spravíte rovnako ako faktúru — a keď ju zákazník prijme, jedným ťuknutím z nej faktúra vznikne.",
  "ponuky.vytvorit": "Vytvoriť ponuku",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Zdieľať",
  "ponuky.odoslat": "Odoslať",
  "ponuky.naFakturu": "Na faktúru",
  "ponuky.platiDo": "platí do",
  "ponuky.stav.vyfakturovana": "Vyfakturovaná",
  "ponuky.stav.zamietnuta": "Zamietnutá",
  "ponuky.stav.prijata": "Prijatá",
  "ponuky.stav.poPlatnosti": "Po platnosti",
  "ponuky.stav.odoslana": "Odoslaná",
  "ponuky.stav.navrh": "Návrh",
  "ponuky.odberatel": "Odberateľ",
  "ponuky.polozky": "Položky",
  "ponuky.pridajPolozku": "Pridať položku",
  "ponuky.vystavena": "Vystavená",
  "ponuky.poznamka": "Poznámka",
  "ponuky.zaklad": "Základ",
  "ponuky.dph": "DPH",
  "ponuky.hladatOdberatela": "Hľadať odberateľa…",
  "ponuky.novyOdberatel": "Nový odberateľ",
  "ponuky.nikNenajdeny": "Nikto sa nenašiel.",
  "ponuky.zmenit": "zmeniť",

  "domov.skupina.fakturacia": "Fakturácia",
  "domov.skupina.skenovanie": "Skenovanie dokladov",
  "domov.skupina.banka": "Banka",
  "domov.skupina.jazdy": "Kniha jázd",

  /* vystavené faktúry */
  "faktury.nazov": "Vystavené faktúry",
  "faktury.hladat": "Hľadať číslo alebo odberateľa",
  "faktury.nacitavam": "Načítavam faktúry…",
  "faktury.ziadne": "Zatiaľ žiadne faktúry",
  "faktury.vystavPrvu": "Vystaviť prvú faktúru",
  "faktury.nicSaNenaslo": "Nič sa nenašlo",
  "faktury.bezOdberatela": "Bez odberateľa",
  "faktury.stav.navrh": "Návrh",
  "faktury.stav.vystavena": "Vystavená",
  "faktury.stav.odoslana": "Odoslaná",
  "faktury.stav.uhradena": "Uhradená",
  "faktury.stav.neuhradena": "Neuhradená",
  "faktury.stav.splatna": "Splatná",
  "faktury.stav.poSplatnosti": "Po splatnosti",
  "faktury.stav.stornovana": "Stornovaná",
  "faktury.otvoritPdf": "Otvoriť PDF",
  "faktury.zdielat": "Zdieľať faktúru",
  "faktury.zdielatPopis": "Pošlite ju cez WhatsApp, Messenger alebo uložte do súborov",
  "faktury.poslatEmailom": "Poslať e-mailom",
  "faktury.oznacitUhradenu": "Označiť ako uhradenú",
  "faktury.oznacitPopis": "Keď platba prišla mimo párovania s bankou",
  "faktury.oznacenaUhradena": "Označená ako uhradená",
  "faktury.upravit": "Upraviť faktúru",
  "faktury.upravitPopis": "Položky, dátumy aj poznámka",
  "faktury.zmazat": "Zmazať faktúru",
  "faktury.zmazatPopis":
    "Zmizne zo zoznamu, ale číslo ostáva obsadené — v číselnom rade nevznikne diera.",
  "faktury.zmazatKratke": "Zmazať",
  "faktury.ponechat": "Ponechať",
  "faktury.mazem": "Mažem…",
  "faktury.naPrezretie": "Faktúra na prezretie",
  "faktury.bezPripojenia": "Bez pripojenia — zobrazené naposledy načítané faktúry.",
  "faktury.bezPripojeniaNacitanie": "Bez pripojenia sa faktúry nedajú načítať",
  "faktury.odlozenaVystavena": "Odložená faktúra je vystavená.",
  "faktury.odosluSaSamy": "Odošlú sa samy, len čo bude signál. Netreba na to myslieť.",
  "faktury.chybaNacitania": "Faktúry sa nepodarilo načítať.",
  "faktury.chybaMazania": "Faktúru sa nepodarilo zmazať.",
  "faktury.chybaPdf": "PDF sa nepodarilo pripraviť.",
  "faktury.chybaZdielania": "Zdieľanie zlyhalo.",
  "faktury.chybaUpomienky": "Upomienku sa nepodarilo odoslať.",

  /* nová faktúra */
  "nf.komuFakturujete": "Komu fakturujete?",
  "nf.zaCoFakturujete": "Za čo fakturujete?",
  "nf.skontrolujte": "Skontrolujte faktúru",
  "nf.skontrolujteZalohovu": "Skontrolujte zálohovú",
  "nf.krok": "Krok {n} z 3",
  "nf.krokZalohova": "Krok 1 z 3 · zálohová",
  "nf.faktura": "Faktúra",
  "nf.zalohova": "Zálohová",
  "nf.odberatel": "Odberateľ",
  "nf.hladatOdberatela": "Hľadať odberateľa",
  "nf.novyOdberatel": "Nový odberateľ",
  "nf.ziadnyOdberatel": "Zatiaľ nemáte žiadneho odberateľa.",
  "nf.nicSaNenaslo": "Nič sa nenašlo.",
  "nf.nacitavamOdberatelov": "Načítavam odberateľov…",
  "nf.nazov": "Názov",
  "nf.zadajteNazov": "Zadajte názov odberateľa.",
  "nf.podlaIco": "Podľa IČO sa doplní názov aj adresa",
  "nf.hladamVRegistri": "Hľadám v registri…",
  "nf.udajeDoplnene": "Údaje doplnené z registra",
  "nf.psc": "PSČ",
  "nf.email": "Na tento e-mail sa dá faktúra hneď odoslať",
  "nf.odberatelPridany": "Odberateľ pridaný",
  "nf.chybaOdberatela": "Odberateľa sa nepodarilo uložiť.",
  "nf.polozky": "Položky",
  "nf.nazovPolozky": "Názov položky",
  "nf.mnozstvo": "Množstvo",
  "nf.pridajtePolozku": "Pridajte položku",
  "nf.odstranitPolozku": "Odstrániť položku",
  "nf.zCennika": "Z cenníka",
  "nf.vlastna": "Vlastná",
  "nf.cennik": "Cenník",
  "nf.hladatPolozku": "Hľadať položku",
  "nf.zopakovatPoslednu": "Zopakovať poslednú faktúru",
  "nf.splatnost": "Splatnosť",
  "nf.splatnostSkor": "Splatnosť nemôže byť skôr ako vystavenie.",
  "nf.sposobUhrady": "Spôsob úhrady",
  "nf.hotovost": "Hotovosť",
  "nf.poznamkaNad": "Poznámka nad položkami",
  "nf.poznamkaPod": "Poznámka pod položkami",
  "nf.priklad": "Napríklad: podľa objednávky č. 2026/114",
  "nf.zaklad": "Základ",
  "nf.naUhradu": "Na úhradu",
  "nf.dalej": "Ďalej",
  "nf.zrusit": "Zrušiť",
  "nf.zavriet": "Zavrieť",
  "nf.ulozitPokracovat": "Uložiť a pokračovať",
  "nf.ulozitZmeny": "Uložiť zmeny",
  "nf.ukladam": "Ukladám…",
  "nf.ukladamZmeny": "Ukladám zmeny…",
  "nf.vystavit": "Vystaviť faktúru",
  "nf.vystavitZalohovu": "Vystaviť zálohovú faktúru",
  "nf.vystavujem": "Vystavujem faktúru…",
  "nf.vystavena": "Faktúra vystavená",
  "nf.maCislo": "Faktúra má pridelené číslo",
  "nf.odlozena": "Faktúra je odložená v telefóne",
  "nf.naPrezretie": "Faktúra na prezretie",
  "nf.otvoritPdf": "Otvoriť PDF",
  "nf.zdielat": "Zdieľať faktúru",
  "nf.zdielatPopis": "Pošlite ju cez WhatsApp, Messenger alebo uložte do súborov",
  "nf.poslatEmailom": "Poslať e-mailom",
  "nf.odoslane": "Odoslané",
  "nf.odosielam": "Odosielam faktúru…",
  "nf.bezEmailu":
    "Odberateľ nemá e-mail, tak sa faktúra nedá odoslať. Doplňte ho v karte odberateľa.",
  "nf.zalohy": "Nezúčtované zálohy tohto odberateľa",
  "nf.hladamZalohy": "Hľadám zálohy…",
  "nf.ziadnaZaloha": "Žiadna zálohová faktúra na zúčtovanie",
  "nf.pridatZalohovu": "Pridať zálohovú faktúru",
  "nf.bezPripojenia": "Bez pripojenia — pracujem s naposledy načítanými údajmi.",
  "nf.bezPripojeniaVystavit":
    "Bez pripojenia a bez uložených odberateľov sa faktúra vystaviť nedá. Otvorte túto obrazovku raz s internetom.",
  "nf.zalohovaBezPripojenia": "Zálohovú faktúru sa bez pripojenia vystaviť nedá.",
  "nf.opravaBezPripojenia": "Na opravu faktúry treba pripojenie.",
  "nf.chybaPodkladov": "Podklady sa nepodarilo načítať.",
  "nf.chybaNacitania": "Faktúru sa nepodarilo načítať.",
  "nf.chybaVystavenia": "Faktúru sa nepodarilo vystaviť.",
  "nf.chybaZmien": "Zmeny sa nepodarilo uložiť.",
  "nf.chybaPdf": "PDF sa nepodarilo pripraviť.",
  "nf.chybaZdielania": "Zdieľanie zlyhalo.",

  /* prijaté doklady a banka */
  "pd.nazov": "Prijaté doklady",
  "pd.hladat": "Hľadať dodávateľa alebo číslo",
  "pd.nacitavam": "Načítavam doklady…",
  "pd.ziadne": "Zatiaľ žiadne doklady",
  "pd.ziadnePopis": "Naskenované bločky a faktúry sa objavia tu.",
  "pd.nicSaNenaslo": "Nič sa nenašlo",
  "pd.skusteInak": "Skúste hľadať inak.",
  "pd.bezDodavatela": "Bez dodávateľa",
  "pd.neprecitany": "Neprečítaný doklad",
  "pd.zFinancnejSpravy": "Z Finančnej správy",
  "pd.sQrKodom": "· s QR kódom",
  "pd.cisloDokladu": "Číslo dokladu",
  "pd.poznamka": "Poznámka",
  "pd.sposobUhrady": "Spôsob úhrady",
  "pd.hotovost": "Hotovosť",
  "pd.kartou": "Kartou",
  "pd.prevodom": "Prevodom",
  "pd.sposobZmeneny": "Spôsob úhrady zmenený",
  "pd.otvoritPdf": "Otvoriť PDF",
  "pd.nacitavamPrilohu": "Načítavam prílohu…",
  "pd.presunut": "Presunúť medzi prijaté faktúry",
  "pd.presuvam": "Presúvam…",
  "pd.presunuty": "Doklad je medzi prijatými faktúrami.",
  "pd.zmazat": "Zmazať doklad",
  "pd.zmazatKratke": "Zmazať",
  "pd.naozajZmazat": "Naozaj zmazať tento doklad?",
  "pd.nedaSaVratit": "Vrátiť sa to nedá.",
  "pd.zmazany": "Doklad zmazaný",
  "pd.ponechat": "Ponechať",
  "pd.zrusit": "Zrušiť",
  "pd.sparovat": "Spárovať",
  "pd.anoPatriKSebe": "Áno, patrí k sebe",
  "pd.uhradenyZUctu": "Doklad označený za uhradený z účtu.",
  "pd.parovanieZrusene": "Párovanie zrušené.",
  "pd.chybaParovania": "Spárovať sa to nepodarilo.",
  "pd.chybaZrusenia": "Zrušiť sa to nepodarilo.",
  "pd.chybaNacitania": "Doklady sa nepodarilo načítať.",
  "pd.bezPripojenia": "Bez pripojenia sa doklady nedajú načítať",
  "pd.odlozeneOdoslu": "Odložené bločky sa odošlú samy, len čo sa vráti signál.",
  "pd.bezSignalu": "Zatiaľ bez signálu — skúsim to znova sám.",
  "pd.zahodit": "Zahodiť odložený doklad",
  "pd.odoslat": "Odoslať",
  "banka.ucet": "Účet",
  "banka.vsetky": "Všetky",
  "banka.nacitavam": "Načítavam pohyby…",
  "banka.ziadnePohyby": "Zatiaľ žiadne pohyby",
  "banka.stiahnut": "Stiahnuť z banky",
  "banka.stahujem": "Sťahujem z banky…",
  "banka.ziadneNove": "Žiadne nové pohyby.",
  "banka.prijataPlatba": "Prijatá platba",
  "banka.odchadzajucaPlatba": "Odchádzajúca platba",
  "banka.dnes": "Dnes",
  "banka.vcera": "Včera",
  "banka.nesynchronizovane": "zatiaľ nesynchronizované",
  "banka.bezUctu": "Firma nemá pripojený bankový účet",
  "banka.pripojenieNaWebe":
    "Účet sa pripája na webe — banka pri tom vyžaduje prihlásenie a súhlas, ktorý sa v telefóne dobre vybaviť nedá.",
  "banka.bezPripojenia": "Bez pripojenia sa účty nedajú načítať",
  "banka.lenSoSignalom":
    "Zostatky a pohyby sa dajú pozrieť, len keď je signál — z telefónu sa nikam neukladajú.",
  "banka.neodpovedala": "Banka teraz neodpovedala. Skúste to o chvíľu.",
  "banka.chybaNacitania": "Pohyby sa nepodarilo načítať.",

  /* kniha jázd */
  "jz.novaJazda": "Nová jazda",
  "jz.zacatJazdu": "Začať jazdu",
  "jz.jazdaBezi": "Jazda beží",
  "jz.jazdaPozastavena": "Jazda pozastavená",
  "jz.meranieNebezi": "meranie zatiaľ nebeží",
  "jz.pozastavene": "pozastavené — pohyb sa nezapočítava",
  "jz.pozastavitMeranie": "Pozastaviť meranie",
  "jz.pokracovatVMerani": "Pokračovať v meraní",
  "jz.tuknutimPozastavite": "Ťuknutím na kruh pozastavíte meranie",
  "jz.tuknutimPokracujete": "Ťuknutím na kruh budete pokračovať",
  "jz.ukoncitAUlozit": "Ukončiť a uložiť jazdu",
  "jz.ukladamJazdu": "Ukladám jazdu…",
  "jz.ucelCesty": "Účel cesty",
  "jz.ucelPriklad": "napr. servis u odberateľa",
  "jz.ulozeneSluzobna": "Uložené ako služobná",
  "jz.ulozeneSukromna": "Uložené ako súkromná",
  "jz.bezSignaluOdoslana": "Jazda zapísaná bez signálu je odoslaná",
  "jz.chybaUlozenia": "Jazdu sa nepodarilo uložiť.",
  "jz.chybaGps": "GPS sa nepodarilo spustiť.",
  "jz.chybaPokracovania": "V meraní sa nepodarilo pokračovať.",
  "jz.rozpoznanaBezi": "Prebieha rozpoznaná jazda",
  "jz.ukoncitJazdu": "Ukončiť jazdu",
  "jz.ukoncujem": "Ukončujem…",
  "jz.zahodit": "Zahodiť",
  "jz.zahoditOtazka": "Zahodiť túto jazdu? Do knihy jázd sa nezapíše.",
  "jz.ukoncena": "Jazda ukončená — zaraďte ju nižšie.",
  "jz.zahodena": "Jazda zahodená.",
  "jz.vozidloPreJazdu": "Vozidlo pre rozpoznanú jazdu",
  "jz.telefonNevie": "Telefón nevie, do ktorého auta ste sadli — skontrolujte ho pri každej jazde.",
  "jz.rozpoznavat": "Rozpoznávať jazdy automaticky",
  "jz.detekciaZapnuta": "Detekcia jázd je zapnutá",
  "jz.detekciaNemaAkoBezat": "Detekcia je zapnutá, ale nemá ako bežať",
  "jz.vyzadujePolohu": "Vyžaduje polohu „Vždy“.",
  "jz.akoFunguje": "Ako rozpoznávanie funguje",
  "jz.ukazatTrasu": "Ukázať trasu",
  "jz.skrytTrasu": "Skryť trasu",
  "jz.historia": "história",
  "jz.noveVozidlo": "Nové vozidlo",
  "jz.pridatVozidlo": "Pridať vozidlo",
  "jz.vozidloPridane": "Vozidlo pridané",
  "jz.chybaVozidla": "Vozidlo sa nepodarilo pridať.",
  "jz.zadajteNazovVozidla": "Zadajte názov vozidla.",
  "jz.evidencneCislo": "Evidenčné číslo",
  "jz.nazovVozidlaPriklad": "napr. Škoda Octavia",
  "jz.ukladamVozidlo": "Ukladám vozidlo…",
  "jz.nacitavamVozidla": "Načítavam vozidlá…",
  "jz.bezVozidla": "Firma nemá žiadne vozidlo",
  "jz.pridajteHo": "Pridajte ho tu — stačí názov a značka, zvyšok sa dá doplniť na webe.",
  "jz.commander": "Jazdy tohto auta ťahá Commander",
  "jz.bezPripojenia": "Bez pripojenia sa vozidlá nedajú načítať",
  "jz.bezZoznamu": "V telefóne zatiaľ nie je uložený zoznam. Otvorte túto obrazovku raz s internetom.",
  "jz.nepovinneCena": "Nepovinné, ale bez nej vyjde náklad na jazdu nula.",

  /* skener, notifikácie, čísla dopredu */
  "jz.nahravamJazdu": "Nahrávam jazdu",
  "jz.spustenaRucne": "spustená ručne",
  "jz.otvoritPrebiehajucu": "Otvoriť prebiehajúcu jazdu",
  "qr.namierte": "Namierte na QR kód",
  "qr.zrusitSkenovanie": "Zrušiť skenovanie",
  "qr.kameraNejde": "Kameru sa nepodarilo spustiť. Skúste doklad odfotiť.",
  "qr.kameraZamietnuta": "Prístup ku kamere je zamietnutý. Povoľte ho v nastaveniach telefónu.",
  "push.nazov": "Notifikácie",
  "push.zistujem": "Zisťujem…",
  "push.zaregistrovane": "Zariadenie je zaregistrované, notifikácie chodiť budú.",
  "push.neznameZariadenie": "Server toto zariadenie zatiaľ nepozná.",
  "push.povolenieVTelefone": "Povolenie v telefóne:",
  "push.lenVApke": "len v mobilnej aplikácii",
  "push.pluginNedostupny": "plugin nedostupný",
  "push.registraciaZlyhala": "registrácia zlyhala",
  "push.zaregistrovatZnova": "Zaregistrovať znova",
  "push.skusitZaregistrovat": "Skúsiť zaregistrovať",
  "spolocne.chyba": "Chyba",
  "cisla.nazov": "Vystavovať bez signálu rovno s číslom",
  "cisla.vypnutePopis": "Bez toho sa faktúra bez signálu odloží a vystaví sa sama po pripojení — číslo dostane až vtedy.",
  "cisla.zapnutePopis": "Pripravených čísel: {pocet}. Faktúra vystavená bez signálu dostane číslo hneď, takže sa dá odovzdať na mieste.",
  "cisla.zapnut": "Zapnúť",
  "cisla.vypnut": "Vypnúť",
  "cisla.vypnute": "Vypnuté. Nepoužité čísla sa vrátili do radu.",
  "cisla.zapnute": "Zapnuté. Appka má {pocet} čísel pripravených.",
  "cisla.trebaPripojenie": "Na zapnutie treba pripojenie — čísla si vypýta appka od servera.",
  "cisla.nepodariloVypytat": "Čísla sa nepodarilo vypýtať. Skúste to o chvíľu.",
  "cisla.nepodariloPrepnut": "Nepodarilo sa to prepnúť.",

  /* skener, firma, registrácia */
  "sken.naskenujte": "Naskenujte QR kód bločku",
  "sken.aleboOdfotte": "alebo odfoťte doklad",
  "sken.kameraNejde": "Doklad sa dá aj tak odfotiť alebo vybrať zo súborov — tlačidlá nižšie fungujú.",
  "sken.odfotit": "Odfotiť",
  "sken.zGalerie": "Z galérie",
  "sken.uhrada": "Úhrada",
  "sken.karta": "Karta",
  "sken.kategoria": "Kategória nákladu",
  "sken.nezaradene": "Nezaradené",
  "sken.pdfSubor": "PDF súbor",
  "sken.viacstranovy": "Viacstranový",
  "vf.vytvorteSiFirmu": "Vytvorte si firmu",
  "vf.pridatFirmu": "Pridať firmu",
  "vf.podnadpis": "Tieto údaje sa zobrazia na faktúrach",
  "vf.vytvaram": "Vytváram…",
  "vf.vytvoritFirmu": "Vytvoriť firmu",
  "vf.uvod": "Stačí názov — ostatné sa dá doplniť kedykoľvek neskôr v nastaveniach. Keď zadáte IČO, adresu aj daňové čísla si natiahneme z registra.",
  "vf.nazovFirmy": "Názov firmy",
  "vf.ico": "IČO",
  "vf.dic": "DIČ",
  "vf.icDph": "IČ DPH",
  "vf.ulica": "Ulica a číslo",
  "vf.mesto": "Mesto",
  "vf.psc": "PSČ",
  "vf.iban": "IBAN",
  "vf.ibanHint": "Zákazník podľa neho zaplatí — pokojne aj neskôr.",
  "vf.email": "E-mail",
  "vf.telefon": "Telefón",
  "vf.hladamVRegistri": "Hľadám v registri…",
  "vf.trebaPripojenie": "Na založenie firmy treba pripojenie. Skúste to, keď bude signál.",
  "vf.nepodariloVytvorit": "Firmu sa nepodarilo vytvoriť.",
  "vf.vytvorena": "Firma je vytvorená.",
  "vf.chyba.nazov": "Zadajte názov firmy.",
  "vf.chyba.ico": "IČO má 6 až 8 číslic.",
  "vf.chyba.email": "Zadajte platný e-mail firmy.",
  "vf.chyba.iban": "IBAN nemá správny tvar.",
  "reg.potvrdteEmail": "Potvrďte si e-mail",
  "reg.potvrdenieText": "Účet {email} je vytvorený. Poslali sme naň odkaz — otvorte ho a vráťte sa sem. Appka si potvrdenia všimne sama; keby nie, je tu tlačidlo nižšie. Bez potvrdenia sa prihlásiť nedá.",
  "reg.spamPriecinok": "Ak e-mail do pár minút nepríde, pozrite sa do nevyžiadanej pošty.",
  "reg.overujem": "Overujem…",
  "reg.uzSomPotvrdil": "Už som potvrdil, pokračovať",
  "reg.posielam": "Posielam…",
  "reg.poslatZnova": "Poslať e-mail znova",
  "reg.spatNaPrihlasenie": "Späť na prihlásenie",
  "reg.vytvorteSiUcet": "Vytvorte si účet",
  "reg.zadarmo": "30 dní zadarmo na pláne Premium. Bez platobnej karty.",
  "reg.meno": "Meno a priezvisko",
  "reg.email": "E-mail",
  "reg.heslo": "Heslo (aspoň 8 znakov)",
  "reg.suhlasPodmienky": "Súhlasím s {odkaz}.",
  "reg.obchodnePodmienky": "Obchodnými podmienkami",
  "reg.suhlasGdpr": "Beriem na vedomie {odkaz}.",
  "reg.spracuvanieUdajov": "Spracúvanie osobných údajov",
  "reg.vytvaram": "Vytváram…",
  "reg.vytvoritUcet": "Vytvoriť účet",
  "reg.uzMamUcet": "Už mám účet, prihlásiť sa",
  "reg.ucetJeVytvoreny": "Účet je vytvorený.",
  "reg.registraciaZlyhala": "Registrácia zlyhala.",
  "reg.nepotvrdene": "Zatiaľ to nie je potvrdené. Otvorte odkaz z e-mailu a skúste to znova.",
  "reg.emailPoslanyZnova": "E-mail sme poslali znova.",
  "reg.chyba.meno": "Zadajte meno a priezvisko.",
  "reg.chyba.email": "Zadajte platný e-mail.",
  "reg.chyba.heslo": "Heslo musí mať aspoň 8 znakov.",
  "reg.chyba.suhlasy": "Potvrďte obidva súhlasy.",

  /* cenové ponuky */
  "ponuky.bezEmailu": "Odberateľ nemá e-mail. Doplňte ho na jeho karte.",
  "ponuky.odoslatOtazka": "Odoslať ponuku {cislo} na {email}?",
  "ponuky.odoslana": "Ponuka odoslaná.",
  "ponuky.uzFakturovana": "Z tejto ponuky už faktúra vznikla.",
  "ponuky.naFakturuOtazka": "Vytvoriť faktúru z ponuky {cislo}?",
  "ponuky.fakturaVytvorena": "Faktúra vytvorená.",
  "ponuky.platiDoSkratka": "platí do {den}",
  "ponuky.vyberteOdberatela": "Vyberte odberateľa.",
  "ponuky.doplntePolozku": "Doplňte aspoň jednu položku.",
  "ponuky.platnostPredVystavenim": "Platnosť nemôže byť pred vystavením.",
  "ponuky.nepodariloVytvorit": "Ponuku sa nepodarilo vytvoriť.",
  "ponuky.vytvaram": "Vytváram ponuku…",

  /* kniha jázd — zvyšok */
  "jz.odCasu": "Od {cas}. Keď ste dojazdili, ukončite ju — inak sa zastaví sama až po piatich minútach státia.",
  "jz.rozpoznalaJazdu": "Appka rozpoznala jazdu",
  "jz.rozpoznalaJazdy": "Appka rozpoznala jazdy ({pocet})",
  "jz.commanderZvysok": ", takže ich telefón merať nemusí — vyber iné auto, alebo nechaj detekciu vypnutú.",
  "jz.typJazdy": "Typ jazdy",
  "jz.vozidlo": "Vozidlo",
  "jz.nazovVozidla": "Názov",
  "jz.spotreba": "Spotreba (l/100 km)",
  "jz.spotrebaPriklad": "napr. 6,5",
  "jz.vsimneSi": "Appka si jazdu všimne sama a spýta sa notifikáciou, či bola služobná.",
  "jz.lenPocasPouzivania": "Ak ste polohu povolili len „počas používania“, nechajte appku otvorenú — po zhasnutí displeja telefón meranie zastaví a kilometre by sa doratali nesprávne. S povolením „Vždy“ beží meranie aj vo vrecku.",
  "jz.vyberteVozidlo": "Vyberte vozidlo.",
  "jz.odoslanychJazd": "Odoslaných {pocet} jázd zapísaných bez signálu",
  "jz.rozpoznanaUlozena": "Rozpoznaná jazda uložená — {km} km, {auto}",
  "jz.bezPolohy": "Nenamerali sme žiadnu polohu, jazdu som neuložil. Skúste to vonku — v budove je poloha nepresná — a polohu povoľte na „Vždy“.",
  "jz.ulozenaVTelefone": "Jazda uložená v telefóne — {km} km. Odošle sa po pripojení.",
  "jz.ulozenaKm": "Jazda uložená — {km} km",
  "jz.historiaVozidla": "História jázd — {auto}",

  /* bočný panel */
  "panel.nadpis": "Panel nastavení",
  "panel.prihlasenyAko": "Prihlásený ako",
  "panel.vsetkoNaJednej": "Všetko, čo appka vie, na jednej obrazovke",
  "panel.ucetPamat": "Účet a jeho zrušenie, pamäť, pripojenie, verzia",
  "panel.ekasaPopis": "Ako sa čítajú doklady z eKasy",
  "panel.napisteNam": "Napíšte nám, čo nefunguje alebo čo by pomohlo",
  "panel.zvysokAplikacie": "Faktúry, sklad a zvyšok aplikácie",
  "panel.pravnePopis": "Podmienky, ochrana údajov a ostatné — otvorí sa v prehliadači",
  "panel.biometria": "Prihlásenie biometriou",
  "panel.biometriaZapnuta": "Pýta sa pri spustení appky",
  "panel.biometriaVypnuta": "Vypnuté",
  "panel.biometriaNedostupna": "Biometria na tomto zariadení nie je dostupná.",
  "panel.rychleZapnute": "Rýchle prihlásenie zapnuté",
  "panel.rychleVypnute": "Rýchle prihlásenie vypnuté",
  "panel.nepodariloZapnut": "Nepodarilo sa zapnúť",

  /* doklady, faktúry, jazdy, banka — zvyšok */
  "pd.doklad": "Doklad",
  "pd.ico": "IČO",
  "pd.icDph": "IČ DPH",
  "faktury.vystavenychPocet": "Vystavených faktúr: {pocet}.",
  "faktury.neuhradene": "Neuhradené",
  "faktury.odosluSaSamy2": "Odošlú sa samy, len čo bude signál. Netreba na to myslieť.",
  "faktury.bezZoznamu": "V telefóne zatiaľ nie je uložený žiadny zoznam. Otvorte túto obrazovku raz s internetom a potom bude dostupná aj bez neho.",
  "faktury.vystavena": "Vystavená",
  "faktury.splatna": "Splatná",
  "faktury.uhradena": "Uhradená",
  "faktury.odoslana": "Odoslaná",
  "faktury.cisloOstava": "Zmizne zo zoznamu, ale číslo ostáva obsadené — v číselnom rade nevznikne diera.",
  "jazdy.nacitavam": "Načítavam jazdy…",
  "jazdy.prvaPribudne": "Prvá pribudne po ukončení merania — alebo sa natiahne z GPS jednotky, keď je vozidlo prepojené.",
  "jazdy.spoluCelaHistoria": "Spolu za celú históriu",
  "jazdy.spoluPoslednych": "Spolu za posledných {pocet} jázd",
  "jazdy.nacitatStarsie": "Načítať staršie jazdy",
  "jazdy.chybaStarsich": "Staršie jazdy sa nepodarilo načítať.",
  "jazdy.zmazatJazdu": "Zmazať jazdu",
  "jazdy.naozajZmazat": "Naozaj zmazať",
  "jazdy.mazem": "Mažem…",
  "jazdy.zmazana": "Jazda je zmazaná",
  "jazdy.mazeLenSpravca": "Jazdu môže zmazať len správca firmy.",
  "banka.nazov": "Banka",
  "banka.vsetkyUcty": "Všetky",
  "banka.ucetSkratka": "účet",

  /* banka — prepínač účtov */
  "banka.ucetVelke": "Účet",
  "banka.zostatokSpolu": "Zostatok spolu",

  /* nová faktúra — zvyšok */
  "nf.zalohovaVysvetlenie": "Zálohová faktúra je výzva na platbu, nie daňový doklad — nevstupuje do DPH a dostane číslo z vlastnej rady. Po zaplatení na ňu vystavíte bežnú faktúru a zálohu na nej zúčtujete.",
  "nf.ico": "IČO",
  "nf.ulica": "Ulica",
  "nf.mesto": "Mesto",
  "nf.dic": "DIČ",
  "nf.icDph": "IČ DPH",
  "nf.emailPole": "E-mail",
  "nf.spolu": "Spolu",
  "nf.dph": "DPH",
  "nf.vystavenie": "Vystavenie",
  "nf.bezIbanu": "Firma nemá vyplnený IBAN — na faktúre nebude kam zaplatiť. Doplňte ho na webe v nastaveniach firmy.",
  "nf.ziadnaZalohaPopis": "Tento odberateľ nemá zálohovú faktúru, ktorá by ešte nebola zúčtovaná. Vystavíte ju tak, že v prvom kroku novej faktúry vyberiete {zalohova}.",
  "nf.cisloJeVase": "Číslo je vaše a nikomu inému sa nepridelí — pokojne ho odovzdajte zákazníkovi. PDF sa vytvorí a faktúra odošle sama, len čo bude signál.",
  "nf.odlozenaPopis": "Vystaví sa aj s číslom sama, len čo bude signál. Číslo zatiaľ nemá, takže sa zákazníkovi nedá nadiktovať — ak to potrebujete, zapnite si v nastaveniach vydávanie s číslom dopredu.",
  "nf.hotovo": "Hotovo",
  "nf.pripravujemPdf": "Pripravujem PDF…",
  "nf.bezPripojeniaNadpis": "Bez pripojenia",

  /* hlavná obrazovka appky */
  "app.chybaObrazovky": "Túto obrazovku sa nepodarilo otvoriť.",
  "app.slabePripojenie": "Býva to slabým pripojením. Skúste to znova, alebo sa prihláste nanovo.",
  "app.skusitZnova": "Skúsiť znova",
  "app.prihlasitNanovo": "Prihlásiť sa nanovo",
  "app.diagnostika": "Diagnostika",
  "app.diagnostikaPopis": "Čo appka v telefóne vidí — balíček, pamäť, pripojenie.",
  "app.novaVerzia": "Je dostupná novšia verzia aplikácie — ťuknite na aktualizáciu",
  "app.prihlasenie": "Prihlásenie",
  "app.prihlasteSa": "Prihláste sa do svojho účtu vo Faktere.",
  "app.odomknutBiometriou": "Odomknúť biometriou",
  "app.nemateUcet": "Nemáte účet?",
  "app.zaregistrujteSa": "Zaregistrujte sa",
  "app.zabudnuteHeslo": "Zabudnuté heslo si obnovíte na faktero.sk.",
  "app.zamknute": "Faktero je zamknuté",
  "app.odomknitePokracujte": "Odomknite ho biometriou a pokračujte tam, kde ste skončili.",
  "app.pridatDalsiuFirmu": "Pridať ďalšiu firmu",
  "app.odvolatZiadost": "Odvolať žiadosť",
  "app.zFakturyPrecita": "Z faktúry sa prečíta dodávateľ, dátum, suma aj DPH. Údaje pred uložením skontrolujte.",
  "app.vyberteUhradu": "Vyberte spôsob úhrady",
  "app.povinne": "Povinné",
  "app.vyberteMoznost": "Vyberte jednu z možností — bez nej sa doklad uložiť nedá.",
  "app.hotovostnyDoklad": "Hotovostný doklad uberie zo stavu pokladne.",
  "app.fotkaDokladu": "Fotka dokladu",
  "app.prilozenePdf": "Priložené PDF",
  "app.odfotitZnova": "Odfotiť znova",
  "app.otvaram": "Otváram…",
  "app.skenerDokladov": "Skener dokladov",
  "app.ucet": "Účet",
  "app.email": "E-mail",
  "app.heslo": "Heslo",
  "app.vyberteFirmu": "Vyberte firmu",
  "app.doVybranejFirmy": "Doklady sa uložia do vybranej firmy",
  "app.staciNazov": "Stačí názov, ostatné sa dá doplniť neskôr",
  "app.fakturyADoklady": "Faktúry a doklady",
  "app.citamDoklad": "Čítam doklad…",
  "app.ukladamDoklad": "Ukladám doklad…",
  "app.nasnimatQr": "Nasnímať QR kód",
  "app.namierteNaBlocek": "Namierte na QR kód na bločku",
  "app.odfotitBlocek": "Odfotiť celý bloček",
  "app.qrNaFotke": "QR sa nájde aj na fotke",
  "app.vybratSubor": "Vybrať súbor",
  "app.pdfAleboObrazok": "PDF alebo obrázok faktúry",
  "app.stranySaSpoja": "Strany sa spoja do jedného PDF",
  "app.skontrolujteDoklad": "Skontrolujte doklad",
  "app.odfotitDoklad": "Odfotiť doklad",
  "app.papierovyDoklad": "Papierový doklad si treba odložiť aj tak — fotka ho nahradí",
  "app.vyplnteEmailHeslo": "Vyplňte e-mail aj heslo.",
  "app.prilohaNenahrata": "Prílohu sa nepodarilo nahrať, doklad uložím bez nej.",
  "app.dokladUlozeny": "Doklad uložený",
  "app.bezPripojeniaFirmy": "Bez pripojenia a v telefóne zatiaľ nie je uložený zoznam firiem. Otvorte appku raz s internetom.",
  "app.fakturaOdoslana": "Faktúra vystavená bez signálu je odoslaná.",
  "app.odoslanychOdlozenych": "Odoslaných odložených faktúr: {pocet}.",
  "app.jazdaUlozena": "Rozpoznaná jazda uložená",
  "app.jazdUlozenych": "Uložených {pocet} rozpoznaných jázd",
  "app.prihlasenieZlyhalo": "Prihlásenie zlyhalo.",
  "app.prihlasujem": "Prihlasujem…",
  "app.prihlasitSa": "Prihlásiť sa",
  "app.odomykam": "Odomykám…",
  "app.odomknut": "Odomknúť",
  "app.bezFirmy": "K tomuto účtu zatiaľ nepatrí žiadna firma. Bez nej nemajú doklady kam ísť — založte si ju rovno tu.",
  "app.blocekQr": "Bloček s QR kódom",
  "app.fakturaPdf": "Faktúra v PDF",
  "app.viacstranovyDoklad": "Viacstranový doklad",
  "app.nepodariloPrecitat": "Doklad sa nepodarilo prečítať.",
  "app.citanieZlyhalo": "Čítanie zlyhalo.",
  "app.spojenieStranZlyhalo": "Spojenie strán zlyhalo.",
  "app.bezSignaluOdosleSa": "Bez signálu — doklad sa odošle sám, keď bude pripojenie.",
  "app.spojenieVypadlo": "Spojenie vypadlo — doklad sa odošle sám neskôr.",
  "app.ulozenieZlyhalo": "Uloženie zlyhalo.",
  "app.odfotitPrvuStranu": "Odfotiť prvú stranu",
  "app.pridatDalsiuStranu": "Pridať ďalšiu stranu",
  "app.zatialStran": "Zatiaľ {pocet} strán",
  "app.dokladOdfotteCely": "Doklad odfoťte celý",
  "app.precitaneZDokladu": "Prečítané z dokladu",
  "app.ulozitDoklad": "Uložiť doklad",
  "app.neznamyPredajca": "Neznámy predajca",
  "app.zDokladuZatvorka": "(prečítané z dokladu)",
  "app.zTohoDph": "z toho DPH {suma}",
  "app.bezPripojeniaKratke": "bez pripojenia",
  "app.bezOdpovede": "bez odpovede",

  /* zrušenie účtu */
  "app.zrusenieNaplanovane": "Účet je naplánovaný na zrušenie {termin} — o {dni}.",
  "spolocne.den1": "deň",
  "spolocne.den2": "dni",
  "spolocne.den5": "dní",

  /* množné tvary */
  "app.cakajuceFaktury": "V telefóne čaká {pocet} na odoslanie. Pripojte sa a otvorte Vystavené faktúry — potom sa dá odhlásiť.",
  "spolocne.faktura1": "faktúra",
  "spolocne.faktura2": "faktúry",
  "spolocne.faktura5": "faktúr",

  /* appka — drobnosti */
  "app.odstranitStranu": "Odstrániť stranu {n}",

  /* ponuky — prázdny zoznam */
  "ponuky.ziadnePopis2": "Ponuku spravíte rovnako ako faktúru — a keď ju zákazník prijme, jedným ťuknutím z nej faktúra vznikne.",

  /* drobnosti — kroky a stavy */
  "nf.oprava": "Oprava {cislo}",
  "nf.fakturaCislo": "Faktúra {cislo}",
  "faktury.pracujem": "Pracujem…",
  "faktury.pripravujemPdf": "Pripravujem PDF…",
  "pd.odosielam": "Odosielam…",

  /* vystavené faktúry */
  "faktury.cakaNaOdoslanie": "Čaká na odoslanie: {pocet}",

  /* prijaté doklady — úhrada */
  "pd.uhradeneZUctuDna": "Uhradené z účtu {den}",
  "pd.uhradeneSkratka": "uhradené z účtu {den}",

  /* súhrny */
  "nf.zakladDph": "základ {zaklad} · DPH {dph}",
  "nf.odpocitaSa": "odpočíta sa {suma}",

  /* šablónové texty */
  "banka.kFakture": "k faktúre {cislo}",
  "banka.aktualizovane": "Aktualizované {ked}",
  "jz.bezi": "beží {trvanie}",
  "jz.ukladaSaNa": "Ukladá sa na {auto} — zmeníš výberom vozidla nižšie.",

  /* povolenia pre knihu jázd (Android) */
  "pov.nadpis": "Aby sa jazdy zapisovali samy",
  "pov.uvod": "Kniha jázd meria trasu na pozadí — aj vtedy, keď máte zhasnutý displej a telefón vo vrecku. Bez toho by sa kilometre nedorátali. Polohu používame len na výpočet jazdy, nikam ju neposielame.",
  "pov.poloha": "Poloha — aby sa dala jazda vôbec zmerať.",
  "pov.notifikacie": "Notifikácie — aby sa appka po jazde spýtala, či bola služobná.",
  "pov.pohyb": "Pohybové senzory — aby sa jazda rozpoznala rýchlejšie.",
  "pov.vzdy": "Poloha „Vždy“ — bez nej sa so zhasnutým displejom nemeria nič.",
  "pov.povolit": "Povoliť",
  "pov.pytamSa": "Pýtam sa…",
  "pov.neskor": "Neskôr",
  "pov.vzdyNastavenia": "Ostáva posledná vec: Android dovolí polohu „Vždy“ prepnúť len v nastaveniach. Otvoríme ich — vyberte Povolenia → Poloha → Povoliť vždy.",
  "pov.otvoritNastavenia": "Otvoriť nastavenia",
  "pov.hotovo": "Hotovo",
  "pov.zvysokNastavenia": "Toto sa oknom povoliť nedá — Android ich ponúka už len v nastaveniach aplikácie. Otvoríme ich, hľadajte Povolenia.",
  "app.spustam": "Spúšťam Faktero… ({faza}) · {balicek}",
  "app.startZasekol": "Štart sa zasekol na kroku „{faza}“.",
  "app.balicek": "balíček {peciatka}",
  "app.hotovoStran": "Hotovo — {pocet} strán",
  "app.poloziekZDokladu": "{pocet} položiek z dokladu",
  "nf.zFaktury": "Z faktúry {cislo}",
  "nf.polozkyZFaktury": "Položky z faktúry {cislo}",
  "nf.opravena": "Faktúra {cislo} opravená",
  "nf.icoS": "IČO {ico}",
  "nf.zuctovanaZaloha": "Zúčtovaná záloha {cislo}",
  "nf.dni": "{d} dní",
  "nf.zalohaCislo": "Záloha {cislo}",
  "nf.odoslaneNa": "Odoslané na {email}",
  "ponuky.vytvorena": "Ponuka {cislo} vytvorená.",
  "ponuky.vytvoritSuma": "Vytvoriť ponuku · {suma}",
  "ponuky.nazovSuboru": "Cenová ponuka {cislo}",
  "pd.odoslaneDoklady": "Odoslané doklady: {pocet}",
  "pd.cakaNaOdoslanie": "Čaká na odoslanie: {pocet}",
  "spolocne.doklad1": "doklad",
  "spolocne.doklad2": "doklady",
  "spolocne.doklad5": "dokladov",
  "pd.najdenePlatby": "Našli sme platby k dokladom ({pocet})",
  "pd.polozkyPocet": "Položky ({pocet})",
  "faktury.zmazana": "Faktúra {cislo} zmazaná",
  "faktury.upomienkaOdoslana": "{n}. upomienka odoslaná",
  "faktury.poslatUpomienku": "Poslať {n}. upomienku",
  "faktury.zatialOdoslane": "Zatiaľ odoslané: {pocet}",
  "faktury.naozajZmazat": "Naozaj zmazať faktúru {cislo}?",

  /* spodná lišta */
  "tab.prehlad": "Prehľad",
  "tab.doklady": "Doklady",
  "tab.jazdy": "Jazdy",

  /* prehľad a vzhľad */
  "ph.nazov": "Prehľad",
  "ph.neuhradene": "Neuhradené",
  "ph.poSplatnosti": "Po splatnosti",
  "ph.rychleAkcie": "Rýchle akcie",
  "ph.faktura": "Faktúra",
  "ph.skenovat": "Skenovať",
  "ph.zacatJazdu": "Začať jazdu",
  "ph.naVybavenie": "Na vybavenie",
  "ph.poslednaAktivita": "Posledná aktivita",
  "ph.fakturyPoSplatnosti": "{pocet} po splatnosti",
  "ph.dokladyNaKontrolu": "{pocet} čaká na kontrolu",
  "ph.jazdaNeukoncena": "Jazda nie je ukončená",
  "ph.vsetkoVybavene": "Nič nečaká",
  "ph.vsetkoVybavenePopis": "Faktúry sú uhradené a doklady skontrolované.",
  "ph.ziadnaAktivita": "Zatiaľ sa nič nedialo",
  "ph.ziadnaAktivitaPopis": "Prvá faktúra alebo doklad sa objavia tu.",
  "ph.fakturaCislo": "Faktúra {cislo}",
  "ph.doklad": "Prijatý doklad",
  "ph.dnes": "Dnes",
  "ph.vcera": "Včera",
  "ph.vzhlad": "Vzhľad",
  "ph.svetly": "Svetlý",
  "ph.tmavy": "Tmavý",
  "ph.podlaSystemu": "Podľa systému",

  /* filtre faktúr */
  "faktury.filterVsetky": "Všetky",
  "faktury.filterNeuhradene": "Neuhradené",
  "faktury.filterPoSplatnosti": "Po splatnosti",
  "faktury.filterUhradene": "Uhradené",
  "faktury.splatnostSkratka": "splatnosť {den}",
  "faktury.hladatKratke": "Hľadať",
  "faktury.filtre": "Filtre",

  /* skener — režimy */
  "sken.doklad": "Doklad",
  "sken.qrKod": "QR kód",
  "sken.naskenujteDoklad": "Naskenujte doklad",
  "sken.automaticky": "Doklad sa naskenuje automaticky",
  "sken.namierteQr": "Namierte na QR kód",
  "sken.qrSaPrecita": "Kód sa prečíta sám, netreba nič stláčať",
  "sken.nastavenie": "Nastavenie dokladu",

  /* banka — párovanie */
  "banka.sparovane": "Spárované",
  "banka.sparovat": "Spárovať",

  /* krokovník novej faktúry */
  "nf.krokOdberatel": "Odberateľ",
  "nf.krokPolozky": "Položky",
  "nf.krokKontrola": "Kontrola",
  "nf.nedavniOdberatelia": "Nedávni odberatelia",
  "nf.vsetciOdberatelia": "Všetci odberatelia",
  "nf.pokracovat": "Pokračovať",

  /* spoločné */
  "spolocne.spat": "Späť",
  "spolocne.ulozit": "Uložiť",
  "spolocne.zrusit": "Zrušiť",
  "spolocne.nacitavam": "Načítavam…",
  "spolocne.km": "km",

  /* samostatná appka Kniha jázd */
  "kj.nazov": "Kniha jázd",
  "kj.tabPrehlad": "Prehľad",
  "kj.tabHistoria": "História",
  "kj.tabVozidla": "Vozidlá",
  "kj.tentoMesiac": "Tento mesiac",
  "kj.sluzobne": "Služobné",
  "kj.sukromne": "Súkromné",
  "kj.posledneJazdy": "Posledné jazdy",
  "kj.vyberVozidla": "Vyberte vozidlo",
  "kj.vyberVozidlaPopis": "Kniha jázd sa vedie po vozidlách.",
  "kj.mojeVozidlo": "Moje vozidlo",
  "kj.mojeVozidloPopis": "Ťuknutím vyberiete auto, ktoré appka ponúkne pri jazde.",
  "kj.nastavitAkoMoje": "Nastaviť ako moje",
  "kj.jazd1": "jazda",
  "kj.jazd2": "jazdy",
  "kj.jazd5": "jázd",
  "kj.bezJazd": "Tento mesiac zatiaľ bez jazdy",
  "kj.bezJazdPopis": "Prvú spustíte zeleným tlačidlom dole.",
} as const;

export type Kluc = keyof typeof sk;
