/**
 * Slovenské znenie — **zdroj pravdy**.
 *
 * Kľúč je cesta k miestu, kde text stojí (`tab.faktury`), nie samotná veta.
 * Vetou ako kľúčom sa preklady rozsypú pri prvej oprave preklepu v origináli.
 *
 * Ostatné jazyky sú `Partial<typeof sk>` — čo v nich chýba, spadne na
 * slovenčinu. Chýbajúci preklad tak vyzerá ako chýbajúci preklad, nie ako
 * pokazená appka.
 */
export const sk = {
  /* spodná lišta */
  "tab.skener": "Skener",
  "tab.faktury": "Faktúry",
  "tab.vytvorit": "Vytvoriť",
  "tab.banka": "Banka",
  "tab.jazda": "Kniha jázd",
  "tab.navigacia": "Hlavná navigácia",

  /* bočný panel */
  "panel.nastavenia": "Nastavenia",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Zmeniť firmu",
  "panel.bezFirmy": "Bez firmy",
  "panel.prehladAgend": "Prehľad agend",
  "panel.vystaveneFaktury": "Vystavené faktúry",
  "panel.cenovePonuky": "Cenové ponuky",
  "panel.prijateDoklady": "Prijaté doklady",
  "panel.pomoc": "Pomoc",
  "panel.nastavenieAplikacie": "Nastavenie aplikácie",
  "panel.navody": "Návody k Fakteru",
  "panel.otvoriVPrehliadaci": "Otvorí sa v prehliadači",
  "panel.blocky": "Bločky a pokladňa",
  "panel.nahlasitChybu": "Nahlásiť chybu alebo návrh",
  "panel.otvoritNaWebe": "Otvoriť Faktero na webe",
  "panel.pravne": "Právne dokumenty",
  "panel.odhlasit": "Odhlásiť sa",
  "panel.zavriet": "Zavrieť",
  "panel.jazyk": "Jazyk",

  /* domovská obrazovka */
  "domov.novaFaktura": "Nová faktúra",
  "domov.novaFakturaPopis": "Odberateľ, položky, splatnosť — a rovno odoslať",
  "domov.vystaveneFaktury": "Vystavené faktúry",
  "domov.vystaveneFakturyPopis": "Kto ešte nezaplatil, PDF a odoslanie",
  "domov.blocek": "Bloček s QR kódom",
  "domov.blocekPopis": "Načíta sa z Finančnej správy aj s položkami",
  "domov.fakturaPdf": "Faktúra v PDF",
  "domov.fakturaPdfPopis": "Vyberte súbor z telefónu alebo z cloudu",
  "domov.viacstranovy": "Viacstranový doklad",
  "domov.viacstranovyPopis": "Strana po strane, uloží sa ako jedno PDF",
  "domov.prijateDoklady": "Prijaté doklady",
  "domov.prijateDokladyPopis": "Bločky a faktúry, ktoré ste už naskenovali",
  "domov.pohybyNaUcte": "Pohyby na účte",
  "domov.pohybyNaUctePopis": "Či prišli peniaze — zostatok a posledné platby",
  "domov.novaJazda": "Nová jazda",
  "domov.novaJazdaPopis": "Kilometre odmeria telefón, stačí štart a stop",

  /* kniha jázd — história */
  "jazdy.historia": "História jázd",
  "jazdy.charakter": "Charakter jazdy",
  "jazdy.sluzobna": "Služobná",
  "jazdy.sukromna": "Súkromná",
  "jazdy.oznacenaSukromna": "Označená ako súkromná.",
  "jazdy.oznacenaSluzobna": "Označená ako služobná.",
  "jazdy.jazda": "Jazda",
  "jazdy.spolu": "Spolu",
  "jazdy.starsie": "Staršie jazdy",
  "jazdy.ziadne": "Zatiaľ žiadne jazdy",

  /* cenové ponuky */
  "ponuky.nazov": "Cenové ponuky",
  "ponuky.nova": "Nová ponuka",
  "ponuky.novaDlha": "Nová cenová ponuka",
  "ponuky.ziadne": "Zatiaľ žiadna cenová ponuka",
  "ponuky.ziadnePopis":
    "Ponuku spravíte rovnako ako faktúru — a keď ju zákazník prijme, jedným ťuknutím z nej faktúra vznikne.",
  "ponuky.vytvorit": "Vytvoriť ponuku",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Zdieľať",
  "ponuky.odoslat": "Odoslať",
  "ponuky.naFakturu": "Na faktúru",
  "ponuky.platiDo": "platí do",
  "ponuky.stav.vyfakturovana": "Vyfakturovaná",
  "ponuky.stav.zamietnuta": "Zamietnutá",
  "ponuky.stav.prijata": "Prijatá",
  "ponuky.stav.poPlatnosti": "Po platnosti",
  "ponuky.stav.odoslana": "Odoslaná",
  "ponuky.stav.navrh": "Návrh",
  "ponuky.odberatel": "Odberateľ",
  "ponuky.polozky": "Položky",
  "ponuky.pridajPolozku": "Pridať položku",
  "ponuky.vystavena": "Vystavená",
  "ponuky.poznamka": "Poznámka",
  "ponuky.zaklad": "Základ",
  "ponuky.dph": "DPH",
  "ponuky.hladatOdberatela": "Hľadať odberateľa…",
  "ponuky.novyOdberatel": "Nový odberateľ",
  "ponuky.nikNenajdeny": "Nikto sa nenašiel.",
  "ponuky.zmenit": "zmeniť",

  "domov.skupina.fakturacia": "Fakturácia",
  "domov.skupina.skenovanie": "Skenovanie dokladov",
  "domov.skupina.banka": "Banka",
  "domov.skupina.jazdy": "Kniha jázd",

  /* vystavené faktúry */
  "faktury.nazov": "Vystavené faktúry",
  "faktury.hladat": "Hľadať číslo alebo odberateľa",
  "faktury.nacitavam": "Načítavam faktúry…",
  "faktury.ziadne": "Zatiaľ žiadne faktúry",
  "faktury.vystavPrvu": "Vystaviť prvú faktúru",
  "faktury.nicSaNenaslo": "Nič sa nenašlo",
  "faktury.bezOdberatela": "Bez odberateľa",
  "faktury.stav.navrh": "Návrh",
  "faktury.stav.vystavena": "Vystavená",
  "faktury.stav.odoslana": "Odoslaná",
  "faktury.stav.uhradena": "Uhradená",
  "faktury.stav.neuhradena": "Neuhradená",
  "faktury.stav.splatna": "Splatná",
  "faktury.stav.poSplatnosti": "Po splatnosti",
  "faktury.stav.stornovana": "Stornovaná",
  "faktury.otvoritPdf": "Otvoriť PDF",
  "faktury.zdielat": "Zdieľať faktúru",
  "faktury.zdielatPopis": "Pošlite ju cez WhatsApp, Messenger alebo uložte do súborov",
  "faktury.poslatEmailom": "Poslať e-mailom",
  "faktury.oznacitUhradenu": "Označiť ako uhradenú",
  "faktury.oznacitPopis": "Keď platba prišla mimo párovania s bankou",
  "faktury.oznacenaUhradena": "Označená ako uhradená",
  "faktury.upravit": "Upraviť faktúru",
  "faktury.upravitPopis": "Položky, dátumy aj poznámka",
  "faktury.zmazat": "Zmazať faktúru",
  "faktury.zmazatPopis":
    "Zmizne zo zoznamu, ale číslo ostáva obsadené — v číselnom rade nevznikne diera.",
  "faktury.zmazatKratke": "Zmazať",
  "faktury.ponechat": "Ponechať",
  "faktury.mazem": "Mažem…",
  "faktury.naPrezretie": "Faktúra na prezretie",
  "faktury.bezPripojenia": "Bez pripojenia — zobrazené naposledy načítané faktúry.",
  "faktury.bezPripojeniaNacitanie": "Bez pripojenia sa faktúry nedajú načítať",
  "faktury.odlozenaVystavena": "Odložená faktúra je vystavená.",
  "faktury.odosluSaSamy": "Odošlú sa samy, len čo bude signál. Netreba na to myslieť.",
  "faktury.chybaNacitania": "Faktúry sa nepodarilo načítať.",
  "faktury.chybaMazania": "Faktúru sa nepodarilo zmazať.",
  "faktury.chybaPdf": "PDF sa nepodarilo pripraviť.",
  "faktury.chybaZdielania": "Zdieľanie zlyhalo.",
  "faktury.chybaUpomienky": "Upomienku sa nepodarilo odoslať.",

  /* spoločné */
  "spolocne.spat": "Späť",
  "spolocne.ulozit": "Uložiť",
  "spolocne.zrusit": "Zrušiť",
  "spolocne.nacitavam": "Načítavam…",
  "spolocne.km": "km",
} as const;

export type Kluc = keyof typeof sk;
