/**
 * Slovenské znenie — **zdroj pravdy**.
 *
 * Kľúč je cesta k miestu, kde text stojí (`tab.faktury`), nie samotná veta.
 * Vetou ako kľúčom sa preklady rozsypú pri prvej oprave preklepu v origináli.
 *
 * Ostatné jazyky sú `Partial<typeof sk>` — čo v nich chýba, spadne na
 * slovenčinu. Chýbajúci preklad tak vyzerá ako chýbajúci preklad, nie ako
 * pokazená appka.
 */
export const sk = {
  /* spodná lišta */
  "tab.skener": "Skener",
  "tab.faktury": "Faktúry",
  "tab.vytvorit": "Vytvoriť",
  "tab.banka": "Banka",
  "tab.jazda": "Kniha jázd",
  "tab.navigacia": "Hlavná navigácia",

  /* bočný panel */
  "panel.nastavenia": "Nastavenia",
  "panel.firma": "Firma",
  "panel.zmenitFirmu": "Zmeniť firmu",
  "panel.bezFirmy": "Bez firmy",
  "panel.prehladAgend": "Prehľad agend",
  "panel.vystaveneFaktury": "Vystavené faktúry",
  "panel.cenovePonuky": "Cenové ponuky",
  "panel.prijateDoklady": "Prijaté doklady",
  "panel.pomoc": "Pomoc",
  "panel.nastavenieAplikacie": "Nastavenie aplikácie",
  "panel.navody": "Návody k Fakteru",
  "panel.otvoriVPrehliadaci": "Otvorí sa v prehliadači",
  "panel.blocky": "Bločky a pokladňa",
  "panel.nahlasitChybu": "Nahlásiť chybu alebo návrh",
  "panel.otvoritNaWebe": "Otvoriť Faktero na webe",
  "panel.pravne": "Právne dokumenty",
  "panel.odhlasit": "Odhlásiť sa",
  "panel.zavriet": "Zavrieť",
  "panel.jazyk": "Jazyk",

  /* domovská obrazovka */
  "domov.novaFaktura": "Nová faktúra",
  "domov.novaFakturaPopis": "Odberateľ, položky, splatnosť — a rovno odoslať",
  "domov.vystaveneFaktury": "Vystavené faktúry",
  "domov.vystaveneFakturyPopis": "Kto ešte nezaplatil, PDF a odoslanie",
  "domov.blocek": "Bloček s QR kódom",
  "domov.blocekPopis": "Načíta sa z Finančnej správy aj s položkami",
  "domov.fakturaPdf": "Faktúra v PDF",
  "domov.fakturaPdfPopis": "Vyberte súbor z telefónu alebo z cloudu",
  "domov.viacstranovy": "Viacstranový doklad",
  "domov.viacstranovyPopis": "Strana po strane, uloží sa ako jedno PDF",
  "domov.prijateDoklady": "Prijaté doklady",
  "domov.prijateDokladyPopis": "Bločky a faktúry, ktoré ste už naskenovali",
  "domov.pohybyNaUcte": "Pohyby na účte",
  "domov.pohybyNaUctePopis": "Či prišli peniaze — zostatok a posledné platby",
  "domov.novaJazda": "Nová jazda",
  "domov.novaJazdaPopis": "Kilometre odmeria telefón, stačí štart a stop",

  /* kniha jázd — história */
  "jazdy.historia": "História jázd",
  "jazdy.charakter": "Charakter jazdy",
  "jazdy.sluzobna": "Služobná",
  "jazdy.sukromna": "Súkromná",
  "jazdy.oznacenaSukromna": "Označená ako súkromná.",
  "jazdy.oznacenaSluzobna": "Označená ako služobná.",
  "jazdy.jazda": "Jazda",
  "jazdy.spolu": "Spolu",
  "jazdy.starsie": "Staršie jazdy",
  "jazdy.ziadne": "Zatiaľ žiadne jazdy",

  /* cenové ponuky */
  "ponuky.nazov": "Cenové ponuky",
  "ponuky.nova": "Nová ponuka",
  "ponuky.novaDlha": "Nová cenová ponuka",
  "ponuky.ziadne": "Zatiaľ žiadna cenová ponuka",
  "ponuky.ziadnePopis":
    "Ponuku spravíte rovnako ako faktúru — a keď ju zákazník prijme, jedným ťuknutím z nej faktúra vznikne.",
  "ponuky.vytvorit": "Vytvoriť ponuku",
  "ponuky.pdf": "PDF",
  "ponuky.zdielat": "Zdieľať",
  "ponuky.odoslat": "Odoslať",
  "ponuky.naFakturu": "Na faktúru",
  "ponuky.platiDo": "platí do",
  "ponuky.stav.vyfakturovana": "Vyfakturovaná",
  "ponuky.stav.zamietnuta": "Zamietnutá",
  "ponuky.stav.prijata": "Prijatá",
  "ponuky.stav.poPlatnosti": "Po platnosti",
  "ponuky.stav.odoslana": "Odoslaná",
  "ponuky.stav.navrh": "Návrh",
  "ponuky.odberatel": "Odberateľ",
  "ponuky.polozky": "Položky",
  "ponuky.pridajPolozku": "Pridať položku",
  "ponuky.vystavena": "Vystavená",
  "ponuky.poznamka": "Poznámka",
  "ponuky.zaklad": "Základ",
  "ponuky.dph": "DPH",
  "ponuky.hladatOdberatela": "Hľadať odberateľa…",
  "ponuky.novyOdberatel": "Nový odberateľ",
  "ponuky.nikNenajdeny": "Nikto sa nenašiel.",
  "ponuky.zmenit": "zmeniť",

  "domov.skupina.fakturacia": "Fakturácia",
  "domov.skupina.skenovanie": "Skenovanie dokladov",
  "domov.skupina.banka": "Banka",
  "domov.skupina.jazdy": "Kniha jázd",

  /* vystavené faktúry */
  "faktury.nazov": "Vystavené faktúry",
  "faktury.hladat": "Hľadať číslo alebo odberateľa",
  "faktury.nacitavam": "Načítavam faktúry…",
  "faktury.ziadne": "Zatiaľ žiadne faktúry",
  "faktury.vystavPrvu": "Vystaviť prvú faktúru",
  "faktury.nicSaNenaslo": "Nič sa nenašlo",
  "faktury.bezOdberatela": "Bez odberateľa",
  "faktury.stav.navrh": "Návrh",
  "faktury.stav.vystavena": "Vystavená",
  "faktury.stav.odoslana": "Odoslaná",
  "faktury.stav.uhradena": "Uhradená",
  "faktury.stav.neuhradena": "Neuhradená",
  "faktury.stav.splatna": "Splatná",
  "faktury.stav.poSplatnosti": "Po splatnosti",
  "faktury.stav.stornovana": "Stornovaná",
  "faktury.otvoritPdf": "Otvoriť PDF",
  "faktury.zdielat": "Zdieľať faktúru",
  "faktury.zdielatPopis": "Pošlite ju cez WhatsApp, Messenger alebo uložte do súborov",
  "faktury.poslatEmailom": "Poslať e-mailom",
  "faktury.oznacitUhradenu": "Označiť ako uhradenú",
  "faktury.oznacitPopis": "Keď platba prišla mimo párovania s bankou",
  "faktury.oznacenaUhradena": "Označená ako uhradená",
  "faktury.upravit": "Upraviť faktúru",
  "faktury.upravitPopis": "Položky, dátumy aj poznámka",
  "faktury.zmazat": "Zmazať faktúru",
  "faktury.zmazatPopis":
    "Zmizne zo zoznamu, ale číslo ostáva obsadené — v číselnom rade nevznikne diera.",
  "faktury.zmazatKratke": "Zmazať",
  "faktury.ponechat": "Ponechať",
  "faktury.mazem": "Mažem…",
  "faktury.naPrezretie": "Faktúra na prezretie",
  "faktury.bezPripojenia": "Bez pripojenia — zobrazené naposledy načítané faktúry.",
  "faktury.bezPripojeniaNacitanie": "Bez pripojenia sa faktúry nedajú načítať",
  "faktury.odlozenaVystavena": "Odložená faktúra je vystavená.",
  "faktury.odosluSaSamy": "Odošlú sa samy, len čo bude signál. Netreba na to myslieť.",
  "faktury.chybaNacitania": "Faktúry sa nepodarilo načítať.",
  "faktury.chybaMazania": "Faktúru sa nepodarilo zmazať.",
  "faktury.chybaPdf": "PDF sa nepodarilo pripraviť.",
  "faktury.chybaZdielania": "Zdieľanie zlyhalo.",
  "faktury.chybaUpomienky": "Upomienku sa nepodarilo odoslať.",

  /* nová faktúra */
  "nf.komuFakturujete": "Komu fakturujete?",
  "nf.zaCoFakturujete": "Za čo fakturujete?",
  "nf.skontrolujte": "Skontrolujte faktúru",
  "nf.skontrolujteZalohovu": "Skontrolujte zálohovú",
  "nf.krok": "Krok {n} z 3",
  "nf.krokZalohova": "Krok 1 z 3 · zálohová",
  "nf.faktura": "Faktúra",
  "nf.zalohova": "Zálohová",
  "nf.odberatel": "Odberateľ",
  "nf.hladatOdberatela": "Hľadať odberateľa",
  "nf.novyOdberatel": "Nový odberateľ",
  "nf.ziadnyOdberatel": "Zatiaľ nemáte žiadneho odberateľa.",
  "nf.nicSaNenaslo": "Nič sa nenašlo.",
  "nf.nacitavamOdberatelov": "Načítavam odberateľov…",
  "nf.nazov": "Názov",
  "nf.zadajteNazov": "Zadajte názov odberateľa.",
  "nf.podlaIco": "Podľa IČO sa doplní názov aj adresa",
  "nf.hladamVRegistri": "Hľadám v registri…",
  "nf.udajeDoplnene": "Údaje doplnené z registra",
  "nf.psc": "PSČ",
  "nf.email": "Na tento e-mail sa dá faktúra hneď odoslať",
  "nf.odberatelPridany": "Odberateľ pridaný",
  "nf.chybaOdberatela": "Odberateľa sa nepodarilo uložiť.",
  "nf.polozky": "Položky",
  "nf.nazovPolozky": "Názov položky",
  "nf.mnozstvo": "Množstvo",
  "nf.pridajtePolozku": "Pridajte položku",
  "nf.odstranitPolozku": "Odstrániť položku",
  "nf.zCennika": "Z cenníka",
  "nf.vlastna": "Vlastná",
  "nf.cennik": "Cenník",
  "nf.hladatPolozku": "Hľadať položku",
  "nf.zopakovatPoslednu": "Zopakovať poslednú faktúru",
  "nf.splatnost": "Splatnosť",
  "nf.splatnostSkor": "Splatnosť nemôže byť skôr ako vystavenie.",
  "nf.sposobUhrady": "Spôsob úhrady",
  "nf.hotovost": "Hotovosť",
  "nf.poznamkaNad": "Poznámka nad položkami",
  "nf.poznamkaPod": "Poznámka pod položkami",
  "nf.priklad": "Napríklad: podľa objednávky č. 2026/114",
  "nf.zaklad": "Základ",
  "nf.naUhradu": "Na úhradu",
  "nf.dalej": "Ďalej",
  "nf.zrusit": "Zrušiť",
  "nf.zavriet": "Zavrieť",
  "nf.ulozitPokracovat": "Uložiť a pokračovať",
  "nf.ulozitZmeny": "Uložiť zmeny",
  "nf.ukladam": "Ukladám…",
  "nf.ukladamZmeny": "Ukladám zmeny…",
  "nf.vystavit": "Vystaviť faktúru",
  "nf.vystavitZalohovu": "Vystaviť zálohovú faktúru",
  "nf.vystavujem": "Vystavujem faktúru…",
  "nf.vystavena": "Faktúra vystavená",
  "nf.maCislo": "Faktúra má pridelené číslo",
  "nf.odlozena": "Faktúra je odložená v telefóne",
  "nf.naPrezretie": "Faktúra na prezretie",
  "nf.otvoritPdf": "Otvoriť PDF",
  "nf.zdielat": "Zdieľať faktúru",
  "nf.zdielatPopis": "Pošlite ju cez WhatsApp, Messenger alebo uložte do súborov",
  "nf.poslatEmailom": "Poslať e-mailom",
  "nf.odoslane": "Odoslané",
  "nf.odosielam": "Odosielam faktúru…",
  "nf.bezEmailu":
    "Odberateľ nemá e-mail, tak sa faktúra nedá odoslať. Doplňte ho v karte odberateľa.",
  "nf.zalohy": "Nezúčtované zálohy tohto odberateľa",
  "nf.hladamZalohy": "Hľadám zálohy…",
  "nf.ziadnaZaloha": "Žiadna zálohová faktúra na zúčtovanie",
  "nf.pridatZalohovu": "Pridať zálohovú faktúru",
  "nf.bezPripojenia": "Bez pripojenia — pracujem s naposledy načítanými údajmi.",
  "nf.bezPripojeniaVystavit":
    "Bez pripojenia a bez uložených odberateľov sa faktúra vystaviť nedá. Otvorte túto obrazovku raz s internetom.",
  "nf.zalohovaBezPripojenia": "Zálohovú faktúru sa bez pripojenia vystaviť nedá.",
  "nf.opravaBezPripojenia": "Na opravu faktúry treba pripojenie.",
  "nf.chybaPodkladov": "Podklady sa nepodarilo načítať.",
  "nf.chybaNacitania": "Faktúru sa nepodarilo načítať.",
  "nf.chybaVystavenia": "Faktúru sa nepodarilo vystaviť.",
  "nf.chybaZmien": "Zmeny sa nepodarilo uložiť.",
  "nf.chybaPdf": "PDF sa nepodarilo pripraviť.",
  "nf.chybaZdielania": "Zdieľanie zlyhalo.",

  /* prijaté doklady a banka */
  "pd.nazov": "Prijaté doklady",
  "pd.hladat": "Hľadať dodávateľa alebo číslo",
  "pd.nacitavam": "Načítavam doklady…",
  "pd.ziadne": "Zatiaľ žiadne doklady",
  "pd.ziadnePopis": "Naskenované bločky a faktúry sa objavia tu.",
  "pd.nicSaNenaslo": "Nič sa nenašlo",
  "pd.skusteInak": "Skúste hľadať inak.",
  "pd.bezDodavatela": "Bez dodávateľa",
  "pd.neprecitany": "Neprečítaný doklad",
  "pd.zFinancnejSpravy": "Z Finančnej správy",
  "pd.sQrKodom": "· s QR kódom",
  "pd.cisloDokladu": "Číslo dokladu",
  "pd.poznamka": "Poznámka",
  "pd.sposobUhrady": "Spôsob úhrady",
  "pd.hotovost": "Hotovosť",
  "pd.kartou": "Kartou",
  "pd.prevodom": "Prevodom",
  "pd.sposobZmeneny": "Spôsob úhrady zmenený",
  "pd.otvoritPdf": "Otvoriť PDF",
  "pd.nacitavamPrilohu": "Načítavam prílohu…",
  "pd.presunut": "Presunúť medzi prijaté faktúry",
  "pd.presuvam": "Presúvam…",
  "pd.presunuty": "Doklad je medzi prijatými faktúrami.",
  "pd.zmazat": "Zmazať doklad",
  "pd.zmazatKratke": "Zmazať",
  "pd.naozajZmazat": "Naozaj zmazať tento doklad?",
  "pd.nedaSaVratit": "Vrátiť sa to nedá.",
  "pd.zmazany": "Doklad zmazaný",
  "pd.ponechat": "Ponechať",
  "pd.zrusit": "Zrušiť",
  "pd.sparovat": "Spárovať",
  "pd.anoPatriKSebe": "Áno, patrí k sebe",
  "pd.uhradenyZUctu": "Doklad označený za uhradený z účtu.",
  "pd.parovanieZrusene": "Párovanie zrušené.",
  "pd.chybaParovania": "Spárovať sa to nepodarilo.",
  "pd.chybaZrusenia": "Zrušiť sa to nepodarilo.",
  "pd.chybaNacitania": "Doklady sa nepodarilo načítať.",
  "pd.bezPripojenia": "Bez pripojenia sa doklady nedajú načítať",
  "pd.odlozeneOdoslu": "Odložené bločky sa odošlú samy, len čo sa vráti signál.",
  "pd.bezSignalu": "Zatiaľ bez signálu — skúsim to znova sám.",
  "pd.zahodit": "Zahodiť odložený doklad",
  "pd.odoslat": "Odoslať",
  "banka.ucet": "Účet",
  "banka.vsetky": "Všetky",
  "banka.nacitavam": "Načítavam pohyby…",
  "banka.ziadnePohyby": "Zatiaľ žiadne pohyby",
  "banka.stiahnut": "Stiahnuť z banky",
  "banka.stahujem": "Sťahujem z banky…",
  "banka.ziadneNove": "Žiadne nové pohyby.",
  "banka.prijataPlatba": "Prijatá platba",
  "banka.odchadzajucaPlatba": "Odchádzajúca platba",
  "banka.dnes": "Dnes",
  "banka.vcera": "Včera",
  "banka.nesynchronizovane": "zatiaľ nesynchronizované",
  "banka.bezUctu": "Firma nemá pripojený bankový účet",
  "banka.pripojenieNaWebe":
    "Účet sa pripája na webe — banka pri tom vyžaduje prihlásenie a súhlas, ktorý sa v telefóne dobre vybaviť nedá.",
  "banka.bezPripojenia": "Bez pripojenia sa účty nedajú načítať",
  "banka.lenSoSignalom":
    "Zostatky a pohyby sa dajú pozrieť, len keď je signál — z telefónu sa nikam neukladajú.",
  "banka.neodpovedala": "Banka teraz neodpovedala. Skúste to o chvíľu.",
  "banka.chybaNacitania": "Pohyby sa nepodarilo načítať.",

  /* spoločné */
  "spolocne.spat": "Späť",
  "spolocne.ulozit": "Uložiť",
  "spolocne.zrusit": "Zrušiť",
  "spolocne.nacitavam": "Načítavam…",
  "spolocne.km": "km",
} as const;

export type Kluc = keyof typeof sk;
