// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/** Overené relácie (session_id) → do kedy výsledok platí (ms). */
const overeneRelacie = new Map<string, number>();

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    /*
      Podpis tokenu nestačí: zakázaný alebo zmazaný účet a relácia zrušená
      cez „Odhlásiť všade“ by prešli až do vypršania tokenu (hodinu). A kto má
      zapnuté dvojfaktorové overenie, smie na server až s reláciou aal2 —
      serverové funkcie píšu aj cez admin klienta, ktorý `mfa_ok()` v RLS
      obchádza. Dobrý výsledok si pamätáme minútu, aby sa DB nepýtala pri
      každom volaní.
    */
    const kluc = String((data.claims as any).session_id ?? data.claims.sub);
    const pamat = overeneRelacie.get(kluc);
    if (!pamat || pamat < Date.now()) {
      const { data: stav, error: stavErr } = await supabase.rpc("stav_relacie" as any);
      if (stavErr || !stav) throw new Error("Unauthorized: overenie relácie zlyhalo");
      const st = stav as { aktivna?: boolean; mfa_ok?: boolean };
      if (!st.aktivna) throw new Error("Unauthorized: relácia už neplatí, prihláste sa znova");
      if (!st.mfa_ok) throw new Error("Unauthorized: zadajte kód dvojfaktorového overenia");
      overeneRelacie.set(kluc, Date.now() + 60_000);
      if (overeneRelacie.size > 10_000) overeneRelacie.clear();
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
