// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * V zabalenej mobilnej appke beží stránka na `capacitor://localhost`.
 *
 * Supabase si prihlásenie zamyká cez `navigator.locks`, aby si ho neprepísali
 * dve karty prehliadača. Vo WebView s vlastnou schémou sa ten zámok nedočká
 * uvoľnenia a `getSession()` neodpovie **vôbec** — nie chybou, ale tichom.
 * Appka potom navždy visela na „Spúšťam Faktero…".
 *
 * V telefóne žiadne druhé okno neexistuje, takže sa použije jednoduchý zámok
 * v pamäti. Na webe ostáva pôvodný, tam viac kariet zmysel dáva.
 */
/**
 * Prístup k `localStorage` vie vo WebView vyhodiť (SecurityError), a keďže sa
 * klient vyrába pri prvom použití, taká výnimka zhodí celý štart appky.
 */
function bezpecneUlozisko(): Storage | undefined {
  try {
    if (typeof window === "undefined") return undefined;
    window.localStorage.getItem("faktero.test");
    return window.localStorage;
  } catch {
    return undefined;
  }
}

function jeVlastnaSchema(): boolean {
  if (typeof window === "undefined") return false;
  return !/^https?:$/.test(window.location.protocol);
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: bezpecneUlozisko(),
      persistSession: true,
      autoRefreshToken: true,
      ...(jeVlastnaSchema() ? { lock: processLock } : {}),
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
