// This file is automatically generated. Do not edit it directly.
import { createClient, processLock } from "@supabase/supabase-js";
import type { Database } from "./types";
import { trvaleUlozisko } from "@/lib/mobile/trvale-ulozisko";

/**
 * V zabalenej mobilnej appke beží stránka na `capacitor://localhost`.
 *
 * Supabase si prihlásenie zamyká cez `navigator.locks`, aby si ho neprepísali
 * dve karty prehliadača. Vo WebView s vlastnou schémou sa ten zámok nedočká
 * uvoľnenia a `getSession()` neodpovie **vôbec** — nie chybou, ale tichom.
 * Appka potom navždy visela na „Spúšťam Faktero…".
 *
 * V telefóne žiadne druhé okno neexistuje, takže sa použije jednoduchý zámok
 * v pamäti. Na webe ostáva pôvodný, tam viac kariet zmysel dáva.
 */
/**
 * Prístup k `localStorage` vie vo WebView vyhodiť (SecurityError), a keďže sa
 * klient vyrába pri prvom použití, taká výnimka zhodí celý štart appky.
 */
function bezpecneUlozisko(): Storage | undefined {
  try {
    if (typeof window === "undefined") return undefined;
    window.localStorage.getItem("faktero.test");
    return window.localStorage;
  } catch {
    return undefined;
  }
}

/**
 * Beží stránka v zabalenej appke?
 *
 * Pozeralo sa to podľa schémy — všetko okrem `http(s)` je appka. Na iOS to
 * sedí (`capacitor://localhost`), **na Androide nie**: ten servíruje appku
 * cez `https://localhost`, takže sa tvárila ako web. Prihlásenie potom
 * skončilo v prehliadačovom úložisku, ktoré zatvorenie appky neprežije —
 * a človek sa po každom reštarte prihlasoval odznova.
 *
 * Rozhoduje preto Capacitor sám. Globálny objekt je vo WebView k dispozícii
 * hneď, ešte pred prvým `await`, a na webe jednoducho nie je.
 */
function jeVTelefone(): boolean {
  if (typeof window === "undefined") return false;
  const cap = (window as { Capacitor?: { isNativePlatform?: () => boolean } }).Capacitor;
  if (cap?.isNativePlatform?.()) return true;
  // Staršie balíčky bez `window.Capacitor` — vlastná schéma je vtedy istá stopa.
  return !/^https?:$/.test(window.location.protocol);
}

/**
 * Kde má bývať prihlásenie.
 *
 * V telefóne **nie v prehliadačovom úložisku**: to vo WebView zatvorenie appky
 * neprežije a po znovuotvorení bola relácia preč. Appka potom ponúkla
 * prihlásenie — a bez signálu sa prihlásiť nedá, takže sa offline nedalo robiť
 * vôbec nič. Natívne úložisko prežije všetko okrem odinštalovania.
 *
 * Na webe ostáva `localStorage`; tam je v poriadku a natívne neexistuje.
 */
function ulozisko() {
  if (!jeVTelefone()) return bezpecneUlozisko();
  try {
    // Načítava sa staticky, aby bolo k dispozícii hneď pri vzniku klienta —
    // Supabase si úložisko pýta ešte pred prvým `await`.
    return trvaleUlozisko;
  } catch {
    return bezpecneUlozisko();
  }
}

/**
 * Ako dlho sa čaká na zámok prihlásenia, kým sa naň vykašle.
 *
 * Supabase si prihlásenie zamyká cez `navigator.locks`, aby si ho neprepísali
 * dve karty. Zámok ale nemá strop čakania: keď ho iná karta drží a neuvoľní —
 * uspatý notebook, karta bez signálu, karta, ktorú prehliadač zmrazil —
 * `signInWithPassword()` **neodpovie vôbec**. Nie chybou, tichom. Navonok to
 * vyzerá tak, že sa tlačidlo točí a nič nenapíše, a človek sa nemá ako dostať
 * dnu, aj keď má správne heslo.
 *
 * Po piatich sekundách sa preto pokračuje bez zámku. Dve karty, ktoré si
 * naraz obnovujú prihlásenie, sú menšie zlo než karta, ktorá sa netočí do
 * skonania sveta.
 */
const CAKANIE_NA_ZAMOK_MS = 5000;

async function zamokSoStropom<R>(
  meno: string,
  _cakaj: number,
  praca: () => Promise<R>,
): Promise<R> {
  const zamky = typeof navigator !== "undefined" ? navigator.locks : undefined;
  if (!zamky?.request) return praca();

  const ovladac = new AbortController();
  const cas = setTimeout(() => ovladac.abort(), CAKANIE_NA_ZAMOK_MS);
  try {
    return await zamky.request(meno, { mode: "exclusive", signal: ovladac.signal }, () => praca());
  } catch (e) {
    if ((e as Error)?.name !== "AbortError") throw e;
    console.warn(`[auth] zámok „${meno}" sa neuvoľnil do 5 s — pokračujem bez neho`);
    return praca();
  } finally {
    clearTimeout(cas);
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: ulozisko(),
      persistSession: true,
      autoRefreshToken: true,
      lock: jeVTelefone() ? processLock : zamokSoStropom,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
