name: Deploy to faktero.sk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy cez SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: patrik
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/faktero-invoice-hub
            git pull
            npm install
            npm run build
            pm2 restart faktero
